'use client'
import { useState } from 'react'
import { ProtocolExperiment } from '../protocol/experiment'
import { AnswerFields } from '../protocol/answer-fields'
import { EventTimeline } from '../protocol/event-timeline'
import { checkRegisterHistory } from './history'
import { exercises, lastRead, quorumLesson, replicaLesson, scenarioCommands, scenariosFor, type LabId } from './lesson'
import { canDeliver, MAX_COMMANDS, nodes, runModel, tagLabel, type ClientId, type Command, type Config, type NodeId, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
const actors = [{ id: 'X', label: '客户端 X' }, { id: 'A', label: '副本 A' }, { id: 'B', label: '副本 B' }, { id: 'C', label: '副本 C' }, { id: 'Y', label: '客户端 Y' }]
const historyLabels = { linearizable: '存在合法顺序', violation: '历史存在反例', incomplete: '历史未完整' }
const messageLabels = { put: '写入请求', replicate: '主从复制', ack: '写入确认', get: '读取请求', reply: '读取回复', repair: '读修复' }
function Live({ s, c, act, disabled }: { s: State; c: Config; act: (command: Command) => void; disabled: boolean }) {
  const [client, setClient] = useState<ClientId>('X'); const [value, setValue] = useState('v1'); const [target, setTarget] = useState<NodeId>('B')
  const h = checkRegisterHistory(s.operations)
  return <><section className={styles.metrics}><div><span>最后读取返回</span><strong data-testid="replica-read">{lastRead(s)?.result ?? 'pending'}</strong></div><div><span>已返回用户操作</span><strong>{s.operations.filter((op) => op.returned !== null).length} / {s.operations.length}</strong></div><div><span>有限历史检查</span><strong data-testid="replica-history">{historyLabels[h.status]}</strong></div><div><span>在途/等待消息</span><strong>{s.messages.filter((m) => m.status === 'network' || m.status === 'held').length}</strong></div></section>
    <section className={styles.panel}><h2>发起用户操作</h2><div className={styles.settings}><label>客户端<select aria-label="复制客户端" value={client} onChange={(e) => setClient(e.target.value as ClientId)}><option>X</option><option>Y</option></select></label><label>写入值<input aria-label="复制写入值" value={value} maxLength={30} onChange={(e) => setValue(e.target.value)} /></label><label>读取副本<select aria-label="读取副本" value={target} disabled={c.mode === 'quorum' || c.readPolicy === 'primary'} onChange={(e) => setTarget(e.target.value as NodeId)}>{nodes.map((id) => <option key={id}>{id}</option>)}</select></label></div><div className={styles.faultActions}><button disabled={disabled || s.operations.length >= 8} onClick={() => act({ type: 'write', client, value })}>发起写入</button><button disabled={disabled || s.operations.length >= 8} onClick={() => act({ type: 'read', client, target })}>发起读取</button></div><p className={styles.note}>{s.clients.map((x) => `${x.id} 已观察最低版本 ${tagLabel(x.minimum)} / 本地计数 ${x.clock}`).join('；')}</p></section>
    <div className={styles.actors}>{s.replicas.map((r) => <section className={styles.actor} key={r.id}><h2>副本 {r.id}</h2><strong data-testid={`replica-${r.id}`}>{r.current.value} @ {tagLabel(r.current.tag)}</strong><p>{r.online ? '运行中' : '已崩溃'} · {r.isolated ? '网络隔离' : '链路可用'}</p><p>见过的版本：{r.seen.map((v) => `${v.value}@${tagLabel(v.tag)}`).join('、')}</p><div className={styles.faultActions}><button disabled={disabled} onClick={() => act({ type: r.online ? 'crash' : 'restart', node: r.id })}>{r.online ? '崩溃' : '重启'} {r.id}</button><button disabled={disabled} onClick={() => act({ type: r.isolated ? 'heal' : 'isolate', node: r.id })}>{r.isolated ? '连通' : '隔离'} {r.id}</button></div></section>)}</div>
    <section className={styles.panel}><h2>实际用户操作历史</h2><div className={styles.tableScroll}><table aria-label="复制操作历史"><thead><tr><th>操作</th><th>调用方</th><th>类型 / 值</th><th>调用事件</th><th>返回事件 / 结果</th><th>确认或回复集合</th></tr></thead><tbody>{s.operations.map((op) => <tr key={op.id}><th>{op.id}</th><td>{op.client}</td><td>{op.kind} {op.value}</td><td>{op.invoked}</td><td>{op.returned ?? 'pending'} / {op.result ?? 'pending'}</td><td>{(op.kind === 'write' ? op.confirmations : op.replies.map((r) => r.node)).join(', ') || '无'}</td></tr>)}</tbody></table></div><p className={styles.note}>检查初值为 initial 的单个寄存器；返回早于另一调用的操作必须排在它之前。有未完成操作时明确报告未完整，不将其忽略。通过只说明这段有限历史存在见证，不证明整个协议。</p>{h.witness.length ? <p>顺序见证：{h.witness.join(' → ')}</p> : null}</section>
    <section className={styles.panel}><h2>逐条递送网络消息</h2><div className={styles.ledgers}>{s.messages.filter((m) => m.status === 'network' || m.status === 'held').map((m) => <div className={styles.message} key={m.id}><strong>{m.id} · {messageLabels[m.type]}</strong><p>{m.from} → {m.to} · {m.operationId}<br />{m.version ? `${m.version.value} @ ${tagLabel(m.version.tag)}` : `最低版本 ${tagLabel(m.minimum)}`} · {m.status === 'held' ? '副本等待版本' : '在途'}</p><div><button disabled={disabled || !canDeliver(s, m)} onClick={() => act({ type: 'deliver', messageId: m.id })}>递送 {m.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop', messageId: m.id })}>丢弃 {m.id}</button></div></div>)}</div></section>
    <EventTimeline timeUnit="step" events={s.events} actors={actors} labels={{ sent: '发送消息', stored: '更新副本', invoked: '调用', returned: '返回', 'read-wait': '等待版本', 'late-reply': '迟到回复', dropped: '丢弃消息', crash: '崩溃', restart: '重启', isolate: '隔离', heal: '连通' }} />
  </>
}
export function ReplicationLab({ labId }: { labId: LabId }) { return <Experiment key={labId} id={labId} /> }
function Experiment({ id }: { id: LabId }) {
  const lesson = id === 'replica-consistency' ? replicaLesson : quorumLesson
  const metadata = exercises.find((e) => e.id === id)!
  const primary = id === 'replica-consistency'
  return <ProtocolExperiment id={id} title={metadata.title} summary={metadata.summary} conceptId={primary ? 'replication-consistency' : 'consensus'} createSession={() => lesson.session()} initial={lesson.initial} scenarios={scenariosFor(id)}
    goals={{ 'stale-read': '固定主节点确认后，先读取尚未同步的 B。让读取满足写后读要求，再完成复制；不能用事后追平抹掉已经返回的旧值。', 'monotonic-read': '先从已追平的 B 读取，再换到落后的 C。比较读取结果能否倒退，以及版本令牌如何等待足够新的值。', partition: '写入确认后隔离 B，发起读取，再恢复链路。观察阻塞、旧值和会话读取的区别；固定主节点模式不进行选主。', intersection: '先仅写入 W 个副本，再从 C、B、A 顺序取得读回复。配置相交的 R/W 集合，核对读取结果和真实回复集合。', repair: '固定 W=2、R=2，让 C 落后。开启异步读修复，观察读返回后，修复消息怎样改变 C；返回与修复完成分别发生。', 'clock-counterexample': '保持 W=2、R=2。Y 先写 v1 并返回，X 再用独立计数器写 v2，最后读取。构造 R+W>N 仍违反实时顺序的反例，并解释原因。', manual: '自由交错两个客户端、三个副本和网络消息。最多八个用户操作，保留完整有限历史检查；自由实验不计挑战进度。' }}
    selectScenario={(d, scenario) => ({ ...lesson.initial(), scenario, config: d.config })} runModel={runModel} guide={(d) => d.scenario === 'manual' ? [] : scenarioCommands(d.config, d.scenario)} commandLabel={(c) => 'messageId' in c ? `${c.type === 'deliver' ? '递送' : '丢弃'} ${c.messageId}` : 'node' in c ? `${c.type} ${c.node}` : `${c.type === 'write' ? '写入' : '读取'} ${c.client}`} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => { const update = (patch: Partial<Config>) => edit({ ...d, config: { ...d.config, ...patch }, commands: [] }); return <div className={styles.settings}>{primary ? <label>复制读取策略<select aria-label="复制读取策略" value={d.config.readPolicy} disabled={disabled} onChange={(e) => update({ readPolicy: e.target.value as Config['readPolicy'] })}><option value="any">任意副本，直接返回</option><option value="session">同一会话最低版本令牌</option><option value="primary">固定主节点 A</option></select></label> : <>{(['writeQuorum', 'readQuorum'] as const).map((key) => <label key={key}>{key === 'writeQuorum' ? '写确认 W' : '读回复 R'}<select aria-label={key === 'writeQuorum' ? '写确认 W' : '读回复 R'} value={d.config[key]} disabled={disabled} onChange={(e) => update({ [key]: Number(e.target.value) })}>{[1, 2, 3].map((n) => <option key={n}>{n}</option>)}</select></label>)}<label>异步读修复<select aria-label="异步读修复" value={String(d.config.repair)} disabled={disabled} onChange={(e) => update({ repair: e.target.value === 'true' })}><option value="false">关闭</option><option value="true">返回后修复已回复的旧副本</option></select></label></>}</div> }}
    renderLive={(d, s, act, disabled) => <Live s={s} c={d.config} act={act} disabled={disabled} />}
    renderAnswers={(d, edit, disabled) => <AnswerFields disabled={disabled} answers={d.answers} change={(answers) => edit({ ...d, answers })} fields={[{ id: 'value', label: '最后读取结果作答' }, { id: 'pending', label: '未返回操作数作答' }, { id: 'history', label: '有限历史检查作答', options: Object.entries(historyLabels).map(([value, label]) => ({ value, label })) }, { id: 'reason', label: '复制保证边界', options: [{ value: 'observed-evidence', label: '按实际回复和实时顺序判断；收敛或 quorum 算式不能单独证明保证' }, { value: 'converged', label: '最后副本都一致，之前的读取就一定正确' }] }]} />}
    compare={(d) => ({ headings: ['最后读取', '历史检查', '副本值'], rows: (primary ? (['any', 'session', 'primary'] as const).map((readPolicy) => ({ label: readPolicy, config: { ...d.config, readPolicy } })) : [[1, 1], [2, 2], [3, 1]].map(([writeQuorum, readQuorum]) => ({ label: `W=${writeQuorum} R=${readQuorum}`, config: { ...d.config, writeQuorum: writeQuorum!, readQuorum: readQuorum! } }))).map(({ label, config }) => { const s = runModel(config, scenarioCommands(config, d.scenario)); return { label, values: [lastRead(s)?.result ?? 'pending', historyLabels[checkRegisterHistory(s.operations).status], s.replicas.map((r) => r.current.value).join(' / ')] } }) })}
    boundary={['replicated-register-v1：三个固定副本、两个客户端、单个字符串寄存器。副本稳定状态在进程崩溃后保留；网络由手动递送、丢弃和隔离控制。事件轴是逻辑步，不代表真实延迟。最多八个用户操作、150 条消息和 150 个命令。', primary ? '主节点固定为 A，主节点本地提交后确认，复制异步进行；没有副本提升、租约读或主节点故障后的强一致性保证。会话令牌携带客户端已观察的版本，约束后续非重叠读取，版本不足时等待。' : 'Quorum 模式采用各客户端独立递增计数器与客户端 ID 组成的全序 tag，副本保留最高 tag。写确认表示处理过该 tag，不代表它胜过并发或先前更高 tag。异步读修复不是 ABD 的返回前多数派写回，也不是 Raft；不承诺线性一致性。', '历史检查器对不超过八个已完成操作枚举合法寄存器顺序，遵守返回早于调用的实时先后；输出见证或反例。任何操作未返回时报告未完整，不推断整个协议的正确性或可用性。']} />
}
