'use client'
import { ProtocolExperiment } from '../protocol/experiment'
import { AnswerFields } from '../protocol/answer-fields'
import { EventTimeline } from '../protocol/event-timeline'
import { exercise, lesson, scenarioCommands, scenarios } from './lesson'
import { canDeliver, MAX_COMMANDS, runModel, type Command, type Config, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
const phaseLabels = { initial: '尚未准备', prepared: '已准备，持锁等待', committed: '已提交', aborted: '已中止' }
function Live({ s, c, act, disabled }: { s: State; c: Config; act: (command: Command) => void; disabled: boolean }) {
  return <><section className={styles.metrics}><div><span>协调者持久决议</span><strong data-testid="commit-decision">{s.decision ?? 'unknown'}</strong></div><div><span>仍持准备锁</span><strong data-testid="commit-prepared">{s.participants.filter((p) => p.phase === 'prepared').length}</strong></div><div><span>业务提交次数</span><strong data-testid="commit-effects">{s.participants.reduce((n, p) => n + p.effects, 0)}</strong></div><div><span>客户端获知</span><strong data-testid="commit-client">{s.clientOutcome ?? 'unknown'}</strong></div></section>
    <section className={styles.panel}><h2>协调者 · {s.coordinatorOnline ? '运行中' : '已崩溃'}</h2><p>已收到投票：A={s.votes.A ?? 'unknown'}，B={s.votes.B ?? 'unknown'}；最终确认：{s.acknowledgements.join(', ') || '无'}。时间 {s.now} ms。</p><div className={styles.faultActions}><button disabled={disabled || !s.coordinatorOnline || s.started} onClick={() => act({ type: 'begin' })}>创建转账事务</button><button disabled={disabled || !s.coordinatorOnline || !s.started || !!s.decision} onClick={() => act({ type: 'prepare' })}>重发准备请求</button><button disabled={disabled || !s.coordinatorOnline || !s.started || !!s.decision} onClick={() => act({ type: 'decide' })}>按投票持久记录决议</button><button disabled={disabled || !s.coordinatorOnline || !s.started || !!s.decision} onClick={() => act({ type: 'abort' })}>持久记录全局中止</button><button disabled={disabled || !s.coordinatorOnline || !s.decision} onClick={() => act({ type: 'broadcast' })}>发送或重发决议</button><button disabled={disabled} onClick={() => act({ type: s.coordinatorOnline ? 'crash' : 'restart', actor: 'coordinator' })}>{s.coordinatorOnline ? '崩溃协调者' : '重启协调者'}</button><button disabled={disabled || s.now + c.timeoutMs > 10000} onClick={() => act({ type: 'advance', ms: c.timeoutMs })}>推进参与者等待超时</button></div></section>
    <div className={styles.ledgers}>{s.participants.map((p) => <section className={styles.actor} key={p.id}><h2>参与者 {p.id}</h2><strong data-testid={`commit-${p.id}`}>{phaseLabels[p.phase]}</strong><p>本地余额：{p.balance} · 曾投票：{p.vote ?? '无'} · {p.online ? '运行中' : '离线'}<br />准备等待期限：{p.timeoutAt ?? '无'} · 提交效果 {p.effects} 次</p><button disabled={disabled} onClick={() => act({ type: p.online ? 'crash' : 'restart', actor: p.id })}>{p.online ? '崩溃' : '重启'}参与者 {p.id}</button></section>)}</div>
    {s.conflicts ? <p role="alert" className={styles.error}>观察到 {s.conflicts} 次本地终态与全局决议冲突。不能将这些状态强行改成一致。</p> : null}
    <section className={styles.panel}><h2>逐条投递 2PC 消息</h2><div className={styles.ledgers}>{s.messages.filter((m) => m.status === 'network').map((m) => <div key={m.id} className={styles.message}><strong>{m.id} · {m.type}</strong><p>{m.from} → {m.to} · {m.vote ?? m.decision ?? '准备请求'}</p><div><button disabled={disabled || !canDeliver(s, m)} onClick={() => act({ type: 'deliver', messageId: m.id })}>递送 {m.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop', messageId: m.id })}>丢弃 {m.id}</button></div></div>)}</div></section>
    <EventTimeline events={s.events} actors={[{ id: 'client', label: '客户端' }, { id: 'coordinator', label: '协调者' }, { id: 'A', label: '参与者 A' }, { id: 'B', label: '参与者 B' }]} labels={{ begun: '创建事务', prepared: '持久准备', 'vote-no': '拒绝准备', 'vote-received': '收到投票', 'decision-logged': '持久决议', applied: '应用决议', blocked: '持锁阻塞', 'heuristic-abort': '危险的自行中止', 'decision-conflict': '决议冲突', 'decision-replay': '重放决议', 'client-result': '客户端结果', crash: '崩溃', restart: '重启', sent: '发送消息', dropped: '丢弃消息', clock: '推进时间' }} />
  </>
}
export function CommitLab() {
  return <ProtocolExperiment id={exercise.id} title={exercise.title} summary={exercise.summary} conceptId="two-phase-commit" createSession={() => lesson.session()} initial={lesson.initial} scenarios={scenarios}
    goals={{ blocking: '两个参与者准备后，协调者在记录决议前崩溃。推进超时，观察准备锁为什么不能直接释放；恢复协调者并重新收集投票，完成事务。', 'decision-gap': '协调者已持久记录 commit，只让 A 收到，然后崩溃。让 B 等待超时，再恢复协调者重发同一个决议。比较等待与错误的超时自行中止。', 'participant-recovery': '让已准备的 B 崩溃。提交决议先到达 A；B 从稳定准备记录恢复，再收到决议。重发一次决议，确认不会重复扣款或入账。', rejection: '让 B 的本地约束拒绝准备。记录并传播全局 abort，两个业务余额保持原值，准备锁全部释放。', manual: '自由交错准备、投票、决议、消息丢失与进程恢复。每个事务只有一份不可更改的全局决议；自由操作只保存证据。' }}
    selectScenario={(d, scenario) => ({ ...lesson.initial(), scenario, config: { ...d.config, rejectB: scenario === 'rejection' } })} runModel={runModel} guide={(d) => d.scenario === 'manual' ? [] : scenarioCommands(d.config, d.scenario)} commandLabel={(c) => 'messageId' in c ? `${c.type === 'deliver' ? '递送' : '丢弃'} ${c.messageId}` : 'actor' in c ? `${c.type} ${c.actor}` : c.type === 'advance' ? '推进参与者等待' : ({ begin: '创建事务', prepare: '重发准备', decide: '持久记录决议', broadcast: '重发决议', abort: '全局中止' })[c.type]} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => { const update = (patch: Partial<Config>) => edit({ ...d, config: { ...d.config, ...patch }, commands: [] }); return <div className={styles.settings}><label>Prepared 后超时<select aria-label="2PC 超时策略" value={d.config.timeoutPolicy} disabled={disabled} onChange={(e) => update({ timeoutPolicy: e.target.value as Config['timeoutPolicy'] })}><option value="wait">保留锁与承诺，等待决议</option><option value="abort">错误规则：自行中止</option></select></label><label>等待期限<select aria-label="2PC 等待期限" value={d.config.timeoutMs} disabled={disabled} onChange={(e) => update({ timeoutMs: Number(e.target.value) })}>{[100, 500, 1000].map((v) => <option key={v} value={v}>{v} ms</option>)}</select></label><label>B 的准备约束<select aria-label="B 准备约束" value={String(d.config.rejectB)} disabled={disabled} onChange={(e) => update({ rejectB: e.target.value === 'true' })}><option value="false">允许准备</option><option value="true">拒绝准备</option></select></label></div> }}
    renderLive={(d, s, act, disabled) => <Live s={s} c={d.config} act={act} disabled={disabled} />} renderAnswers={(d, edit, disabled) => <AnswerFields answers={d.answers} disabled={disabled} change={(answers) => edit({ ...d, answers })} fields={[{ id: 'decision', label: '持久决议作答', options: ['commit', 'abort', 'unknown'].map((value) => ({ value, label: value })) }, { id: 'prepared', label: '仍准备持锁的参与者数作答' }, { id: 'effects', label: '业务提交次数作答' }, { id: 'reason', label: '2PC 保证边界', options: [{ value: 'durable-decision', label: '准备是承诺，超时不能推断决议；恢复后按稳定决议收尾' }, { value: 'timeout-abort', label: '超时说明协调者没有提交，可以直接释放锁' }] }]} />}
    compare={(d) => ({ headings: ['持久决议', '参与者终态', '冲突', '客户端结果'], rows: (['wait', 'abort'] as const).map((timeoutPolicy) => { const c = { ...d.config, timeoutPolicy }; const s = runModel(c, scenarioCommands(c, d.scenario)); return { label: timeoutPolicy === 'wait' ? 'Prepared 后等待' : '错误的超时自行中止', values: [s.decision ?? 'unknown', s.participants.map((p) => p.phase).join(' / '), s.conflicts, s.clientOutcome ?? 'unknown'] } }) })}
    boundary={['two-phase-commit-v1：单个 txn-1、一个协调者和两个参与者，A/B 初始余额各 5，事务转移 2。准备写意图与 YES 稳定记录后才回复；协调者先持久记录唯一决议再发送。业务应用与终态本地原子提交，重复决议不重复效果。', '协调者崩溃丢失收到的投票和确认，稳定决议保留；参与者稳定保留 Prepared、终态和业务余额。超时等待可能持续阻塞，不自动选择多数派或新协调者。错误的自行中止仅用于构造反例。', '本题不模拟参与者并发事务、全局快照读取、Paxos Commit 或完整数据库隔离；物理提交时刻可不同，仍准备的资源保持锁定。最多 120 个命令、80 条消息和 10,000 ms。']} />
}
