import { useState } from 'react'
import { EventTimeline } from '../protocol/event-timeline'
import { contiguousCheckpoint, MAX_TIME, MAX_TOTAL_DELIVERIES, nextTimer, type Command, type Config, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'

export const eventLabels: Record<string, string> = { 'task-commit': '提交业务', 'publish-sent': '发送事件', 'publish-dropped': '发布丢失', 'broker-accepted': '队列接纳', 'confirm-delivered': '发布确认到达', 'confirm-dropped': '发布确认丢失', 'confirm-stale': '旧确认失效', 'outbox-sent': '提交发送进度', dispatch: '发出投递', 'delivery-received': 'Worker 收到', 'delivery-dropped': '投递丢失', 'effect-written': '效果已写入', 'atomic-effect': '原子效果与进度', 'effect-skipped': '跳过重复效果', 'checkpoint-saved': '保存进度', 'ack-sent': '发送 ACK', 'ack-accepted': '接纳 ACK', 'ack-dropped': 'ACK 丢失', 'ack-stale': '拒绝旧 ACK', 'worker-crashed': 'Worker 崩溃', 'worker-restarted': 'Worker 恢复', 'producer-crashed': '生产者崩溃', 'producer-restarted': '生产者恢复', 'visibility-expired': '到期重投', 'dead-letter': '进入死信', 'work-failed': '处理失败', redrive: '修复后重放', 'clock-advanced': '推进时间', 'consumer-start': '开启投递', 'consumer-pause': '暂停新投递' }
const workLabels = { todo: '尚未处理', effect: '效果已写，进度未提交', checkpoint: '效果与进度均已保存', replayed: '已有 Checkpoint，未重复执行', failed: '本次处理失败' }
const copyLabels = { pending: '等待投递', 'in-flight': '等待有效 ACK', acked: '已确认', 'dead-letter': '死信待修复' }

export function MessageLiveView({ config, state, act, produce, disabled }: { config: Config; state: State; act: (command: Command) => void; produce: () => void; disabled: boolean }) {
  const [advanceMs, setAdvanceMs] = useState(500)
  const next = nextTimer(state)
  return <>
    <div id="message-state" className={styles.metrics} aria-label="消息实验状态">
      <div><small>已提交任务</small><strong data-testid="message-tasks">{state.tasks.length}</strong></div>
      <div><small>实际业务效果</small><strong data-testid="message-effects">{state.effects.length}</strong></div>
      <div><small>持久 Checkpoint</small><strong data-testid="message-checkpoints">{state.checkpoints.length}</strong></div>
      <div><small>已确认队列副本</small><strong data-testid="message-acked">{state.copies.filter((copy) => copy.status === 'acked').length} <span>/ {state.copies.length}</span></strong></div>
    </div>
    <div className={styles.actors}>
      <section className={styles.actor} aria-label="生产者操作"><span className={styles.actorNumber}>01 / PRODUCER</span><h2>业务提交与发布</h2><strong className={styles.status}>{state.producerOnline ? `在线 · 进程 ${state.producerEpoch}` : '生产者已崩溃'}</strong><p>{config.producer === 'outbox' ? '提交任务时原子保存 Outbox；发布和提交发送进度是后续步骤。' : '业务记录与发布分开，进程可能在两步之间失败。'}</p>
        <button className={styles.primary} disabled={disabled || !state.producerOnline || state.tasks.length >= 3} onClick={produce}>生产并确认一条消息</button>
        <button disabled={disabled || !state.producerOnline || state.tasks.length >= 3} onClick={() => act({ type: 'create-task' })}>只提交业务任务</button>
        <button disabled={disabled || !state.producerOnline || config.producer !== 'outbox' || !state.outbox.some((record) => record.status === 'pending')} onClick={() => act({ type: 'relay' })}>发布一个 Outbox 待办</button>
        {state.tasks.map((task) => <div className={styles.message} key={task.id}><strong>{task.id} · {task.messageId}</strong><small>业务序号 {task.sequence} · 提交于 {task.createdAt} ms</small><button disabled={disabled || !state.producerOnline || state.publications.length >= 12} onClick={() => act({ type: 'publish', taskId: task.id })}>发送事件 {task.messageId}</button></div>)}
        {state.publications.map((publication) => <div className={`${styles.message} ${styles.response}`} key={publication.id}><strong>{publication.id} · {publication.messageId}</strong><span>{publication.status === 'network' ? '发布在网络中' : publication.status === 'accepted' ? 'broker 已接纳' : '发布已丢失'} · 发送进程 {publication.epoch}</span>
          {publication.status === 'network' ? <div><button disabled={disabled} onClick={() => act({ type: 'accept-publication', publicationId: publication.id })}>接纳 {publication.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-publication', publicationId: publication.id })}>丢弃发布 {publication.id}</button></div> : null}
          {publication.confirm === 'network' ? <div><button disabled={disabled || !state.producerOnline} onClick={() => act({ type: 'deliver-confirm', publicationId: publication.id })}>递送发布确认 {publication.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-confirm', publicationId: publication.id })}>丢弃发布确认 {publication.id}</button></div> : publication.confirm !== 'none' ? <small>发布确认：{({ delivered: '已到达', dropped: '已丢失', ignored: '旧进程确认被忽略' } as Record<string, string>)[publication.confirm]}</small> : null}
          {config.producer === 'outbox' ? <button disabled={disabled || !state.producerOnline || publication.epoch !== state.producerEpoch || publication.confirm !== 'delivered' || !state.outbox.some((record) => record.messageId === publication.messageId && record.status === 'pending')} onClick={() => act({ type: 'mark-sent', publicationId: publication.id })}>标记已发送 {publication.id}</button> : null}
        </div>)}
        <div className={styles.faultActions}><button disabled={disabled || !state.producerOnline} onClick={() => act({ type: 'crash-producer' })}>生产者崩溃</button><button disabled={disabled || state.producerOnline} onClick={() => act({ type: 'restart-producer' })}>重启生产者</button></div>
      </section>
      <section className={styles.actor} aria-label="Broker 与消息网络"><span className={styles.actorNumber}>02 / BROKER</span><h2>队列与在途消息</h2><strong className={styles.status}>逻辑时间 <span data-testid="message-clock">{state.now}</span> ms</strong><p>生产者停止后也能继续排空。每份投递有独立凭据；到期会重投，旧请求不会被魔法撤回。</p>
        <div className={styles.faultActions}><button disabled={disabled || state.consuming} onClick={() => act({ type: 'start-consumer' })}>开启投递</button><button disabled={disabled || !state.consuming} onClick={() => act({ type: 'pause-consumer' })}>暂停新投递</button></div>
        <button disabled={disabled || next === null || next > MAX_TIME} onClick={() => { if (next !== null) act({ type: 'advance', ms: Math.max(1, next - state.now) }) }}>推进下一次到期{next !== null ? `（${next} ms）` : ''}</button>
        <div className={styles.advance}><select aria-label="消息推进时间" value={advanceMs} onChange={(event) => setAdvanceMs(Number(event.target.value))}>{[100, 500, 1000, 5000].map((value) => <option key={value} value={value}>{value} ms</option>)}</select><button disabled={disabled || state.now + advanceMs > MAX_TIME} onClick={() => act({ type: 'advance', ms: advanceMs })}>推进消息时间</button></div>
        {state.deliveries.filter((delivery) => delivery.location === 'network').map((delivery) => <div className={styles.message} key={delivery.id} data-testid={delivery.id}><strong>{delivery.id} → Worker</strong><span>{delivery.messageId} · {delivery.copyId}</span><small>{delivery.status === 'expired' ? '凭据已过期，但迟到的工作仍可能执行' : `等待 ACK 至 ${delivery.expiresAt} ms`}</small><div><button disabled={disabled || !state.workerOnline} onClick={() => act({ type: 'deliver-work', deliveryId: delivery.id })}>递送 {delivery.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-work', deliveryId: delivery.id })}>丢弃 {delivery.id}</button></div></div>)}
        {state.acks.filter((ack) => ack.status === 'network').map((ack) => <div className={`${styles.message} ${styles.response}`} key={ack.id} data-testid={ack.id}><strong>{ack.id} → Broker</strong><span>只确认 {ack.deliveryId}</span><div><button disabled={disabled} onClick={() => act({ type: 'deliver-ack', ackId: ack.id })}>递送 {ack.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-ack', ackId: ack.id })}>丢弃 {ack.id}</button></div></div>)}
        {!state.deliveries.some((delivery) => delivery.location === 'network') && !state.acks.some((ack) => ack.status === 'network') ? <div className={styles.empty}>没有待递送的工作或消费 ACK。</div> : null}
        {state.deliveries.length >= MAX_TOTAL_DELIVERIES ? <p className={styles.note}>全局投递预算已耗尽。待处理状态不会自动算作完成。</p> : null}
      </section>
      <section className={styles.actor} aria-label="Worker 操作"><span className={styles.actorNumber}>03 / WORKER</span><h2>效果、进度与 ACK</h2><strong className={styles.status}>{state.workerOnline ? `在线 · 进程 ${state.workerEpoch}` : 'Worker 已崩溃'}</strong><p>{config.consumer === 'early' ? '收到消息就发送 ACK，业务处理与进度仍在后面。' : config.consumer === 'split' ? '先写业务效果，再单独保存 Checkpoint，随后 ACK。两次提交之间可以崩溃。' : '一条原子步骤提交效果和 Checkpoint，再发送 ACK；已有 Checkpoint 时跳过重复效果。'}</p>
        {state.deliveries.filter((delivery) => delivery.location === 'worker').map((delivery) => <div className={styles.message} key={delivery.id}><strong>{delivery.id} · {delivery.messageId}</strong><span>{workLabels[delivery.work]}</span><small>{delivery.status === 'expired' ? '旧凭据已失效，Worker 的本地执行并未被取消' : delivery.status === 'acked' ? 'Broker 已确认该投递' : `等待有效 ACK 至 ${delivery.expiresAt} ms`}</small><div><button disabled={disabled || !state.workerOnline || delivery.work !== 'todo'} onClick={() => act({ type: 'process', deliveryId: delivery.id })}>执行效果 {delivery.id}</button><button disabled={disabled || !state.workerOnline || delivery.work !== 'effect' || config.consumer === 'atomic'} onClick={() => act({ type: 'checkpoint', deliveryId: delivery.id })}>保存 Checkpoint {delivery.id}</button></div><div><button disabled={disabled || !state.workerOnline || delivery.work !== 'todo'} onClick={() => act({ type: 'fail-work', deliveryId: delivery.id })}>处理失败 {delivery.id}</button><button disabled={disabled || !state.workerOnline || (config.consumer !== 'early' && !['checkpoint', 'replayed'].includes(delivery.work)) || state.acks.some((ack) => ack.deliveryId === delivery.id && ack.status === 'network')} onClick={() => act({ type: 'resend-ack', deliveryId: delivery.id })}>重发 ACK {delivery.id}</button></div></div>)}
        <div className={styles.faultActions}><button disabled={disabled || !state.workerOnline} onClick={() => act({ type: 'crash-worker' })}>Worker 崩溃</button><button disabled={disabled || state.workerOnline} onClick={() => act({ type: 'restart-worker' })}>重启 Worker</button></div><p className={styles.note}>本地未提交进度会丢失，持久效果与 Checkpoint 保留。已经发出的 ACK 仍可到达 broker。</p>
      </section>
    </div>
    <section className={styles.panel}><h2>队列副本、投递与死信</h2><div className={styles.tableScroll}><table aria-label="队列副本表"><thead><tr><th>副本 / 逻辑消息</th><th>状态</th><th>当前凭据</th><th>本轮 / 累计投递</th><th>恢复</th></tr></thead><tbody>{state.copies.map((copy) => <tr key={copy.id}><td>{copy.id}<small>{copy.messageId}</small></td><td>{copyLabels[copy.status]}</td><td>{copy.activeDelivery ?? '—'}</td><td>{copy.attempts} / {copy.totalAttempts}</td><td><button disabled={disabled || copy.status !== 'dead-letter' || state.deliveries.length >= MAX_TOTAL_DELIVERIES} onClick={() => act({ type: 'redrive', copyId: copy.id })}>修复后重放 {copy.id}</button></td></tr>)}</tbody></table></div><p className={styles.note}>“修复后重放”重新给出本轮投递预算，保留累计次数、消息身份与历史效果。这里的处理错误由手动注入，不模拟消息 Schema 修复。</p></section>
    <section className={styles.panel} aria-label="稳定业务状态"><h2>稳定状态：业务效果与恢复依据</h2><div className={styles.ledgers}>
      <div><h3>业务效果账本 · {state.effects.length} 次</h3><div className={styles.tableScroll}><table aria-label="消费效果表"><thead><tr><th>效果</th><th>逻辑消息</th><th>来自投递</th><th>时刻</th></tr></thead><tbody>{state.effects.map((effect) => <tr key={effect.id}><td>{effect.id}</td><td>{effect.messageId}</td><td>{effect.deliveryId}</td><td>{effect.at} ms</td></tr>)}</tbody></table></div></div>
      <div><h3>Checkpoint · 连续完成位置 {contiguousCheckpoint(state)}</h3><div className={styles.tableScroll}><table aria-label="消费 Checkpoint 表"><thead><tr><th>逻辑消息</th><th>业务序号</th><th>已提交时刻</th></tr></thead><tbody>{state.checkpoints.map((checkpoint) => <tr key={checkpoint.messageId}><td>{checkpoint.messageId}</td><td>{checkpoint.sequence}</td><td>{checkpoint.at} ms</td></tr>)}</tbody></table></div><p className={styles.note}>去重域为同一逻辑消费者与消息身份；连续位置只能越过已完成的全部前序任务，不因先完成第 2 项就跳过第 1 项。</p></div>
      <div><h3>生产者任务表</h3><div className={styles.tableScroll}><table aria-label="生产者任务表"><thead><tr><th>任务</th><th>消息身份</th><th>提交时刻</th></tr></thead><tbody>{state.tasks.map((task) => <tr key={task.id}><td>{task.id}</td><td>{task.messageId}</td><td>{task.createdAt} ms</td></tr>)}</tbody></table></div></div>
      <div><h3>Outbox 发送意图</h3><div className={styles.tableScroll}><table aria-label="Outbox 记录表"><thead><tr><th>任务 / 消息</th><th>状态</th></tr></thead><tbody>{state.outbox.map((record) => <tr key={record.messageId}><td>{record.taskId} / {record.messageId}</td><td>{record.status === 'pending' ? '等待发布或发送标记' : '发送进度已提交'}</td></tr>)}</tbody></table></div>{!state.outbox.length ? <p className={styles.note}>没有 Outbox 记录。业务表存在，不代表发送意图已经可靠保存。</p> : null}</div>
    </div></section>
    <EventTimeline events={state.events} actors={[{ id: 'producer', label: '生产者' }, { id: 'broker', label: 'Broker' }, { id: 'worker', label: 'Worker' }, { id: 'store', label: '稳定存储' }]} labels={eventLabels} />
  </>
}
