'use client'
import { ProtocolExperiment } from '../protocol/experiment'
import { ConfigurationFields } from '../protocol/configuration-fields'
import { AnswerFields } from '../protocol/answer-fields'
import { counts,MAX_COMMANDS,runModel,type Command } from './model'
import { exercise,lesson,scenarios,script } from './lesson'
import styles from '../retry-idempotency/retry-lab.module.css'
const label=(c:Command)=>c.type==='tick'?'推进一个 10 ms 处理槽':`租户 ${c.tenant} 提交 ${c.count} 个作业`
export function TenantIsolationLab(){return <ProtocolExperiment id={exercise.id} title={exercise.title} summary={exercise.summary} conceptId="security-boundaries" createSession={()=>lesson.session()} initial={lesson.initial} scenarios={scenarios}
  goals={{admission:'A 先提交 8 个作业，B 再提交 2 个。B 的两个作业都必须完成，A 至少完成一个；所有拒绝仍要报告。',latency:'保持相同需求与一个 Worker，B 的两个作业都必须在提交后 40 ms 内完成。配额足够，不代表调度足够。',manual:'自行提交并按槽执行。公平性与保护目标只针对本模型声明的租户、工作量和预算。'}}
  selectScenario={(d,scenario)=>({...lesson.initial(),scenario,config:d.config})} runModel={runModel} guide={d=>d.scenario==='manual'?[]:script} commandLabel={label} maxCommands={MAX_COMMANDS}
  renderConfig={(d,edit,disabled)=><ConfigurationFields config={d.config} disabled={disabled} change={config=>edit({...d,config,commands:[]})} fields={[{key:'admission',label:'队列接纳策略',choices:[{value:'shared',label:'共享 6 个等待位'},{value:'reserved',label:'总共 6 位，每租户最多 3 位'}]},{key:'schedule',label:'租户调度策略',choices:[{value:'fifo',label:'全局先来先服务'},{value:'round-robin',label:'在有等待工作的租户间轮转'}]}]} />}
  renderLive={(_d,s,act,disabled)=><><section className={styles.metrics}>{(['A','B'] as const).map(t=>{const c=counts(s,t);return <div key={t}><span>租户 {t} 完成 / 提交</span><strong data-testid={`tenant-${t}`}>{c.completed} / {c.offered}</strong><small>拒绝 {c.rejected}；40 ms 内 {c.onTime}</small></div>})}<div><span>逻辑时间</span><strong>{s.now} ms</strong></div></section><section className={styles.panel}><h2>实际作业账本</h2><div className={styles.tableScroll}><table aria-label="租户作业账本"><thead><tr><th>作业 / 租户</th><th>提交</th><th>开始</th><th>完成</th><th>结果</th></tr></thead><tbody>{s.jobs.map(j=><tr key={j.id}><th>{j.id} / {j.tenant}</th><td>{j.createdAt}</td><td>{j.startedAt??'—'}</td><td>{j.finishedAt??'—'}</td><td>{j.status}</td></tr>)}</tbody></table></div><div className={styles.faultActions}><button disabled={disabled} onClick={()=>act({type:'submit',tenant:'A',count:8})}>A 提交 8 个作业</button><button disabled={disabled} onClick={()=>act({type:'submit',tenant:'B',count:2})}>B 提交 2 个作业</button><button disabled={disabled} onClick={()=>act({type:'tick'})}>推进一个 10 ms 处理槽</button></div></section></>}
  renderAnswers={(d,edit,disabled)=><AnswerFields answers={d.answers} change={answers=>edit({...d,answers})} disabled={disabled} fields={[{id:'a',label:'A 完成数作答'},{id:'b',label:'B 完成数作答'},{id:'rejected',label:'全部拒绝数作答'},{id:'reason',label:'租户保护依据',options:[{value:'admission-and-scheduling',label:'同时检查接纳、调度与各租户结果'},{value:'total',label:'总吞吐正常就不需要看小租户'}]}]} />}
  compare={d=>({headings:['A 完成','B 完成','B 按时完成','总拒绝'],rows:([{admission:'shared',schedule:'fifo'},{admission:'shared',schedule:'round-robin'},{admission:'reserved',schedule:'fifo'},{admission:'reserved',schedule:'round-robin'}] as const).map(policy=>{const s=runModel({...d.config,...policy},script);const a=counts(s,'A'),b=counts(s,'B');return {label:`${policy.admission} / ${policy.schedule}`,values:[a.completed,b.completed,b.onTime,a.rejected+b.rejected]}})})}
  boundary={['tenant-isolation-v1：两个可信租户、一个 Worker、每作业固定 10 ms、总等待位 6。处理槽是完整非抢占作业，空槽也推进 10 ms；不模拟操作系统调度或分布式限流。', '预留模式每租户最多 3 个等待作业，轮转只在非空租户间进行。最多 40 步和 40 个原始作业。所有接纳、拒绝与完成保留，不通过丢弃账本制造吞吐改善。', '本关目标是保护 B 的有限突发并保留 A 的进展；异构工作耗时、更多租户、权重和多节点公平性需要另行建模。']} />}
