import type { Concept, LearningPath } from './types'

export const foundationConcepts: readonly Concept[] = [
  { id: 'quality-goals', groupId: 'foundations', title: '把可靠、可用和持久变成明确目标', aliases: ['Reliability', 'Availability', 'Durability', 'Scalability', 'Maintainability', 'SLI', 'SLO', '可靠性', '可用性', '持久性'], question: '返回成功，是否就满足了用户的要求？', summary: '先声明成功条件和故障范围，再选择副本、持久化和降级策略。', prerequisiteIds: [], capabilityIds: ['REQ-01', 'REQ-02', 'REL-03', 'REL-04'], labIds: ['quality-goals'], caseIds: [] },
  { id: 'resource-constraints', groupId: 'foundations', title: '计算、存储和网络的基本限制', aliases: ['CPU', 'Memory', 'IOPS', 'Bandwidth', 'Latency', 'RTT', '带宽', '资源争用'], question: '系统变慢时，究竟是哪一种资源不够？', summary: '区分计算、等待、传输与排队，用证据找到约束。', prerequisiteIds: ['quality-goals'], capabilityIds: ['PERF-01', 'PERF-02', 'NET-02', 'NET-03'], labIds: ['resource-budget', 'service-queue-replicas', 'database-bottleneck', 'overload'], caseIds: [] },
  { id: 'capacity-estimation', groupId: 'foundations', title: '从用户规模推导流量和资源需求', aliases: ['QPS', 'RPS', 'Concurrency', 'Little law', 'Capacity estimation', '容量估算', '峰值', '存储增长'], question: '十万用户，意味着多少请求、并发和存储？', summary: '让单位、时间窗口、读写比例和放大来源都能追溯。', prerequisiteIds: ['resource-constraints'], capabilityIds: ['REQ-03', 'PERF-05'], labIds: ['resource-budget', 'service-queue-replicas', 'database-bottleneck'], caseIds: [] },
  { id: 'storage-access-patterns', groupId: 'foundations', title: '从访问模式选择数据模型与存储', aliases: ['Database selection', 'SQL', 'NoSQL', 'Key value', 'Document', 'Index', '数据库选型', '关系型', '文档', '对象存储', '索引'], question: '数据要怎样读取和修改，才决定该用什么存储？', summary: '从查询、更新和事务边界出发，比较模型及索引的维护代价。', prerequisiteIds: ['quality-goals'], capabilityIds: ['API-02', 'DATA-01', 'DATA-04', 'DATA-07'], labIds: ['data-access-paths', 'database-bottleneck', 'concurrent-update'], caseIds: [] },
  { id: 'state-and-scaling', groupId: 'foundations', title: '状态放在哪里，决定怎样扩展', aliases: ['Stateless', 'Stateful', 'Replication', 'Partitioning', 'Horizontal scaling', 'Vertical scaling', '无状态', '有状态', '横向扩展', '纵向扩展', '复制', '分片'], question: '把一台服务变成两台，哪些状态和故障问题会出现？', summary: '区分服务实例、数据所有权、副本和分片，检查扩容后的依赖与故障域。', prerequisiteIds: ['quality-goals', 'storage-access-patterns'], capabilityIds: ['API-05', 'SCALE-03', 'SCALE-05', 'NET-01', 'REL-04'], labIds: ['state-placement', 'quality-goals', 'consistent-hashing', 'replica-consistency'], caseIds: [] },
  { id: 'sync-async-boundaries', groupId: 'foundations', title: '何时等待结果，何时异步处理？', aliases: ['Synchronous', 'Asynchronous', '异步处理', '同步调用', '任务状态', '202'], question: '快速返回受理后，谁负责把工作真正完成？', summary: '从业务等待要求选择调用边界，并检查状态、积压、重试与取消。', prerequisiteIds: ['quality-goals', 'resource-constraints'], capabilityIds: ['API-01', 'MSG-01', 'MSG-05'], labIds: ['ack-checkpoint', 'transactional-outbox', 'overload', 'retry-idempotency'], caseIds: [] },
  { id: 'choosing-guarantees', groupId: 'foundations', title: '幂等、事务和一致性分别保护什么？', aliases: ['Guarantee selection', '正确性', '保证边界', '机制选择'], question: '同一个流程为什么可能需要多种不同的保证？', summary: '从重复、竞争、双写和旧读出发，找到保护相应事实的机制。', prerequisiteIds: ['transactions', 'idempotency', 'replication-consistency'], capabilityIds: ['DATA-04', 'DATA-05', 'CONS-01', 'CONS-04', 'REL-02'], labIds: ['retry-idempotency', 'concurrent-update', 'transactional-outbox', 'replica-consistency', 'quorum-reads', 'cache-coherence', 'saga-recovery', 'two-phase-commit'], caseIds: [] },
  { id: 'failure-recovery-design', groupId: 'foundations', title: '从故障范围设计冗余与恢复', aliases: ['Failure domains', 'Recovery design', 'Safety', 'Liveness', '冗余', '恢复演练'], question: '切换成功后，服务、状态和业务都恢复了吗？', summary: '联合检查检测、接管、剩余能力与数据恢复，区分安全性和进展。', prerequisiteIds: ['quality-goals', 'state-and-scaling', 'timeouts-retries', 'durability-recovery'], capabilityIds: ['REL-01', 'REL-03', 'REL-04', 'REL-05', 'OPS-02'], labIds: ['quality-goals', 'state-placement', 'heartbeat', 'retry-idempotency', 'overload', 'lease-fencing', 'durability-recovery'], caseIds: [] },
  { id: 'security-boundaries', groupId: 'foundations', title: '身份、对象授权与租户资源隔离', aliases: ['Authentication', 'Authorization', 'AuthZ', 'Noisy neighbor', '授权', '权限撤销', '租户配额'], question: '谁能访问什么，又能占用多少共同资源？', summary: '把对象权限、缓存撤销、接纳配额和调度分别核对。', prerequisiteIds: ['quality-goals', 'state-and-scaling', 'caching'], capabilityIds: ['SEC-01', 'SEC-02', 'SEC-04'], labIds: ['authorization-boundaries', 'tenant-isolation'], caseIds: [] },
  { id: 'safe-evolution-design', groupId: 'foundations', title: '如何观察、发布和回滚一次变更？', aliases: ['Observability', 'Canary', 'Migration', 'Rollback', '可观测性', '灰度', '数据迁移', '回滚'], question: '代码换了、数据变了，旧版本还能工作吗？', summary: '按版本和实际记录检查变化，区分代码回滚与数据恢复。', prerequisiteIds: ['quality-goals', 'storage-access-patterns', 'choosing-guarantees'], capabilityIds: ['OPS-01', 'OPS-03', 'OPS-04', 'API-05'], labIds: ['safe-evolution', 'resource-budget', 'database-bottleneck'], caseIds: [] },
]

export const foundationPath: LearningPath = {
  id: 'design-foundations', title: '基础设计决策', description: '先理解目标、资源、规模、数据和状态，再用已有实验验证缓存、异步、并发与故障恢复。',
  steps: [
    { question: '先定义什么才算成功', conceptIds: ['quality-goals'] },
    { question: '识别资源限制并估算需求', conceptIds: ['resource-constraints', 'capacity-estimation', 'capacity-and-queues'] },
    { question: '决定数据怎样组织和访问', conceptIds: ['storage-access-patterns', 'transactions'] },
    { question: '确认状态归属，再讨论扩展', conceptIds: ['state-and-scaling', 'consistent-hashing', 'replication-consistency'] },
    { question: '选择缓存并解释新鲜度代价', conceptIds: ['caching', 'hot-keys'] },
    { question: '选择异步边界并控制积压', conceptIds: ['sync-async-boundaries', 'success-boundaries', 'acknowledgements', 'overload-control'] },
    { question: '保护并发效果并验证恢复', conceptIds: ['choosing-guarantees', 'concurrency-control', 'idempotency', 'failure-recovery-design', 'durability-recovery'] },
    { question: '保护权限与共同资源', conceptIds: ['security-boundaries'] },
    { question: '观察结果并安全地演进', conceptIds: ['safe-evolution-design'] },
  ],
}
