import { EventTimeline } from '../protocol/event-timeline'
import { canSend, MAX_TIME, nextOperation, operationLabels, type Command, type Config, type Operation, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
export const phaseLabels = { idle: '尚未开始', forward: '正向执行中', compensating: '补偿中', complete: '发布完成', compensated: '已补偿，发布未成功', failed: '失败后停止', attention: '需要人工处理' }
const responseLabels = { none: '尚无响应', network: '在途', delivered: '已收到，尚未存进度', recorded: '已记入恢复日志', dropped: '响应已丢失', ignored: '旧响应或离线接收，已忽略' }
const requestLabels = { network: '在途', processed: '已处理', dropped: '已丢弃' }
const outcomeLabels = { ok: '成功', rejected: '业务拒绝', unavailable: '暂时不可用' }
const actors = [{ id: 'coordinator', label: '流程协调者' }, { id: 'services', label: '业务服务' }, { id: 'journal', label: '恢复日志' }]
const labels = { started: '创建流程', 'request-sent': '发送步骤', effect: '业务效果提交', 'operation-failed': '步骤失败', dedupe: '重放原结果', 'response-sent': '发送响应', 'response-received': '收到响应', 'response-dropped': '响应丢失', 'response-ignored': '忽略旧响应', checkpoint: '保存恢复进度', 'compensation-started': '开始补偿', compensated: '补偿结束', attention: '需要人工处理', 'review-resumed': '人工核查后恢复', 'retry-pending': '保存暂时失败', crashed: '协调者崩溃', restarted: '恢复协调者', timeout: '等待超时' }
export function SagaLiveView({ state: s, config, act, disabled }: { state: State; config: Config; act: (command: Command) => void; disabled: boolean }) {
  const next = nextOperation(s)
  return <div id="saga-state">
    <section className={styles.metrics} aria-label="Saga 实时状态"><div><span>流程结果</span><strong data-testid="saga-phase">{phaseLabels[s.phase]}</strong></div><div><span>可用配额 / 初始 1</span><strong data-testid="saga-quota">{1 - s.resource.reserved + s.resource.released}</strong></div><div><span>保留产物</span><strong data-testid="saga-artifacts">{s.resource.artifacts}</strong></div><div><span>已消耗的转码工作</span><strong data-testid="saga-work">{s.resource.transcodeWork}</strong></div></section>
    <div className={styles.actors}><section className={styles.actor}><h2>流程协调者</h2><p>{s.online ? '运行中' : '已崩溃'} · 世代 {s.epoch} · {s.now} ms</p><p>恢复位置：{next ? operationLabels[next] : '当前没有待执行步骤'}</p><div className={styles.faultActions}><button disabled={disabled || !s.online || s.phase !== 'idle'} onClick={() => act({ type: 'start' })}>创建视频流程</button><button className={styles.primary} disabled={disabled || !canSend(s, config)} onClick={() => act({ type: 'send' })}>发送或重试当前步骤</button><button disabled={disabled || !s.online} onClick={() => act({ type: 'crash' })}>协调者崩溃</button><button disabled={disabled || s.online} onClick={() => act({ type: 'restart' })}>重启协调者</button><button disabled={disabled || !s.online || s.phase !== 'attention'} onClick={() => act({ type: 'resume-review' })}>人工核查后恢复</button><button disabled={disabled || s.now + config.timeoutMs > MAX_TIME} onClick={() => act({ type: 'advance', ms: config.timeoutMs })}>推进一个响应超时</button></div><p className={styles.note}>响应到达内存后还要保存进度。人工恢复只开启新的有限预算，不会把业务效果改成成功。</p></section>
      <section className={styles.actor}><h2>实际业务账本</h2><p>预留 {s.resource.reserved} 次 · 释放 {s.resource.released} 次</p><p>发布状态：{s.resource.published ? '已发布' : '未发布'}</p><p>累计效果记录 {s.effects.length} 条</p><p className={styles.note}>释放配额是一次增加余额的业务操作。没有幂等保护，重复释放会过量返还；清理产物也不会退还已经发生的计算工作。</p></section>
      <section className={styles.actor}><h2>故障注入</h2><p className={styles.note}>正向步骤设为业务拒绝；补偿步骤设为暂时不可用。已提交的结果不受后续修复影响。</p>{(['transcode', 'publish', 'cleanup', 'release'] as const).map((operation) => <div className={styles.message} key={operation}><strong>{operationLabels[operation]}</strong><p>{s.blocked.includes(operation) ? '故障已注入' : '当前可用'}</p><button disabled={disabled} onClick={() => act({ type: s.blocked.includes(operation) ? 'repair' : 'block', operation })}>{s.blocked.includes(operation) ? '修复' : '阻断'}{operationLabels[operation]}</button></div>)}</section></div>
    <section className={styles.panel}><h2>恢复日志与服务端去重</h2><div className={styles.tableScroll}><table aria-label="Saga 进度表"><thead><tr><th>步骤</th><th>逻辑操作 ID</th><th>持久进度</th><th>服务端去重结果</th><th>已发生效果</th></tr></thead><tbody>{(Object.keys(operationLabels) as Operation[]).map((op) => <tr key={op}><th>{operationLabels[op]}</th><td>video-1/{op}</td><td>{s.journal[op] ? outcomeLabels[s.journal[op]!] : '未记录'}</td><td>{s.dedupe[op] ? outcomeLabels[s.dedupe[op]!] : '无'}</td><td>{s.effects.filter((e) => e.operation === op).length} 次</td></tr>)}</tbody></table></div><p className={styles.note}>正向：预留 → 转码 → 发布。发布拒绝后：清理产物 → 释放配额。每一步单独提交，恢复日志与业务效果没有全局事务。</p></section>
    <section className={styles.panel}><h2>逐条递送调用与响应</h2>{!s.packets.length ? <p className={styles.empty}>创建流程并发送步骤后，可在这里逐条递送或丢弃。</p> : null}<div className={styles.ledgers}>{s.packets.map((p) => <div className={styles.message} key={p.id} data-testid={p.id}><strong>{p.id} · {operationLabels[p.operation]}</strong><p>{p.operationId} · 协调者世代 {p.epoch} · 响应期限 {p.deadline} ms{p.expired ? '（已到期）' : ''}</p><p>调用：{requestLabels[p.status]} · 服务端结果：{p.outcome ? outcomeLabels[p.outcome] : '尚未处理'}{p.replayed ? '（幂等重放）' : ''}<br />响应：{responseLabels[p.response]}</p><div className={styles.faultActions}>{p.status === 'network' ? <><button disabled={disabled} onClick={() => act({ type: 'deliver-request', packetId: p.id })}>执行 {p.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-request', packetId: p.id })}>丢弃调用 {p.id}</button></> : null}{p.response === 'network' ? <><button disabled={disabled} onClick={() => act({ type: 'deliver-response', packetId: p.id })}>递送响应 {p.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-response', packetId: p.id })}>丢弃响应 {p.id}</button></> : null}{p.response === 'delivered' ? <button disabled={disabled || !s.online || p.epoch !== s.epoch || p.operation !== next || s.phase === 'attention'} onClick={() => act({ type: 'checkpoint', packetId: p.id })}>保存进度 {p.id}</button> : null}</div></div>)}</div></section>
    <EventTimeline events={s.events} actors={actors} labels={labels} />
  </div>
}
