'use client'
import Link from 'next/link'
import { StorageNotice, storageLabel } from '../algorithm/storage-notice'
import { useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import { LabConceptLinks } from '../../learning/lab-concept-links'
import { SagaSession } from './session'
import { answersIdentity, identity, initialDraft, sagaExercise, scenarioCommands, scenarioLabels, type Draft, type Scenario } from './lesson'
import { MAX_COMMANDS, runModel, same, type Command, type Config } from './model'
import { SagaLiveView, phaseLabels } from './live-view'
import styles from '../retry-idempotency/retry-lab.module.css'
const goals: Record<Scenario, string> = { 'response-lost': '发布被拒绝后进行补偿。释放配额已经生效，但响应丢失；重试同一步骤，防止重复返还。', 'coordinator-crash': '清理产物已成功，协调者在保存恢复进度之前崩溃。重启后根据日志重试，并安全完成后续补偿。', 'compensation-failure': '让清理产物持续失败。耗尽本轮预算后进入人工处理，修复服务并重新执行，不能把待处理直接标成成功。', manual: '自行注入正向或补偿故障，交错调用、响应、崩溃和恢复。自由实验保存记录，不自动计入挑战进度。' }
const commandLabel = (c: Command) => ({ start: '创建流程', send: '发送当前步骤', 'deliver-request': '执行业务步骤', 'drop-request': '丢弃调用', 'deliver-response': '递送响应', 'drop-response': '丢弃响应', checkpoint: '保存进度', advance: '等待超时', crash: '协调者崩溃', restart: '重启协调者', block: '注入步骤故障', repair: '修复步骤故障', 'resume-review': '人工核查后恢复' })[c.type]
export function SagaLab() {
  const [session] = useState(() => new SagaSession())
  const state = useSyncExternalStore(session.subscribe, session.getSnapshot, session.getSnapshot)
  useEffect(() => { void session.load() }, [session])
  const { draft: d } = state
  const [error, setError] = useState('')
  const frame = useMemo(() => { try { return { result: runModel(d.config, d.commands), error: '' } } catch (e) { return { result: null, error: e instanceof Error ? e.message : '状态无法恢复。' } } }, [d.config, d.commands])
  const guide = useMemo(() => d.scenario === 'manual' ? [] : scenarioCommands(d.config, d.scenario), [d.config, d.scenario])
  const next = same(d.commands, guide.slice(0, d.commands.length)) ? guide[d.commands.length] : undefined
  const completed = state.attempts.find((a) => a.id === state.activeAttemptId)
  const stale = !!completed && identity(completed.draft) !== identity(d)
  const changedAnswers = !!completed && answersIdentity(completed.draft) !== answersIdentity(d)
  const finished = new Set(state.attempts.filter((a) => a.evaluation.task && a.evaluation.explanation).map((a) => a.draft.scenario))
  const edit = (value: Draft) => { try { runModel(value.config, value.commands); session.edit(value); setError('') } catch (e) { setError(e instanceof Error ? e.message : '操作无效。') } }
  const act = (command: Command) => edit({ ...d, commands: [...d.commands, command] })
  const config = (patch: Partial<Config>) => edit({ ...d, config: { ...d.config, ...patch }, commands: [] })
  const answer = (field: 'prediction' | 'phaseAnswer' | 'quotaAnswer' | 'artifactsAnswer' | 'workAnswer' | 'reasonAnswer' | 'reflection', value: string) => edit({ ...d, [field]: value })
  const disabled = !state.ready || !frame.result || d.commands.length >= MAX_COMMANDS
  return <main className={styles.page}>
    <nav className={styles.nav} aria-label="Saga 实验导航"><Link href="/practice">← 全部实验</Link><span>SAGA / COMPENSATION</span><Link href="/learn/sagas">相关原理</Link></nav>
    <header className={styles.hero}><div><span className={styles.eyebrow}>可操作业务恢复 LAB</span><h1>{sagaExercise.title}</h1><p>{sagaExercise.summary}</p></div><div className={styles.progress} aria-label="Saga 学习进度"><strong>{finished.size} / 3 故障挑战已验证</strong><span>业务纠正、持久进度、可恢复性分别核对</span></div></header>
    <LabConceptLinks labId="saga-recovery" />
    <div className={styles.scenarios} role="group" aria-label="Saga 故障场景">{(Object.keys(scenarioLabels) as Scenario[]).map((scenario) => <button key={scenario} disabled={!state.ready} aria-pressed={d.scenario === scenario} onClick={() => edit({ ...initialDraft(), scenario, config: d.config })}>{scenarioLabels[scenario]}</button>)}<span role="status" data-testid="saga-save-status">{storageLabel(state)}</span></div>
    <StorageNotice state={state} session={session} className={styles.error} saveLabel="重试保存 Saga 实验" />
    {state.rejected ? <p role="alert">{state.rejected} 条记录无法验证，保留原记录并排除评分。</p> : null}
    <section className={styles.configuration} aria-label="Saga 配置"><div className={styles.settings}><label>失败后如何处理<select aria-label="Saga 恢复策略" disabled={!state.ready} value={d.config.recovery} onChange={(e) => config({ recovery: e.target.value as Config['recovery'] })}><option value="stop">遇到失败就停止</option><option value="saga">按持久进度执行补偿</option></select></label><label>每步操作的幂等保护<select aria-label="Saga 幂等保护" disabled={!state.ready} value={String(d.config.idempotent)} onChange={(e) => config({ idempotent: e.target.value === 'true' })}><option value="true">同一操作 ID 重放已提交结果</option><option value="false">每次调用重新执行业务操作</option></select></label><label>响应超时<select aria-label="Saga 响应超时" disabled={!state.ready} value={d.config.timeoutMs} onChange={(e) => config({ timeoutMs: Number(e.target.value) })}>{[100, 500, 1000].map((n) => <option key={n} value={n}>{n} ms</option>)}</select></label><label>每步每轮尝试预算<select aria-label="Saga 尝试预算" disabled={!state.ready} value={d.config.maxAttempts} onChange={(e) => config({ maxAttempts: Number(e.target.value) })}>{[2, 3, 5].map((n) => <option key={n} value={n}>{n} 次</option>)}</select></label></div><p className={styles.note}>修改策略会从空状态重开；之前的尝试保留。幂等键是 video-1 / 步骤，重试不会创建新意图。</p></section>
    <section className={styles.guide} aria-label="Saga 步骤引导"><div><strong>{scenarioLabels[d.scenario]}</strong><p>{goals[d.scenario]}</p></div><div className={styles.guideActions}>{d.scenario !== 'manual' ? <><button className={styles.primary} disabled={disabled || !next} onClick={() => { if (next) act(next) }}>{next ? `下一步：${commandLabel(next)}` : '向导已完成或进入自由操作'}</button><button disabled={!state.ready} onClick={() => edit({ ...d, commands: guide })}>运行完整 Saga 故障示例</button></> : null}<button disabled={!state.ready || !state.undoCount} onClick={() => session.undo()}>撤销</button><button disabled={!state.ready || !state.redoCount} onClick={() => session.redo()}>重做</button><button disabled={!state.ready} onClick={() => edit({ ...d, commands: [] })}>清空 Saga 实验</button></div></section>
    {error || frame.error ? <p role="alert" className={styles.error}>{error || frame.error}<button onClick={() => edit(initialDraft())}>恢复默认 Saga 实验</button></p> : null}
    {frame.result ? <SagaLiveView state={frame.result} config={d.config} act={act} disabled={disabled} /> : null}
    <section className={styles.panel}><h2>补偿后，哪些状态真的改变了？</h2><div className={styles.answers}><label>最初预测<select aria-label="Saga 实验预测" disabled={!state.ready} value={d.prediction} onChange={(e) => answer('prediction', e.target.value)}><option value="">预测允许出错</option><option value="unknown">还不确定</option><option value="rollback">补偿后就像从未执行过</option><option value="correction">可以纠正业务状态，但不一定恢复原样</option></select></label><label>流程最终状态<select aria-label="Saga 流程结果作答" disabled={!state.ready} value={d.phaseAnswer} onChange={(e) => answer('phaseAnswer', e.target.value)}><option value="">选择状态</option>{Object.entries(phaseLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{([['quotaAnswer', '可用配额'], ['artifactsAnswer', '保留产物'], ['workAnswer', '累计转码工作']] as const).map(([field, label]) => <label key={field}>{label}<input aria-label={`Saga ${label}作答`} disabled={!state.ready} value={d[field]} inputMode="numeric" maxLength={5} onChange={(e) => answer(field, e.target.value)} /></label>)}<label>补偿意味着什么？<select aria-label="Saga 边界解释" disabled={!state.ready} value={d.reasonAnswer} onChange={(e) => answer('reasonAnswer', e.target.value)}><option value="">选择解释</option><option value="business-correction">补偿是可失败、需幂等和恢复进度的业务纠正</option><option value="global-rollback">所有服务进入一次全局事务回滚</option><option value="success">补偿完成代表视频已成功发布</option></select></label></div><label>复盘（保存原文，不自动评分）<textarea aria-label="Saga 实验复盘" disabled={!state.ready} value={d.reflection} rows={2} maxLength={4000} onChange={(e) => answer('reflection', e.target.value)} /></label><button className={styles.primary} disabled={!state.ready || !frame.result || !d.commands.length} onClick={() => { try { session.run(); setError('') } catch (e) { setError(e instanceof Error ? e.message : '无法核验。') } }}>核对并保存 Saga 结果</button><div className={styles.feedback} data-testid="saga-feedback" aria-live="polite"><h3>{stale ? '动作或配置已改变，请重新核验' : !completed ? '操作后核对结果' : completed.evaluation.task ? !changedAnswers && completed.evaluation.explanation ? '本关 Saga 验证通过' : '恢复目标满足，继续解释证据' : '流程或业务状态尚未满足目标'}</h3>{completed && !stale ? <ul>{completed.evaluation.messages.map((message) => <li key={message}>{message}</li>)}</ul> : <p>检查器重算完整账本与恢复日志，不按策略名称判定通过。</p>}</div></section>
    <section className={styles.panel} data-testid="saga-history"><h2>已保存 Saga 实验 · {state.attempts.length}</h2>{state.attempts.slice(0, 10).map((a) => <details className={styles.historyItem} key={a.id}><summary>{scenarioLabels[a.draft.scenario]} · {phaseLabels[a.result.phase]} · {a.evaluation.task && a.evaluation.explanation ? '已验证' : '已记录'}</summary><p>{new Date(a.createdAt).toLocaleString('zh-CN')} · {a.draft.reflection || '尚未填写复盘。'}</p><button disabled={!state.ready} onClick={() => session.restoreAttempt(a)}>恢复 Saga 尝试</button></details>)}</section>
    <footer className={styles.boundary}><strong>可执行模型的范围</strong><p>saga-v1：一个视频流程、一个协调者、多个符号本地业务步骤和持久恢复日志。各服务的效果与本地去重结果在同一步原子提交；协调者要另行保存进度。稳定状态保留是声明前提，不模拟磁盘丢失、复制或真实视频处理。</p><p>暂时失败不写入永久去重结果；已提交的成功和业务拒绝在本次实验内保留。恢复与重试始终使用原操作 ID。配额释放增加余额，清理操作删除产物，已消耗的转码工作保留。这个补偿顺序属于本案例的业务规则，其他业务需要自己的纠正规则。</p><p>最多 150 个命令、30 次调用、10,000 ms。预算耗尽进入人工处理，人工恢复后仍需实际执行步骤。没有模拟多流程竞争、并发 Saga、外部支付撤回、真实 RPC 或全局事务。</p></footer>
  </main>
}
