import { expect, test, type Page } from '@playwright/test'
test.use({ actionTimeout: 15000 })
const click = (p: Page, name: string) => p.getByRole('button', { name, exact: true }).click()
const select = (p: Page, name: string, value: string) => p.getByRole('combobox', { name, exact: true }).selectOption(value)
const fill = (p: Page, name: string, value: string) => p.getByRole('textbox', { name, exact: true }).fill(value)
async function open(p: Page, id: string) { await p.goto(`/practice/${id}#experiment-state`); await expect(p.getByTestId('experiment-save-status')).toHaveText('当前操作已保存') }
async function save(p: Page) { await click(p, '核对并保存实验'); await expect(p.getByTestId('experiment-save-status')).toHaveText('当前操作已保存') }
async function concurrentAnswer(p: Page, remaining: string, bookings: string, valid = 'safe') { await select(p, '实验预测', 'unknown'); await fill(p, '剩余库存作答', remaining); await fill(p, '实际预订作答', bookings); await select(p, '并发不变量作答', valid); await select(p, '并发边界解释', 'different-boundaries'); await save(p) }
async function overloadAnswer(p: Page) {
  await select(p, '实验预测', 'unknown')
  for (const [name, id] of [['原始到达数作答', 'overload-offered'], ['实际尝试数作答', 'overload-attempts'], ['及时成功数作答', 'overload-successes'], ['服务端完成数作答', 'overload-completed']]) await fill(p, name!, (await p.getByTestId(id!).textContent())!)
  await select(p, '过载边界解释', 'work-and-outcome'); await save(p)
}
test('exposes overselling and lost updates, then fixes the real interleaving with CAS', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/learn/concurrency-control'); await page.locator('#labs a[href="/practice/concurrent-update"]').click()
  await click(page, '读取 A'); await click(page, '读取 B'); await click(page, '提交 A'); await click(page, '提交 B')
  await expect(page.getByTestId('concurrent-remaining')).toHaveText('0'); await expect(page.getByTestId('concurrent-reservations')).toHaveText('2'); await expect(page.getByTestId('concurrent-invariant')).toHaveText('已违反')
  await concurrentAnswer(page, '0', '2', 'broken'); await expect(page.getByTestId('experiment-feedback')).toContainText('运行目标尚未满足')
  await select(page, '并发幂等保护', 'true'); await click(page, '运行完整实验示例')
  await expect(page.getByTestId('concurrent-invariant')).toHaveText('已违反')
  await click(page, '运行策略对照'); await expect(page.getByRole('table', { name: '实验策略对照表', exact: true })).toContainText('只开启幂等')
  await select(page, '并发控制策略', 'cas'); await click(page, '读取 A'); await click(page, '读取 B'); await click(page, '提交 A'); await click(page, '提交 B')
  await expect(page.getByTestId('concurrent-B')).toHaveText('版本冲突，需重读'); await expect(page.getByTestId('concurrent-reservations')).toHaveText('1')
  await click(page, '读取 B'); await click(page, '提交 B'); await concurrentAnswer(page, '0', '1')
  await expect(page.getByTestId('experiment-feedback')).toContainText('本关实验验证通过')
  await page.reload(); await expect(page.getByTestId('experiment-feedback')).toContainText('本关实验验证通过')
  await click(page, '两个名额的丢失更新'); await select(page, '并发控制策略', 'read-write'); await click(page, '运行完整实验示例')
  await expect(page.getByTestId('concurrent-remaining')).toHaveText('1'); await expect(page.getByTestId('concurrent-reservations')).toHaveText('2')
  await select(page, '并发控制策略', 'cas'); await click(page, '运行完整实验示例'); await concurrentAnswer(page, '0', '2')
  await expect(page.getByLabel('实验学习进度')).toContainText('2 / 3')
  expect(errors).toEqual([])
})
test('restores a lock wait and recovers a crashed transaction without leaking lesson records', async ({ page }) => {
  test.setTimeout(60000)
  await open(page, 'concurrent-update'); await click(page, '提交前崩溃'); await select(page, '并发控制策略', 'row-lock')
  await click(page, '读取 A'); await click(page, '读取 B'); await expect(page.getByTestId('concurrent-B')).toHaveText('等待行锁')
  await expect(page.getByRole('button', { name: '提交 B', exact: true })).toBeDisabled()
  await expect(page.getByTestId('experiment-save-status')).toHaveText('当前操作已保存'); await page.reload()
  await expect(page.getByTestId('concurrent-lock')).toHaveText('A')
  await click(page, '崩溃 A'); await expect(page.getByTestId('concurrent-lock')).toHaveText('B')
  await click(page, '读取 B'); await click(page, '提交 B'); await click(page, '重启 A'); await click(page, '读取 A'); await click(page, '提交 A'); await concurrentAnswer(page, '0', '1')
  await expect(page.getByTestId('experiment-feedback')).toContainText('本关实验验证通过')
  await click(page, '清空当前实验'); await expect(page.getByTestId('experiment-feedback')).toContainText('动作或配置已改变')
  await click(page, '撤销'); await expect(page.getByTestId('experiment-feedback')).toContainText('本关实验验证通过')
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.locator('main').evaluate((e) => e.scrollWidth <= e.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/concurrent-mobile.png' })
  await open(page, 'overload'); await expect(page.getByTestId('experiment-history').locator('details')).toHaveCount(0)
  await open(page, 'concurrent-update'); await expect(page.getByTestId('experiment-history').locator('details')).toHaveCount(1)
})
test('reduces overload without reducing original demand, and shows late work separately', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/learn/overload-control'); await page.locator('#labs a[href="/practice/overload"]').click()
  await click(page, '处理减速到 500 ms'); await click(page, '启动固定 12 个请求'); await click(page, '推进 200 ms')
  await expect(page.getByTestId('overload-attempts')).toHaveText('4')
  await expect(page.getByTestId('overload-completed')).toHaveText('0')
  await expect(page.getByTestId('experiment-save-status')).toHaveText('当前操作已保存'); await page.reload()
  await expect(page.getByTestId('overload-clock')).toHaveText('200 ms')
  await click(page, '推进 200 ms'); await click(page, '推进 200 ms'); await click(page, '恢复到 100 ms'); await click(page, '推进到实验结束')
  const baseline = Number(await page.getByTestId('overload-attempts').textContent())
  await overloadAnswer(page); await expect(page.getByTestId('experiment-feedback')).toContainText('运行目标尚未满足')
  await select(page, '过载重试策略', 'backoff'); await select(page, '客户端发送窗口', '1'); await select(page, '过载队列上限', '2'); await click(page, '运行完整实验示例')
  await expect(page.getByTestId('overload-offered')).toHaveText('12'); await expect(page.getByTestId('overload-successes')).toHaveText('12'); await expect(page.getByTestId('overload-attempts')).toHaveText('12')
  expect(baseline).toBeGreaterThan(12)
  await overloadAnswer(page); await expect(page.getByTestId('experiment-feedback')).toContainText('本关实验验证通过')
  await click(page, '突发流量与有限队列'); await click(page, '运行完整实验示例'); await overloadAnswer(page)
  await expect(page.getByTestId('overload-peak')).toHaveText('0'); await expect(page.getByLabel('实验学习进度')).toContainText('2 / 3')
  await click(page, '截止后仍在处理'); await select(page, '客户端发送窗口', '0'); await select(page, '过载队列上限', '60'); await select(page, '过载重试策略', 'immediate'); await select(page, '过期工作检查', 'true'); await click(page, '运行完整实验示例')
  await expect(page.getByTestId('overload-successes')).toHaveText('1'); await expect(page.getByTestId('overload-completed')).toHaveText('2'); await expect(page.getByTestId('overload-deadlines')).toHaveText('11')
  await overloadAnswer(page); await expect(page.getByLabel('实验学习进度')).toContainText('3 / 3')
  await click(page, '运行策略对照'); await expect(page.getByRole('table', { name: '实验策略对照表', exact: true }).getByRole('row')).toHaveCount(5)
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.locator('main').evaluate((e) => e.scrollWidth <= e.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/overload-mobile.png' })
  expect(errors).toEqual([])
})
test('reports failed extension saves and allows keyboard recovery without erasing old attempts', async ({ page }) => {
  test.setTimeout(60000)
  await page.addInitScript(() => {
    const original = IDBDatabase.prototype.transaction; const flags = { fail: false }
    IDBDatabase.prototype.transaction = function (...args: Parameters<typeof original>) { if (flags.fail && this.name === 'system-design-algorithm-labs' && args[1] === 'readwrite') throw new DOMException('test quota', 'QuotaExceededError'); return original.apply(this, args) }
    Object.assign(window, { extensionStorageFlags: flags })
  })
  await open(page, 'overload'); await select(page, '过载重试策略', 'backoff'); await select(page, '客户端发送窗口', '1')
  await page.evaluate(() => { (window as unknown as { extensionStorageFlags: { fail: boolean } }).extensionStorageFlags.fail = true })
  await click(page, '运行完整实验示例'); await click(page, '核对并保存实验')
  await expect(page.getByTestId('experiment-save-status')).toContainText('未保存'); await expect(page.getByTestId('experiment-history').locator('details')).toHaveCount(1)
  await page.evaluate(() => { (window as unknown as { extensionStorageFlags: { fail: boolean } }).extensionStorageFlags.fail = false })
  await page.getByRole('button', { name: '重试保存实验', exact: true }).focus(); await page.keyboard.press('Enter')
  await expect(page.getByTestId('experiment-save-status')).toHaveText('当前操作已保存'); await page.reload()
  await expect(page.getByTestId('overload-successes')).toHaveText('12'); await expect(page.getByTestId('experiment-history').locator('details')).toHaveCount(1)
})
