import { expect, test, type Page } from '@playwright/test'
import { compare, distribute } from '../src/features/practice/distribution/model'
import { challenge, type Mode } from '../src/features/practice/distribution/lesson'
import type { Method } from '../src/features/practice/distribution/model'

test.use({ actionTimeout: 10_000 })

const title = '扩容时，哪些 key 需要换节点？'
async function open(page: Page) {
  await page.goto('/practice')
  await page.getByRole('link', { name: title, exact: true }).click()
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
  await expect(page.getByTestId('algorithm-save-status')).toHaveText('已保存到此浏览器')
}
async function solve(page: Page, mode: Mode, method: Method) {
  const draft = challenge(mode, method)
  const before = distribute(draft.input)
  draft.input.nodes = mode === 'add' ? [...draft.input.nodes, 'node-e'] : draft.input.nodes.filter((node) => node !== 'node-c')
  const after = distribute(draft.input)
  const comparison = compare(before, after)!
  const moved = after.assignments.find((item) => before.assignments.find((old) => old.key === item.key)?.owner !== item.owner)!
  await page.getByRole('combobox', { name: '你的预测', exact: true }).selectOption('uncertain')
  await page.getByRole('button', { name: mode === 'add' ? '+ 新增 node-e' : '移除 node-c', exact: true }).click()
  await page.getByRole('button', { name: '运行并记录', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('操作完成，继续用证据解释')
  await expect(page.getByTestId('remapped-count')).toHaveText(comparison.remapped.toLocaleString())
  await page.getByLabel('发生变化的 key', { exact: true }).fill(moved.key)
  await page.getByLabel('需要重映射的 key 数', { exact: true }).fill(String(comparison.remapped))
  const local = comparison.transfers.every((item) => item.from === item.to || (mode === 'add' ? item.to === 'node-e' : item.from === 'node-c'))
  await page.getByRole('combobox', { name: '本次变化涉及哪些节点？', exact: true }).selectOption(local ? 'local' : 'spread')
  await page.getByRole('combobox', { name: '较少重映射能说明什么？', exact: true }).selectOption('separate')
  await page.getByLabel('你的复盘（保留原文，不自动判分）', { exact: true }).fill('需要分别观察归属变化和键数均衡。')
  await expect(page.getByTestId('algorithm-feedback')).toContainText('复盘有未提交的修改')
  await page.getByRole('button', { name: '检查解释并记录', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('本次挑战通过')
  await expect(page.getByTestId('algorithm-save-status')).toHaveText('已保存到此浏览器')
}

test('completes all three controlled additions, a separate removal task, and restores evidence', async ({ page }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await open(page)
  await expect(page.getByRole('button', { name: '运行并记录', exact: true })).toBeDisabled()
  await solve(page, 'add', 'modulo')
  await page.getByRole('button', { name: '单 token 环', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('有未运行的修改')
  await solve(page, 'add', 'ring')
  await page.getByRole('button', { name: '虚拟节点环', exact: true }).click()
  await solve(page, 'add', 'vnodes')
  await expect(page.getByLabel('学习进度')).toContainText('3 / 3 方法已验证')
  await page.getByRole('button', { name: '进入新数据集的移除节点挑战', exact: false }).click()
  await solve(page, 'remove', 'vnodes')
  await expect(page.getByLabel('学习进度')).toContainText('本题挑战已完成')
  await page.reload()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('本次挑战通过')
  await expect(page.getByLabel('学习进度')).toContainText('本题挑战已完成')
  await expect(page.getByRole('textbox', { name: '你的复盘（保留原文，不自动判分）', exact: true })).toHaveValue('需要分别观察归属变化和键数均衡。')
  await expect(page.getByTestId('algorithm-history').locator('details')).toHaveCount(8)
  await expect(page.getByRole('button', { name: '撤销', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '重置实验', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('有未运行的修改')
  await expect(page.getByTestId('algorithm-history').locator('details')).toHaveCount(8)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('本次挑战通过')
  await page.screenshot({ path: 'test-results/consistent-hashing-desktop.png', fullPage: true })
  expect(errors).toEqual([])
})

test('supports controlled exploration, key inspection, semantic invalidation and maximum bounded input', async ({ page }) => {
  test.setTimeout(90_000)
  await open(page)
  await page.getByRole('button', { name: '自由探索', exact: true }).click()
  await page.getByRole('button', { name: '固定当前配置为基线', exact: true }).click()
  await page.getByRole('button', { name: '+ 添加节点', exact: true }).click()
  await page.getByRole('button', { name: '运行并记录', exact: true }).click()
  await page.getByLabel('只看归属变化', { exact: true }).check()
  const table = page.getByRole('table', { name: '完整 key 归属表（分页）', exact: true })
  await expect(table.locator('tbody tr').first()).toContainText('变化')
  await table.locator('tbody button').first().focus()
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: '用这个 key 作答', exact: true }).click()
  await expect(page.getByLabel('发生变化的 key', { exact: true })).not.toHaveValue('')
  await page.getByRole('button', { name: '虚拟节点环', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('有未运行的修改')
  await expect(page.getByTestId('algorithm-feedback')).not.toContainText('本次挑战通过')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).not.toContainText('有未运行的修改')
  await page.getByRole('button', { name: '重做', exact: true }).click()
  await page.getByText('开始新的数据集', { exact: true }).click()
  await page.getByLabel('新 Seed', { exact: true }).fill('max-input')
  await page.getByRole('combobox', { name: 'Key 数量', exact: true }).selectOption('4096')
  await page.getByRole('button', { name: '生成新数据集', exact: true }).click()
  await expect(page.getByTestId('remapped-count')).toHaveText('—')
  await expect(page.getByText('数据集或版本不同，不提供重映射对照。', { exact: false })).toBeVisible()
  await page.getByRole('combobox', { name: '每节点 token 数', exact: true }).selectOption('128')
  for (let i = 0; i < 7; i++) await page.getByRole('button', { name: '+ 添加节点', exact: true }).click()
  await expect(page.getByRole('button', { name: '+ 添加节点', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '固定当前配置为基线', exact: true }).click()
  const start = Date.now()
  await page.getByRole('button', { name: '运行并记录', exact: true }).click()
  await expect(page.getByTestId('algorithm-feedback')).toContainText('运行证据已记录')
  await expect(page.getByTestId('algorithm-save-status')).toHaveText('已保存到此浏览器')
  expect(Date.now() - start).toBeLessThan(5000)
  await expect(page.getByText('1536 tokens', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '清除筛选', exact: true }).click()
  await expect(table.locator('tbody tr')).toHaveCount(20)
  await expect(page.getByText('4096 条 · 第 1 / 205 页', { exact: true })).toBeVisible()
  await page.getByLabel('哈希环缩放', { exact: true }).fill('1.4')
  await expect(page.getByTestId('algorithm-feedback')).not.toContainText('有未运行的修改')
  await page.reload()
  await expect(page.getByText('1536 tokens', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: '运行并记录', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('main').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/consistent-hashing-mobile.png', fullPage: true })
})

test('keeps simulation history separate and makes failed saves visible and retryable', async ({ page }) => {
  test.setTimeout(60_000)
  await page.addInitScript(() => {
    const original = IDBDatabase.prototype.transaction
    const flags = { fail: false }
    // Install before Dexie captures the native transaction function at open.
    IDBDatabase.prototype.transaction = function (...args: Parameters<typeof original>) {
      if (flags.fail && this.name === 'system-design-algorithm-labs' && args[1] === 'readwrite') throw new DOMException('test quota', 'QuotaExceededError')
      return original.apply(this, args)
    }
    Object.assign(window, { algorithmStorageFlags: flags })
  })
  await page.goto('/practice/service-queue-replicas')
  await page.getByRole('button', { name: '运行并检查', exact: true }).click()
  await expect(page.getByTestId('exercise-attempts')).toContainText('1 个副本')
  await open(page)
  await page.evaluate(() => { (window as unknown as { algorithmStorageFlags: { fail: boolean } }).algorithmStorageFlags.fail = true })
  await page.getByRole('combobox', { name: '你的预测', exact: true }).selectOption('uncertain')
  await page.getByRole('button', { name: '+ 新增 node-e', exact: true }).click()
  await page.getByRole('button', { name: '运行并记录', exact: true }).click()
  await expect(page.getByTestId('algorithm-save-status')).toContainText('未保存')
  await expect(page.getByTestId('algorithm-history').locator('details')).toHaveCount(1)
  await page.evaluate(() => { (window as unknown as { algorithmStorageFlags: { fail: boolean } }).algorithmStorageFlags.fail = false })
  await page.getByRole('button', { name: '重试保存当前实验', exact: true }).click()
  await expect(page.getByTestId('algorithm-save-status')).toHaveText('已保存到此浏览器')
  await page.goto('/practice/service-queue-replicas')
  await expect(page.getByTestId('exercise-attempts')).toContainText('1 个副本')
  await open(page)
  await expect(page.getByTestId('algorithm-history').locator('details')).toHaveCount(1)
  await expect(page.getByTestId('algorithm-feedback')).toContainText('操作完成，继续用证据解释')
})
