import { expect, test, type Page } from '@playwright/test'
test.use({ actionTimeout: 15000 })
const click = (page: Page, name: string) => page.getByRole('button', { name, exact: true }).click()
async function open(page: Page, id: 'heartbeat' | 'lease-fencing') { await page.goto(`/practice/${id}#coordination-state`); await expect(page.getByTestId('coordination-save-status')).toHaveText('当前操作已保存') }
async function answer(page: Page, actual: string, value?: string, rejected?: string) {
  await page.getByRole('combobox', { name: '协调实验预测', exact: true }).selectOption('unknown')
  await page.getByRole('combobox', { name: '观察者判断作答', exact: true }).selectOption('suspected')
  await page.getByRole('combobox', { name: '真实状态作答', exact: true }).selectOption(actual)
  if (value !== undefined) { await page.getByRole('textbox', { name: '资源结果作答', exact: true }).fill(value); await page.getByRole('textbox', { name: '拒绝写入作答', exact: true }).fill(rejected!) }
  await page.getByRole('combobox', { name: '协调边界解释', exact: true }).selectOption(value === undefined ? 'observation-not-proof' : 'resource-token-check')
  await click(page, '核对并保存协调结果')
  await expect(page.getByTestId('coordination-save-status')).toHaveText('当前操作已保存')
}
test('distinguishes pause, partition and crash from local suspicion and recovers delayed heartbeats', async ({ page }) => {
  test.setTimeout(60000)
  const errors: string[] = []; page.on('pageerror', (e) => errors.push(e.message))
  await open(page, 'heartbeat')
  for (const [scenario, actual, truth] of [['进程暂停', 'paused', '已暂停'], ['网络分区', 'running', '运行中'], ['进程崩溃', 'crashed', '已崩溃']]) {
    await click(page, scenario!); await click(page, '运行完整协调故障示例')
    await expect(page.getByTestId('coordination-observation')).toHaveText('怀疑失联')
    await expect(page.getByTestId('coordination-truth')).toHaveText(truth!)
    await answer(page, actual!)
    await expect(page.getByTestId('coordination-feedback')).toContainText('本关协调验证通过')
  }
  await expect(page.getByLabel('协调实验学习进度')).toContainText('3 / 3')
  await click(page, '清空协调实验'); await click(page, '发送 A 心跳'); await click(page, '崩溃 A'); await click(page, '推进 1000 ms')
  await click(page, '递送 heartbeat-1')
  await expect(page.getByTestId('coordination-truth')).toHaveText('已崩溃')
  await expect(page.getByTestId('coordination-observation')).toHaveText('近期收到心跳')
  await expect(page.getByTestId('coordination-feedback')).toContainText('动作或配置已改变')
  await expect(page.getByTestId('coordination-save-status')).toHaveText('当前操作已保存')
  await page.reload()
  await expect(page.getByTestId('coordination-observation')).toHaveText('近期收到心跳')
  await expect(page.getByTestId('coordination-history').locator('details')).toHaveCount(3)
  expect(errors).toEqual([])
})
test('protects the resource from stale generations and exposes the unseen-token boundary', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/fencing'); await page.locator('#labs a[href="/practice/lease-fencing"]').click()
  await click(page, '运行完整协调故障示例')
  await expect(page.getByTestId('coordination-value')).toHaveText('A-old')
  await answer(page, 'running', 'A-old', '0')
  await expect(page.getByTestId('coordination-feedback')).toContainText('故障或保护条件尚未满足')
  await page.getByRole('combobox', { name: '资源端 Fencing', exact: true }).selectOption('true')
  await click(page, '申请 A 租约'); await page.getByRole('textbox', { name: 'A 写入值', exact: true }).fill('A-old'); await click(page, '准备 A 写入'); await click(page, '暂停 A')
  await expect(page.getByTestId('coordination-save-status')).toHaveText('当前操作已保存'); await page.reload()
  await expect(page.getByRole('button', { name: '递送 write-1', exact: true })).toBeEnabled()
  await click(page, '推进 1000 ms'); await click(page, '推进 500 ms'); await click(page, '申请 B 租约')
  await page.getByRole('textbox', { name: 'B 写入值', exact: true }).fill('B-new'); await click(page, '准备 B 写入'); await click(page, '递送 write-2'); await click(page, '恢复 A'); await click(page, '递送 write-1')
  await expect(page.getByTestId('coordination-value')).toHaveText('B-new')
  await expect(page.getByTestId('coordination-rejected')).toHaveText('1')
  await answer(page, 'running', 'B-new', '1')
  await expect(page.getByTestId('coordination-feedback')).toContainText('本关协调验证通过')
  await click(page, '怀疑不等于租约到期'); await click(page, '运行完整协调故障示例'); await answer(page, 'running', 'A-valid', '0')
  await expect(page.getByTestId('coordination-lease')).toContainText('A · token 1')
  await click(page, '资源尚未见到新 token'); await click(page, '运行完整协调故障示例'); await answer(page, 'running', 'B-new', '0')
  await expect(page.getByLabel('协调实验学习进度')).toContainText('3 / 3')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.locator('main').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/coordination-mobile.png' })
  await open(page, 'heartbeat'); await expect(page.getByTestId('coordination-history').locator('details')).toHaveCount(0)
})
