import { test, expect } from '@playwright/test'

test('learns Feed tradeoffs, validates all fault cases and restores separate product evidence', async ({ page }) => {
  test.setTimeout(60000)
  const errors: string[] = []; page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/practice')
  await page.getByRole('link', { name: 'News Feed 设计：分发与名人热点', exact: true }).click()
  await expect(page.getByRole('button', { name: '执行本关场景', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '执行本关场景', exact: true }).click()
  await page.getByRole('button', { name: '核验并保存设计', exact: true }).click()
  await expect(page.getByTestId('product-feedback')).toContainText('本关目标尚未满足')
  await expect(page.getByTestId('product-feedback')).toContainText('实际 14 次')
  await page.getByLabel('分发策略', { exact: true }).selectOption('hybrid')
  await page.getByLabel('发布可靠性', { exact: true }).selectOption('atomic')
  await page.getByLabel('收件箱写入', { exact: true }).selectOption('on')
  await page.getByLabel('读取可见性', { exact: true }).selectOption('source')
  await expect(page.getByTestId('product-feedback')).toContainText('请重新核验')
  for (const title of ['名人写放大', '提交与发布中断', '同一事件重投', '删除与旧收件箱']) {
    await page.getByRole('button', { name: title, exact: true }).click()
    await page.getByRole('button', { name: '执行本关场景', exact: true }).click()
    await page.getByRole('button', { name: '核验并保存设计', exact: true }).click()
    await expect(page.getByTestId('product-feedback')).toContainText('本关设计验证通过')
  }
  await expect(page.getByTestId('product-progress')).toContainText('4 / 4')
  await page.getByRole('button', { name: '运行方案对照', exact: true }).click()
  await expect(page.getByRole('table', { name: '设计方案对照', exact: true }).locator('tbody tr')).toHaveCount(3)
  await expect(page.getByTestId('product-save-status')).toHaveText('当前操作已保存')
  await page.reload()
  await expect(page.getByTestId('product-progress')).toContainText('4 / 4')
  await expect(page.getByTestId('product-feedback')).toContainText('本关设计验证通过')
  await expect(page.getByTestId('product-history').locator('details')).toHaveCount(5)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
