import { expect, test } from '@playwright/test'

test('builds a short-link design, rejects missing paths, compares alternatives and restores notes', async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto('/practice')
  await page.getByRole('link', { name: '短链接设计：跳转读取路径', exact: true }).click()
  await expect(page.getByRole('heading', { name: '痛点：为什么需要这个设计？' })).toBeVisible()
  const run = page.getByRole('button', { name: '运行并验证设计', exact: true })
  await expect(run).toBeEnabled()
  await run.click()
  await expect(page.getByRole('complementary', { name: '综合设计任务' }).getByRole('alert')).toContainText('必须连接')
  await page.getByRole('button', { name: '添加 跳转 Service', exact: true }).click()
  await page.getByRole('button', { name: '添加 映射 Database', exact: true }).click()
  await page.getByLabel('连接终点', { exact: true }).selectOption({ label: 'Redirect Service' })
  await page.getByRole('button', { name: '连接组件', exact: true }).click()
  await page.getByLabel('连接起点', { exact: true }).selectOption({ label: 'Redirect Service' })
  await page.getByLabel('连接终点', { exact: true }).selectOption({ label: 'Code → URL Database' })
  await page.getByRole('button', { name: '连接组件', exact: true }).click()
  await run.click()
  await expect(page.getByTestId('design-feedback')).toContainText('继续调整设计', { timeout: 15000 })
  await page.getByLabel('数据库连接', { exact: true }).selectOption('8')
  await expect(page.getByTestId('design-feedback')).toContainText('设计已修改')
  await run.click()
  await expect(page.getByTestId('design-feedback')).toContainText('本关目标已达成', { timeout: 15000 })
  await page.getByText('参考方案与提示', { exact: true }).click()
  await page.getByRole('button', { name: '参考：缓存分担读取', exact: true }).click()
  await run.click()
  await expect(page.getByTestId('design-feedback')).toContainText('本关目标已达成', { timeout: 15000 })
  await expect(page.getByTestId('design-attempts').locator('tbody tr')).toHaveCount(3)
  await page.getByTestId('design-feedback').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/design-short-link-desktop.png' })
  await page.getByLabel('复盘：哪条证据支持结论，还缺什么？', { exact: true }).fill('缓存减少了读取，但冷启动仍需要数据库连接；撤销一致性尚未验证。')
  await expect(page.getByRole('region', { name: '设计笔记' })).toContainText('当前操作已保存')
  await page.reload()
  await expect(run).toBeEnabled()
  await expect(page.getByTestId('design-feedback')).toContainText('本关目标已达成')
  await expect(page.getByTestId('design-attempts').locator('tbody tr')).toHaveCount(3)
  await expect(page.getByLabel('复盘：哪条证据支持结论，还缺什么？')).toHaveValue(/冷启动/)
  await page.getByRole('button', { name: '恢复方案 1', exact: true }).click()
  await expect(page.getByTestId('design-feedback')).toContainText('设计已修改')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('keeps design records separate from foundational labs and the free workbench', async ({ page }) => {
  await page.goto('/practice/design-short-link')
  await expect(page.getByRole('button', { name: '运行并验证设计', exact: true })).toBeEnabled()
  await page.getByText('参考方案与提示', { exact: true }).click()
  await page.getByRole('button', { name: '参考：数据库扩容', exact: true }).click()
  await page.getByRole('link', { name: '缓存压力 →', exact: true }).click()
  await expect(page.getByRole('button', { name: '8 条缓存', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: '全部练习', exact: true }).click()
  await page.getByRole('link', { name: '短链接设计：跳转读取路径', exact: true }).click()
  await expect(page.getByLabel('数据库连接', { exact: true })).toHaveValue('8')
  await expect(page.getByTestId('design-attempts').locator('tbody tr')).toHaveCount(0)
})
