import { expect, test } from '@playwright/test'

test('completes all drive workflows with real content, sync, explicit conflicts, trash and revocation', async ({ page }) => {
  test.setTimeout(60000)
  await page.goto('/practice')
  await page.getByRole('link', { name: '云盘设计：文件、同步、冲突与分享', exact: true }).click()
  await expect(page.getByRole('button', { name: '执行本关场景', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '内容与文件条目', exact: true }).click()
  await page.getByRole('button', { name: '执行本关场景', exact: true }).click()
  await page.getByRole('button', { name: '核验并保存设计', exact: true }).click()
  await expect(page.getByTestId('product-feedback')).toContainText('本关目标尚未满足')
  await expect(page.getByRole('table', { name: '真实下载内容', exact: true })).toContainText('元数据指向缺失内容')
  await page.getByLabel('文件发布边界', { exact: true }).selectOption('durable')
  await page.getByLabel('并发编辑处理', { exact: true }).selectOption('copy')
  await page.getByLabel('元数据与同步日志', { exact: true }).selectOption('atomic')
  await page.getByLabel('设备同步检查点', { exact: true }).selectOption('atomic')
  await page.getByLabel('删除与离线旧写', { exact: true }).selectOption('tombstone')
  await page.getByLabel('分享撤销语义', { exact: true }).selectOption('recheck')
  await page.getByLabel('文件提交幂等', { exact: true }).selectOption('key')
  for (const name of ['新文件上传与目录同步', '内容与文件条目', '两台设备并发编辑', '提交中断与重试同步', '同步设备崩溃', '离线旧写与删除', '分享链接撤销', '文件夹、移动与回收站', '文件版本与内容恢复']) {
    await page.getByRole('button', { name, exact: true }).click()
    await page.getByRole('button', { name: '执行本关场景', exact: true }).click()
    await page.getByRole('button', { name: '核验并保存设计', exact: true }).click()
    await expect(page.getByTestId('product-feedback')).toContainText('本关设计验证通过')
  }
  await expect(page.getByTestId('product-progress')).toContainText('9 / 9')
  await expect(page.getByRole('table', { name: '真实下载内容', exact: true })).toContainText('initial content')
  await page.getByLabel('复盘：哪条证据支持结论，还缺什么？', { exact: true }).fill('内容、元数据、同步 cursor 和分享授权具有不同的提交边界。')
  await expect(page.getByRole('region', { name: '设计笔记' })).toContainText('当前操作已保存')
  await expect(page.getByTestId('product-save-status')).toHaveText('当前操作已保存')
  await page.reload()
  await expect(page.getByTestId('product-progress')).toContainText('9 / 9')
  await expect(page.getByTestId('product-feedback')).toContainText('本关设计验证通过')
  await expect(page.getByLabel('复盘：哪条证据支持结论，还缺什么？')).toHaveValue(/提交边界/)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
