import { expect, test, type Page } from '@playwright/test'
import { hotChallenge, type Stage } from '../src/features/practice/hot-key/lesson'
import { generateWorkload, runHotModel, topKeys } from '../src/features/practice/hot-key/model'

test.use({ actionTimeout: 15000 })
const title = '数据均匀，为什么请求仍集中？'
async function open(page: Page) {
  await page.goto('/practice')
  await page.getByRole('link', { name: title, exact: true }).click()
  await expect(page).toHaveURL(/\/practice\/hot-key$/)
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
  await expect(page.getByTestId('hot-save-status')).toHaveText('已保存到此浏览器')
}
async function solve(page: Page, stage: Stage) {
  const draft = hotChallenge(stage)
  await page.getByRole('combobox', { name: '热点实验预测', exact: true }).selectOption('balanced')
  if (stage === 'hotspot') {
    draft.input.workload = generateWorkload(draft.input.distribution, { pattern: 'hotspot' })
    await page.getByRole('combobox', { name: '访问分布', exact: true }).selectOption('hotspot')
  } else if (stage === 'shards') {
    draft.input.distribution.virtualNodes = 128
    await page.getByRole('combobox', { name: '热点每节点 token 数', exact: true }).selectOption('128')
  } else {
    draft.input.cache.enabled = true
    await page.getByRole('combobox', { name: '读取缓存', exact: true }).selectOption('on')
  }
  const result = runHotModel(draft.input)
  const hottest = topKeys(result)[0]!
  await page.getByRole('button', { name: '运行热点实验', exact: true }).click()
  await expect(page.getByTestId('hot-feedback')).toContainText('操作完成，继续用证据解释')
  await expect(page.getByTestId('hot-backend-count')).toHaveText(result.totals.backendReads.toLocaleString())
  await page.getByRole('button', { name: `用 ${hottest.key} 作答`, exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox', { name: '最热门的 key', exact: true })).toHaveValue(hottest.key)
  await page.getByRole('textbox', { name: '热门 key 读取次数', exact: true }).fill(String(hottest.requests))
  await page.getByRole('combobox', { name: '热门 key 的 owner', exact: true }).selectOption(hottest.owner)
  await page.getByRole('textbox', { name: '本次后端读取次数', exact: true }).fill(String(result.totals.backendReads))
  await page.getByRole('combobox', { name: '热点结果解释', exact: true }).selectOption(stage === 'cache' ? 'cache-boundary' : 'single-owner')
  await page.getByRole('combobox', { name: '热点应用背景', exact: true }).selectOption('video')
  await page.getByRole('combobox', { name: '热点案例关联', exact: true }).selectOption('read-hotspot')
  await page.getByRole('textbox', { name: '热点复盘', exact: true }).fill('需要区分键分布、请求集中度与实际后端读取。')
  await expect(page.getByTestId('hot-feedback')).toContainText('作答有未提交的修改')
  await page.getByRole('button', { name: '检查热点解释并记录', exact: true }).click()
  await expect(page.getByTestId('hot-feedback')).toContainText('本步骤通过')
  await expect(page.getByTestId('hot-save-status')).toHaveText('已保存到此浏览器')
}

test('completes the three evidence steps and restores immutable attempts, answers and undo state', async ({ page }) => {
  test.setTimeout(120000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await open(page)
  await expect(page.getByRole('button', { name: '运行热点实验', exact: true })).toBeDisabled()
  await solve(page, 'hotspot')
  await expect(page.getByTestId('hot-comparison')).toContainText('负载变化')
  await expect(page.getByTestId('hot-hit-rate')).toHaveText('不适用')
  await page.getByRole('button', { name: '虚拟节点的边界', exact: true }).click()
  await expect(page.getByTestId('hot-feedback')).toContainText('有未运行的修改')
  await solve(page, 'shards')
  await expect(page.getByTestId('hot-comparison')).toContainText('分配策略对照')
  await page.getByRole('button', { name: '缓存对照', exact: true }).click()
  await solve(page, 'cache')
  await expect(page.getByTestId('hot-comparison')).toContainText('缓存策略对照')
  await expect(page.getByLabel('热点学习进度')).toContainText('热点与缓存挑战已完成')
  const requests = page.getByRole('table', { name: '逐请求证据表', exact: true })
  await expect(requests.locator('tbody tr').first()).toContainText('未命中')
  await requests.locator('tbody button').first().click()
  await expect(page.getByText('填充：是，同一时刻成功填充', { exact: false })).toBeVisible()
  await page.getByText('查看这一请求的采样值', { exact: true }).click()
  await expect(page.getByText(/gate=\d+ \/ 2³²/)).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('hot-feedback')).toContainText('本步骤通过')
  await expect(page.getByRole('textbox', { name: '热点复盘', exact: true })).toHaveValue('需要区分键分布、请求集中度与实际后端读取。')
  await expect(page.getByTestId('hot-history').locator('details')).toHaveCount(6)
  await expect(page.getByRole('button', { name: '撤销', exact: true })).toBeDisabled()
  await page.getByRole('combobox', { name: '缓存 TTL', exact: true }).selectOption('100')
  await expect(page.getByTestId('hot-feedback')).toContainText('有未运行的修改')
  await expect(page.getByTestId('hot-feedback')).not.toContainText('本步骤通过')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByTestId('hot-feedback')).toContainText('本步骤通过')
  await page.getByRole('button', { name: '重置实验', exact: true }).click()
  await expect(page.getByTestId('hot-history').locator('details')).toHaveCount(6)
  await expect(page.getByTestId('hot-feedback')).toContainText('有未运行的修改')
  expect(errors).toEqual([])
})

test('compares a uniform counterexample and handles the largest input on a narrow screen', async ({ page }) => {
  test.setTimeout(120000)
  await open(page)
  await page.getByRole('button', { name: '自由探索', exact: true }).click()
  await page.getByRole('button', { name: '试试均匀大工作集反例', exact: true }).click()
  await page.getByRole('button', { name: '运行热点实验', exact: true }).click()
  await expect(page.getByTestId('hot-hit-rate')).toContainText('%')
  expect(parseFloat(await page.getByTestId('hot-hit-rate').innerText())).toBeLessThan(5)
  await page.getByRole('button', { name: '固定热点实验基线', exact: true }).click()
  await page.getByText('新的数据集或负载 seed', { exact: true }).click()
  await expect(page.getByRole('combobox', { name: '热点 key 数量', exact: true })).toHaveValue('4096')
  await page.getByRole('textbox', { name: '读取负载 seed', exact: true }).fill('max-hot-test')
  await page.getByRole('combobox', { name: '热点请求次数', exact: true }).selectOption('20000')
  await page.getByRole('button', { name: '生成新的热点实验数据', exact: true }).click()
  await page.getByRole('combobox', { name: '热点每节点 token 数', exact: true }).selectOption('128')
  for (let i = 0; i < 8; i++) await page.getByRole('button', { name: '添加热点节点', exact: true }).click()
  await expect(page.getByRole('button', { name: '添加热点节点', exact: true })).toBeDisabled()
  await page.getByRole('combobox', { name: '缓存条目容量', exact: true }).selectOption('256')
  const started = Date.now()
  await page.getByRole('button', { name: '运行热点实验', exact: true }).click()
  await expect(page.getByTestId('hot-save-status')).toHaveText('已保存到此浏览器')
  expect(Date.now() - started).toBeLessThan(5000)
  await expect(page.getByTestId('hot-comparison')).toContainText('实验条件不同')
  await expect(page.getByText('4096 keys · 第 1 / 274 页', { exact: true })).toBeVisible()
  await expect(page.getByText('20000 次读取 · 第 1 / 1334 页', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '请求结果筛选', exact: true }).selectOption('hit')
  await expect(page.getByRole('table', { name: '逐请求证据表', exact: true }).locator('tbody tr').first()).toContainText('命中')
  await page.getByRole('textbox', { name: '请求 key 筛选', exact: true }).fill('unknown-key')
  await expect(page.getByText('这个筛选条件下没有请求。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('combobox', { name: '热点每节点 token 数', exact: true })).toHaveValue('128')
  await expect(page.getByTestId('hot-save-status')).toHaveText('已保存到此浏览器')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('region', { name: '热点与缓存运行证据', exact: true }).scrollIntoViewIfNeeded()
  expect(await page.locator('main').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/hot-key-mobile.png' })
})

test('isolates hashing records and recovers from failed Hot Key saves', async ({ page }) => {
  test.setTimeout(90000)
  await page.addInitScript(() => {
    const original = IDBDatabase.prototype.transaction
    const flags = { fail: false }
    IDBDatabase.prototype.transaction = function (...args: Parameters<typeof original>) {
      if (flags.fail && this.name === 'system-design-algorithm-labs' && args[1] === 'readwrite') throw new DOMException('test quota', 'QuotaExceededError')
      return original.apply(this, args)
    }
    Object.assign(window, { hotStorageFlags: flags })
  })
  await page.goto('/practice/consistent-hashing')
  await page.getByRole('combobox', { name: '你的预测', exact: true }).selectOption('uncertain')
  await page.getByRole('button', { name: '+ 新增 node-e', exact: true }).click()
  await page.getByRole('button', { name: '运行并记录', exact: true }).click()
  await expect(page.getByTestId('algorithm-save-status')).toHaveText('已保存到此浏览器')
  await open(page)
  await page.getByRole('button', { name: '自由探索', exact: true }).click()
  await page.evaluate(() => { (window as unknown as { hotStorageFlags: { fail: boolean } }).hotStorageFlags.fail = true })
  await page.getByRole('button', { name: '运行热点实验', exact: true }).click()
  await expect(page.getByTestId('hot-save-status')).toContainText('未保存')
  await expect(page.getByTestId('hot-history').locator('details')).toHaveCount(1)
  await page.evaluate(() => { (window as unknown as { hotStorageFlags: { fail: boolean } }).hotStorageFlags.fail = false })
  await page.getByRole('button', { name: '重试保存热点实验', exact: true }).click()
  await expect(page.getByTestId('hot-save-status')).toHaveText('已保存到此浏览器')
  await page.getByRole('link', { name: '一致性哈希', exact: true }).click()
  await expect(page.getByTestId('algorithm-history').locator('details')).toHaveCount(1)
  await expect(page.getByTestId('algorithm-feedback')).toContainText('操作完成，继续用证据解释')
  await open(page)
  await expect(page.getByTestId('hot-history').locator('details')).toHaveCount(1)
  await expect(page.getByTestId('hot-feedback')).toContainText('运行证据已记录')
})
