import { expect, test, type Page } from '@playwright/test'

test.use({ actionTimeout: 15000 })
const click = (page: Page, name: string) => page.getByRole('button', { name, exact: true }).click()
async function open(page: Page, id = 'ack-checkpoint') {
  await page.goto(`/practice/${id}#message-state`)
  await expect(page.getByTestId('message-save-status')).toHaveText('当前操作已保存')
}
async function answer(page: Page, effects: string, checkpoints: string, copies: string) {
  await page.getByRole('combobox', { name: '消息实验预测', exact: true }).selectOption('unknown')
  await page.getByRole('textbox', { name: '消息效果次数作答', exact: true }).fill(effects)
  await page.getByRole('textbox', { name: '消息 Checkpoint 作答', exact: true }).fill(checkpoints)
  await page.getByRole('textbox', { name: '消息确认副本作答', exact: true }).fill(copies)
  await page.getByRole('combobox', { name: '消息边界解释', exact: true }).selectOption('separate-boundaries')
  await click(page, '核对并保存消息结果')
  await expect(page.getByTestId('message-save-status')).toHaveText('当前操作已保存')
}
test('manual early ACK loses work, while atomic checkpoint survives crash and lost ACK', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await open(page)
  await click(page, '生产并确认一条消息')
  await click(page, '递送 delivery-1')
  await expect(page.getByTestId('message-effects')).toHaveText('0')
  await click(page, '递送 ack-1')
  await click(page, 'Worker 崩溃')
  await click(page, '重启 Worker')
  await expect(page.getByTestId('message-acked')).toHaveText('1 / 1')
  await answer(page, '0', '0', '1')
  await expect(page.getByTestId('message-feedback')).toContainText('仍有任务没有业务效果')
  await expect(page.getByTestId('message-feedback')).not.toContainText('本关消息验证通过')
  await page.getByRole('combobox', { name: '消费者处理策略', exact: true }).selectOption('atomic')
  await click(page, '消费 ACK 丢失')
  await click(page, '生产并确认一条消息')
  await click(page, '递送 delivery-1')
  await click(page, '执行效果 delivery-1')
  await expect(page.getByTestId('message-effects')).toHaveText('1')
  await expect(page.getByTestId('message-checkpoints')).toHaveText('1')
  await click(page, '丢弃 ack-1')
  await click(page, 'Worker 崩溃')
  await page.getByRole('button', { name: /^推进下一次到期/ }).click()
  await expect(page.getByTestId('delivery-2')).toBeVisible()
  await click(page, '重启 Worker')
  await click(page, '递送 delivery-2')
  await click(page, '执行效果 delivery-2')
  await click(page, '递送 ack-2')
  await expect(page.getByTestId('message-effects')).toHaveText('1')
  await expect(page.getByRole('table', { name: '完整消息事件表', exact: true })).toContainText('跳过重复效果')
  await answer(page, '1', '1', '1')
  await expect(page.getByTestId('message-feedback')).toContainText('本关消息验证通过')
  await page.reload()
  await expect(page.getByTestId('message-effects')).toHaveText('1')
  await expect(page.getByTestId('message-feedback')).toContainText('本关消息验证通过')
  expect(errors).toEqual([])
})
test('Outbox recovers a commit gap and exposes duplicate publishing and consumer commit gaps', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/transactional-outbox')
  await page.locator('#labs a[href="/practice/transactional-outbox"]').click()
  await click(page, '只提交业务任务')
  await click(page, '生产者崩溃')
  await click(page, '重启生产者')
  await expect(page.getByRole('button', { name: '发布一个 Outbox 待办', exact: true })).toBeDisabled()
  await answer(page, '0', '0', '0')
  await expect(page.getByTestId('message-feedback')).toContainText('缺少业务事务中的发送意图')
  await page.getByRole('combobox', { name: '生产者提交方式', exact: true }).selectOption('outbox')
  await click(page, '只提交业务任务')
  await expect(page.getByRole('table', { name: 'Outbox 记录表', exact: true })).toContainText('等待发布或发送标记')
  await click(page, '生产者崩溃'); await click(page, '重启生产者')
  await click(page, '发布一个 Outbox 待办')
  await click(page, '接纳 publication-1')
  await click(page, '递送发布确认 publication-1')
  await click(page, '标记已发送 publication-1')
  await click(page, '递送 delivery-1'); await click(page, '执行效果 delivery-1'); await click(page, '递送 ack-1')
  await answer(page, '1', '1', '1')
  await expect(page.getByTestId('message-feedback')).toContainText('本关消息验证通过')
  await click(page, '发布后、标记前崩溃')
  await click(page, '运行完整消息故障示例')
  await expect(page.getByTestId('message-effects')).toHaveText('1')
  await expect(page.getByTestId('message-acked')).toHaveText('2 / 2')
  await answer(page, '1', '1', '2')
  await click(page, '消费效果后崩溃')
  await page.getByRole('combobox', { name: '消费者处理策略', exact: true }).selectOption('split')
  await click(page, '运行完整消息故障示例')
  await expect(page.getByTestId('message-effects')).toHaveText('2')
  await answer(page, '2', '1', '1')
  await expect(page.getByTestId('message-feedback')).toContainText('发现重复业务效果')
  await page.getByRole('combobox', { name: '消费者处理策略', exact: true }).selectOption('atomic')
  await click(page, '运行完整消息故障示例'); await answer(page, '1', '1', '1')
  await expect(page.getByLabel('消息实验学习进度')).toContainText('3 / 3')
})
test('handles out-of-order completion, stale receipts, dead letters and manual redrive', async ({ page }) => {
  test.setTimeout(90000)
  await open(page)
  await click(page, '自由实验')
  await page.getByRole('combobox', { name: '消费者处理策略', exact: true }).selectOption('atomic')
  await page.getByRole('combobox', { name: '同时在途额度', exact: true }).selectOption('2')
  await click(page, '生产并确认一条消息'); await click(page, '生产并确认一条消息')
  await click(page, '生产者崩溃')
  await click(page, '递送 delivery-2'); await click(page, '执行效果 delivery-2')
  await expect(page.getByRole('heading', { name: 'Checkpoint · 连续完成位置 0', exact: true })).toBeVisible()
  await click(page, '递送 ack-1')
  await click(page, '递送 delivery-1'); await click(page, '执行效果 delivery-1'); await click(page, '递送 ack-2')
  await expect(page.getByRole('heading', { name: 'Checkpoint · 连续完成位置 2', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '同时在途额度', exact: true }).selectOption('1')
  await click(page, '生产并确认一条消息'); await click(page, '递送 delivery-1'); await click(page, '执行效果 delivery-1')
  await page.getByRole('button', { name: /^推进下一次到期/ }).click()
  await click(page, '递送 ack-1')
  await expect(page.getByRole('table', { name: '完整消息事件表', exact: true })).toContainText('拒绝旧 ACK')
  await expect(page.getByRole('table', { name: '队列副本表', exact: true })).toContainText('delivery-2')
  await page.getByRole('combobox', { name: '消息投递预算', exact: true }).selectOption('2')
  await click(page, '生产并确认一条消息')
  for (const id of [1, 2]) { await click(page, `递送 delivery-${id}`); await click(page, `处理失败 delivery-${id}`); await page.getByRole('button', { name: /^推进下一次到期/ }).click() }
  await expect(page.getByRole('table', { name: '队列副本表', exact: true })).toContainText('死信待修复')
  await click(page, '修复后重放 copy-1')
  await click(page, '递送 delivery-3'); await click(page, '执行效果 delivery-3'); await click(page, '递送 ack-1')
  await expect(page.getByTestId('message-effects')).toHaveText('1')
  await expect(page.getByTestId('message-acked')).toHaveText('1 / 1')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.locator('main').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/message-flow-mobile.png' })
})
test('persists partial packets and independent lesson records, with save failure recovery', async ({ page }) => {
  test.setTimeout(60000)
  await page.addInitScript(() => {
    const original = IDBDatabase.prototype.transaction
    const flags = { fail: false }
    IDBDatabase.prototype.transaction = function (...args: Parameters<typeof original>) {
      if (flags.fail && this.name === 'system-design-algorithm-labs' && args[1] === 'readwrite') throw new DOMException('test quota', 'QuotaExceededError')
      return original.apply(this, args)
    }
    Object.assign(window, { messageStorageFlags: flags })
  })
  await open(page)
  await click(page, '只提交业务任务'); await click(page, '发送事件 event-1')
  await expect(page.getByTestId('message-save-status')).toHaveText('当前操作已保存')
  await page.reload()
  await expect(page.getByRole('button', { name: '接纳 publication-1', exact: true })).toBeEnabled()
  await click(page, '清空消息实验')
  await page.getByRole('combobox', { name: '消费者处理策略', exact: true }).selectOption('atomic')
  await page.evaluate(() => { (window as unknown as { messageStorageFlags: { fail: boolean } }).messageStorageFlags.fail = true })
  await click(page, '运行完整消息故障示例'); await click(page, '核对并保存消息结果')
  await expect(page.getByTestId('message-save-status')).toContainText('未保存')
  await expect(page.getByTestId('message-history').locator('details')).toHaveCount(1)
  await page.evaluate(() => { (window as unknown as { messageStorageFlags: { fail: boolean } }).messageStorageFlags.fail = false })
  await click(page, '重试保存消息实验')
  await expect(page.getByTestId('message-save-status')).toHaveText('当前操作已保存')
  await open(page, 'transactional-outbox')
  await expect(page.getByTestId('message-history').locator('details')).toHaveCount(0)
  await open(page)
  await expect(page.getByTestId('message-history').locator('details')).toHaveCount(1)
  await expect(page.getByTestId('message-effects')).toHaveText('1')
  await click(page, '清空消息实验')
  await page.getByRole('button', { name: '只提交业务任务', exact: true }).focus(); await page.keyboard.press('Enter')
  await expect(page.getByTestId('message-tasks')).toHaveText('1')
})
