import { expect, test, type Page } from '@playwright/test'
import { defaultConfig } from '../src/features/practice/retry-idempotency/model'
import { scenarioCommands, type Scenario } from '../src/features/practice/retry-idempotency/lesson'

test.use({ actionTimeout: 15000 })
async function open(page: Page) {
  await page.goto('/learn/idempotency')
  await page.locator('#labs a[href="/practice/retry-idempotency"]').click()
  await expect(page.getByRole('heading', { name: '任务创建了，响应却丢了', level: 1, exact: true })).toBeVisible()
  await expect(page.getByTestId('retry-save-status')).toHaveText('当前操作已保存')
}
const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
async function loseResponseAndRetry(page: Page) {
  await button(page, '提交请求').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('0 个任务')
  await button(page, '递送 request-1').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('0 个任务')
  await button(page, '处理 request-1').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await expect(page.getByTestId('retry-known-count')).toHaveText('0 个任务')
  await button(page, '丢弃 response-1').click()
  await page.getByRole('button', { name: /^推进下一计时器/ }).click()
  await expect(page.getByTestId('retry-clock')).toHaveText('500 ms')
  await expect(page.getByTestId('retry-request-count')).toHaveText('1 / 3')
  await expect(page.getByRole('region', { name: '客户端状态', exact: true })).toContainText('业务结果仍未知')
  await page.getByRole('button', { name: /^推进下一计时器/ }).click()
  await expect(page.getByTestId('retry-request-count')).toHaveText('2 / 3')
  await button(page, '递送 request-2').click()
  await button(page, '处理 request-2').click()
  await button(page, '递送 response-2').click()
}
async function answer(page: Page, tasks = '1') {
  await page.getByRole('combobox', { name: '请求实验预测', exact: true }).selectOption('duplicate')
  await page.getByRole('textbox', { name: '任务创建次数作答', exact: true }).fill(tasks)
  await page.getByRole('combobox', { name: '客户端状态作答', exact: true }).selectOption('success')
  await page.getByRole('combobox', { name: '超时含义作答', exact: true }).selectOption('unknown-does-not-mean-failed')
  await button(page, '核对并保存结果').click()
  await expect(page.getByTestId('retry-save-status')).toHaveText('当前操作已保存')
}
test('manually delivers and drops actual messages, sees duplication, and fixes it with atomic idempotency', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await open(page)
  await loseResponseAndRetry(page)
  await expect(page.getByTestId('retry-task-count')).toHaveText('2 个任务')
  await expect(page.getByTestId('retry-known-count')).toHaveText('1 个任务')
  await expect(page.getByRole('table', { name: '实际任务表', exact: true }).locator('tbody tr')).toHaveCount(2)
  await answer(page, '2')
  await expect(page.getByTestId('retry-feedback')).toContainText('发现重复创建')
  await button(page, '重试 + 原子幂等').click()
  await expect(page.getByTestId('retry-feedback')).toContainText('动作或配置已改变')
  await loseResponseAndRetry(page)
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await expect(page.getByRole('table', { name: '幂等记录表', exact: true }).locator('tbody tr')).toHaveCount(1)
  await expect(page.getByRole('table', { name: '完整协议事件表', exact: true })).toContainText('幂等重放')
  await answer(page)
  await expect(page.getByTestId('retry-feedback')).toContainText('本关验证通过')
  await expect(page.getByTestId('retry-history').locator('details')).toHaveCount(2)
  await button(page, '运行三种策略对照').click()
  const comparison = page.getByRole('table', { name: '重试策略对照表', exact: true })
  await expect(comparison.locator('tbody tr').nth(0)).toContainText('结果未知')
  await expect(comparison.locator('tbody tr').nth(1)).toContainText('task-2')
  await expect(comparison.locator('tbody tr').nth(2)).toContainText('task-1')
  await page.reload()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await expect(page.getByTestId('retry-feedback')).toContainText('本关验证通过')
  expect(errors).toEqual([])
})

test('steps through new fault timings, preserves mid-experiment state and rejects stale feedback', async ({ page }) => {
  test.setTimeout(90000)
  await open(page)
  await button(page, '重试 + 原子幂等').click()
  await button(page, '运行完整故障示例').click()
  await answer(page)
  for (const [scenario, title] of [['request-lost', '请求没有到达'], ['late-request', '旧请求延迟到达']] as [Exclude<Scenario, 'manual'>, string][]) {
    await button(page, title).click()
    const count = scenarioCommands({ ...defaultConfig(), strategy: 'idempotent' }, scenario).length
    await page.getByRole('button', { name: /^下一步：/ }).click()
    await expect(page.getByTestId('retry-save-status')).toHaveText('当前操作已保存')
    await page.reload()
    await expect(button(page, '递送 request-1')).toBeVisible()
    for (let i = 1; i < count; i++) await page.getByRole('button', { name: /^下一步：/ }).click()
    await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
    await answer(page)
    await expect(page.getByTestId('retry-feedback')).toContainText('本关验证通过')
  }
  await expect(page.getByLabel('请求可靠性学习进度')).toContainText('3 / 3')
  await button(page, '清空操作重新开始').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('0 个任务')
  await expect(page.getByTestId('retry-feedback')).toContainText('动作或配置已改变')
  await button(page, '撤销').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await expect(page.getByTestId('retry-feedback')).toContainText('本关验证通过')
  await page.getByRole('region', { name: '本题相关基础知识', exact: true }).getByRole('link', { name: '幂等与重复业务效果 ↗', exact: true }).click()
  await page.locator('#labs a[href="/practice/retry-idempotency"]').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await expect(page.getByTestId('retry-history').locator('details')).toHaveCount(3)
})

test('exercises concurrent requests, expired keys, process recovery and parameter conflicts', async ({ page }) => {
  test.setTimeout(90000)
  await open(page)
  await button(page, '重试 + 原子幂等').click()
  await button(page, '自由实验').click()
  await button(page, '提交请求').click()
  await button(page, '递送 request-1').click()
  await button(page, '立即重试（同键同参数）').click()
  await button(page, '递送 request-2').click()
  await button(page, '处理 request-2').click()
  await button(page, '处理 request-1').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await button(page, '递送 response-2').click()
  await button(page, '递送 response-1').click()
  await expect(page.getByTestId('retry-known-count')).toHaveText('1 个任务')
  await button(page, '创建后丢响应').click()
  await page.getByRole('combobox', { name: '幂等记录保留期', exact: true }).selectOption('200')
  await button(page, '运行完整故障示例').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('2 个任务')
  await expect(page.getByRole('table', { name: '完整协议事件表', exact: true })).toContainText('去重到期')
  await page.getByRole('combobox', { name: '幂等记录保留期', exact: true }).selectOption('10000')
  await button(page, '提交请求').click()
  await button(page, '递送 request-1').click()
  await button(page, '处理 request-1').click()
  await button(page, '丢弃 response-1').click()
  await button(page, '服务崩溃').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await page.getByRole('button', { name: /^推进下一计时器/ }).click()
  await page.getByRole('button', { name: /^推进下一计时器/ }).click()
  await expect(button(page, '递送 request-2')).toBeDisabled()
  await button(page, '重启服务').click()
  await button(page, '递送 request-2').click()
  await button(page, '处理 request-2').click()
  await button(page, '递送 response-2').click()
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await button(page, '清空操作重新开始').click()
  await button(page, '提交请求').click()
  await button(page, '递送 request-1').click()
  await button(page, '处理 request-1').click()
  await page.getByText('边界实验：换键或改参数', { exact: true }).click()
  await page.getByRole('combobox', { name: '自定义重试格式', exact: true }).selectOption('1080p')
  await button(page, '用自定义参数重试').click()
  await button(page, '递送 request-2').click()
  await button(page, '处理 request-2').click()
  await button(page, '递送 response-2').click()
  await expect(page.getByTestId('retry-client-status')).toHaveText('收到参数冲突')
  await expect(page.getByTestId('retry-task-count')).toHaveText('1 个任务')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.locator('main').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.getByRole('region', { name: '客户端状态', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/retry-protocol-mobile.png' })
})

test('reports failed saves, retries persistence and restores executable command state', async ({ page }) => {
  await page.addInitScript(() => {
    const original = IDBDatabase.prototype.transaction
    const flags = { fail: false }
    IDBDatabase.prototype.transaction = function (...args: Parameters<typeof original>) {
      if (flags.fail && this.name === 'system-design-algorithm-labs' && args[1] === 'readwrite') throw new DOMException('test quota', 'QuotaExceededError')
      return original.apply(this, args)
    }
    Object.assign(window, { retryStorageFlags: flags })
  })
  await open(page)
  await page.evaluate(() => { (window as unknown as { retryStorageFlags: { fail: boolean } }).retryStorageFlags.fail = true })
  await button(page, '运行完整故障示例').click()
  await button(page, '核对并保存结果').click()
  await expect(page.getByTestId('retry-save-status')).toContainText('未保存')
  await expect(page.getByTestId('retry-task-count')).toHaveText('2 个任务')
  await expect(page.getByTestId('retry-history').locator('details')).toHaveCount(1)
  await page.evaluate(() => { (window as unknown as { retryStorageFlags: { fail: boolean } }).retryStorageFlags.fail = false })
  await button(page, '重试保存协议实验').click()
  await expect(page.getByTestId('retry-save-status')).toHaveText('当前操作已保存')
  await page.reload()
  await expect(page.getByTestId('retry-task-count')).toHaveText('2 个任务')
  await expect(page.getByTestId('retry-feedback')).toContainText('发现重复创建')
  await button(page, '清空操作重新开始').click()
  await button(page, '提交请求').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('request-1')).toBeVisible()
})
