import { expect, test, type Page } from '@playwright/test'
test.use({ actionTimeout: 15000 })
const click = (page: Page, name: string) => page.getByRole('button', { name, exact: true }).click()
async function open(page: Page) { await page.goto('/practice/saga-recovery#saga-state'); await expect(page.getByTestId('saga-save-status')).toHaveText('当前操作已保存') }
async function answer(page: Page, quota = '1') {
  await page.getByRole('combobox', { name: 'Saga 实验预测', exact: true }).selectOption('unknown')
  await page.getByRole('combobox', { name: 'Saga 流程结果作答', exact: true }).selectOption('compensated')
  await page.getByRole('textbox', { name: 'Saga 可用配额作答', exact: true }).fill(quota)
  await page.getByRole('textbox', { name: 'Saga 保留产物作答', exact: true }).fill('0')
  await page.getByRole('textbox', { name: 'Saga 累计转码工作作答', exact: true }).fill('1')
  await page.getByRole('combobox', { name: 'Saga 边界解释', exact: true }).selectOption('business-correction')
  await click(page, '核对并保存 Saga 结果')
  await expect(page.getByTestId('saga-save-status')).toHaveText('当前操作已保存')
}
async function finish(page: Page, id: number) { await click(page, '发送或重试当前步骤'); await click(page, `执行 call-${id}`); await click(page, `递送响应 call-${id}`); await click(page, `保存进度 call-${id}`) }
test('contrasts abandonment, duplicate refunds and safe compensating retries', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []; page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/learn/sagas'); await page.locator('#labs a[href="/practice/saga-recovery"]').click()
  await click(page, '运行完整 Saga 故障示例')
  await expect(page.getByTestId('saga-phase')).toHaveText('失败后停止')
  await expect(page.getByTestId('saga-artifacts')).toHaveText('1')
  await page.getByRole('combobox', { name: 'Saga 恢复策略', exact: true }).selectOption('saga')
  await page.getByRole('combobox', { name: 'Saga 幂等保护', exact: true }).selectOption('false')
  await click(page, '运行完整 Saga 故障示例')
  await expect(page.getByTestId('saga-phase')).toHaveText('已补偿，发布未成功')
  await expect(page.getByTestId('saga-quota')).toHaveText('2')
  await answer(page, '2')
  await expect(page.getByTestId('saga-feedback')).toContainText('流程或业务状态尚未满足目标')
  await page.getByRole('combobox', { name: 'Saga 幂等保护', exact: true }).selectOption('true')
  await click(page, '创建视频流程'); await finish(page, 1); await finish(page, 2); await click(page, '阻断发布视频'); await finish(page, 3); await finish(page, 4)
  await click(page, '发送或重试当前步骤'); await click(page, '执行 call-5'); await click(page, '丢弃响应 call-5')
  await expect(page.getByTestId('saga-quota')).toHaveText('1')
  await expect(page.getByRole('table', { name: 'Saga 进度表', exact: true }).getByRole('row').filter({ hasText: '释放配额' })).toContainText('未记录')
  await click(page, '推进一个响应超时'); await finish(page, 6)
  await expect(page.getByTestId('saga-quota')).toHaveText('1')
  await expect(page.getByTestId('call-6')).toContainText('幂等重放')
  await answer(page)
  await expect(page.getByTestId('saga-feedback')).toContainText('本关 Saga 验证通过')
  await page.reload(); await expect(page.getByTestId('saga-feedback')).toContainText('本关 Saga 验证通过')
  await expect(page.getByTestId('saga-work')).toHaveText('1')
  expect(errors).toEqual([])
})
test('restores the crash window and requires actual repair after compensation budget exhaustion', async ({ page }) => {
  test.setTimeout(90000)
  await open(page)
  await page.getByRole('combobox', { name: 'Saga 恢复策略', exact: true }).selectOption('saga')
  await click(page, '补偿后、记进度前崩溃')
  await click(page, '创建视频流程'); await finish(page, 1); await finish(page, 2); await click(page, '阻断发布视频'); await finish(page, 3)
  await click(page, '发送或重试当前步骤'); await click(page, '执行 call-4'); await click(page, '递送响应 call-4')
  await expect(page.getByTestId('saga-save-status')).toHaveText('当前操作已保存'); await page.reload()
  await expect(page.getByRole('button', { name: '保存进度 call-4', exact: true })).toBeEnabled()
  await click(page, '协调者崩溃'); await click(page, '重启协调者'); await finish(page, 5); await finish(page, 6); await answer(page)
  await expect(page.getByTestId('saga-feedback')).toContainText('本关 Saga 验证通过')
  await click(page, '补偿本身失败'); await click(page, '创建视频流程'); await finish(page, 1); await finish(page, 2); await click(page, '阻断发布视频'); await finish(page, 3); await click(page, '阻断清理产物')
  for (const id of [4, 5, 6]) await finish(page, id)
  await expect(page.getByTestId('saga-phase')).toHaveText('需要人工处理')
  await expect(page.getByRole('button', { name: '发送或重试当前步骤', exact: true })).toBeDisabled()
  await click(page, '修复清理产物')
  await expect(page.getByTestId('saga-artifacts')).toHaveText('1')
  await expect(page.getByTestId('saga-phase')).toHaveText('需要人工处理')
  await click(page, '人工核查后恢复'); await finish(page, 7); await finish(page, 8); await answer(page)
  await expect(page.getByTestId('saga-feedback')).toContainText('本关 Saga 验证通过')
  await expect(page.getByLabel('Saga 学习进度')).toContainText('2 / 3')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.locator('main').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/saga-mobile.png' })
  await page.goto('/practice/transactional-outbox'); await expect(page.getByTestId('message-history').locator('details')).toHaveCount(0)
  await open(page); await expect(page.getByTestId('saga-history').locator('details')).toHaveCount(2)
})
