'use client'

import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react'
import type { InteractionAction, InteractionDefinition, ProjectFile } from '@system-design/model'
import type { ProjectEditIssue } from '@/lib/store'
import { CheckInput, IdentityFields, NodeSelect, NumberInput, OperationReferenceSelect, SelectInput, StringListInput, TextInput } from './definition-form-controls'

type ActionKind = InteractionAction['kind']
const actionKinds: Array<{ value: ActionKind; label: string }> = [
  { value: 'api-call', label: 'API call' }, { value: 'service-call', label: 'Service call' }, { value: 'data-access', label: 'Data access' },
  { value: 'cache-access', label: 'Cache access' }, { value: 'event-publish', label: 'Publish event' }, { value: 'event-consume', label: 'Consume event' },
  { value: 'realtime', label: 'Realtime connection / broadcast' },
]
const referenceKey = (id: string, version: number) => `${id}@${version}`

const createAction = (project: ProjectFile, kind: ActionKind, index: number): InteractionAction => {
  const services = project.topology.nodes.filter((node) => node.type === 'service')
  const source = project.topology.nodes.find((node) => node.type === 'traffic') ?? services[0]
  const target = services[0]
  const cache = project.topology.nodes.find((node) => node.type === 'cache')
  const broker = project.topology.nodes.find((node) => node.type === 'queue' || node.type === 'stream' || node.type === 'topic')
  const api = project.definitions.apis[0]
  const operation = api?.operations[0]
  const operationReference = { apiId: api?.id ?? 'missing-api', apiVersion: api?.version ?? 1, operationId: operation?.id ?? 'missing-operation' }
  const base = { id: `action-${index + 1}`, name: `Action ${index + 1}`, dependsOn: [] as string[] }
  if (kind === 'api-call') return { ...base, kind, sourceNodeId: source?.id ?? 'missing-source', targetNodeId: target?.id ?? 'missing-service', operation: operationReference }
  if (kind === 'service-call') return { ...base, kind, sourceNodeId: source?.id ?? 'missing-source', targetNodeId: target?.id ?? 'missing-service', operation: operationReference }
  if (kind === 'data-access') {
    const model = project.definitions.dataModels[0]
    const objectId = model?.kind === 'relational' ? model.tables[0]?.id : model?.kind === 'document' ? model.collections[0]?.id : model?.namespaces[0]?.id
    const owner = project.topology.nodes.find((node) => node.id === model?.ownerNodeId)
    return { ...base, kind, nodeId: model?.ownerNodeId ?? 'missing-data-node', model: { modelId: model?.id ?? 'missing-model', modelVersion: model?.version ?? 1 }, objectId: objectId ?? 'missing-object', operation: owner?.type === 'search-index' ? 'scan' : 'point-read', estimatedRows: 1 }
  }
  if (kind === 'cache-access') { const key = project.definitions.cacheKeys[0]; return { ...base, kind, nodeId: cache?.id ?? 'missing-cache', operation: 'get', key: { cacheKeyId: key?.id ?? 'missing-key', cacheKeyVersion: key?.version ?? 1 } } }
  if (kind === 'realtime') { const gateway = project.topology.nodes.find((node) => node.type === 'realtime-gateway'); const configuredBytes = gateway?.type === 'realtime-gateway' ? gateway.config.defaultMessageBytes : undefined; const messageBytes = typeof configuredBytes === 'number' ? configuredBytes : 1_024; return { ...base, kind, nodeId: gateway?.id ?? 'missing-realtime-gateway', operation: 'broadcast', connectionPattern: 'connection:{request}', channelPattern: 'channel:{key}', messageBytes } }
  const event = project.definitions.events[0]
  if (kind === 'event-publish') return { ...base, kind, producerNodeId: event?.producerNodeId ?? target?.id ?? 'missing-producer', brokerNodeId: broker?.id ?? 'missing-broker', event: { eventId: event?.id ?? 'missing-event', eventVersion: event?.version ?? 1 } }
  return { ...base, kind, consumerNodeId: event?.consumerNodeIds[0] ?? target?.id ?? 'missing-consumer', brokerNodeId: broker?.id ?? 'missing-broker', event: { eventId: event?.id ?? 'missing-event', eventVersion: event?.version ?? 1 } }
}

function CommonActionFields({ action, index, priorIds, issues, onChange }: { action: InteractionAction; index: number; priorIds: string[]; issues: ProjectEditIssue[]; onChange: (action: InteractionAction) => void }) {
  const condition = action.condition
  return <><div className="definition-field-grid"><TextInput label="Action ID" value={action.id} issues={issues} path={['actions', index, 'id']} onChange={(id) => onChange({ ...action, id })} /><TextInput label="Name" value={action.name ?? ''} onChange={(name) => onChange({ ...action, name: name || undefined })} /><StringListInput label="Depends on" value={action.dependsOn} placeholder={priorIds.join(', ')} issues={issues} path={['actions', index, 'dependsOn']} onChange={(dependsOn) => onChange({ ...action, dependsOn })} /></div><div className="definition-subsection"><div className="definition-subsection__heading"><strong>Conditional execution</strong><CheckInput label="Conditional" checked={Boolean(condition)} onChange={(checked) => onChange({ ...action, condition: checked && priorIds[0] ? { actionId: priorIds[0], outcome: 'success' } : undefined })} /></div>{condition ? <div className="definition-field-grid"><SelectInput label="Prior action" value={condition.actionId} options={priorIds.length ? priorIds.map((id) => ({ value: id, label: id })) : [{ value: condition.actionId, label: `${condition.actionId} · unavailable` }]} issues={issues} path={['actions', index, 'condition', 'actionId']} onChange={(actionId) => onChange({ ...action, condition: { ...condition, actionId } })} /><SelectInput label="Outcome" value={condition.outcome} options={[{ value: 'success', label: 'Success' }, { value: 'failure', label: 'Failure' }, { value: 'cache-hit', label: 'Cache hit' }, { value: 'cache-miss', label: 'Cache miss' }]} onChange={(outcome) => onChange({ ...action, condition: { ...condition, outcome } })} /></div> : null}</div>{priorIds.length > 0 ? <p className="definition-hint">Available earlier actions: {priorIds.join(', ')}</p> : null}</>
}

function DataAccessFields({ project, action, index, issues, onChange }: { project: ProjectFile; action: Extract<InteractionAction, { kind: 'data-access' }>; index: number; issues: ProjectEditIssue[]; onChange: (action: InteractionAction) => void }) {
  const models = project.definitions.dataModels
  const currentModelKey = referenceKey(action.model.modelId, action.model.modelVersion)
  const model = models.find((candidate) => referenceKey(candidate.id, candidate.version) === currentModelKey)
  const owner = project.topology.nodes.find((node) => node.id === action.nodeId)
  const objectOptions = model?.kind === 'relational' ? model.tables.map((object) => ({ value: object.id, label: object.name })) : model?.kind === 'document' ? model.collections.map((object) => ({ value: object.id, label: object.name })) : model?.kind === 'key-value' ? model.namespaces.map((object) => ({ value: object.id, label: object.name })) : [{ value: action.objectId, label: `${action.objectId} · unresolved` }]
  const indexOptions = model?.kind === 'relational'
    ? (() => { const table = model.tables.find((object) => object.id === action.objectId); return table ? [table.primaryKey, ...table.uniqueKeys, ...table.indexes].map((candidate) => ({ value: candidate.id, label: candidate.name })) : [] })()
    : model?.kind === 'document'
      ? (model.collections.find((object) => object.id === action.objectId)?.secondaryIndexes ?? []).map((candidate) => ({ value: candidate.id, label: candidate.name }))
      : []
  return <div className="definition-field-grid"><NodeSelect project={project} type={['database', 'search-index']} label="Data node" value={action.nodeId} issues={issues} path={['actions', index, 'nodeId']} onChange={(nodeId) => onChange({ ...action, nodeId })} /><SelectInput label="Data model" value={currentModelKey} options={models.map((candidate) => ({ value: referenceKey(candidate.id, candidate.version), label: `${candidate.name} · ${candidate.kind}` }))} issues={issues} path={['actions', index, 'model']} onChange={(key) => { const divider = key.lastIndexOf('@'); const next = models.find((candidate) => referenceKey(candidate.id, candidate.version) === key)!; const objectId = next.kind === 'relational' ? next.tables[0]!.id : next.kind === 'document' ? next.collections[0]!.id : next.namespaces[0]!.id; onChange({ ...action, nodeId: next.ownerNodeId, model: { modelId: key.slice(0, divider), modelVersion: Number(key.slice(divider + 1)) }, objectId, operation: project.topology.nodes.find((node) => node.id === next.ownerNodeId)?.type === 'search-index' ? 'scan' : action.operation, indexId: undefined }) }} /><SelectInput label="Data object" value={action.objectId} options={objectOptions} issues={issues} path={['actions', index, 'objectId']} onChange={(objectId) => onChange({ ...action, objectId, indexId: undefined })} /><SelectInput label="Operation" value={action.operation} options={(owner?.type === 'search-index' ? ['index-read', 'range-read', 'scan', 'insert', 'update', 'delete'] : ['point-read', 'index-read', 'range-read', 'scan', 'insert', 'update', 'delete']).map((value) => ({ value: value as typeof action.operation, label: value }))} onChange={(operation) => onChange({ ...action, operation, ...((operation === 'index-read' || operation === 'range-read') && indexOptions[0] ? { indexId: indexOptions[0].value } : { indexId: undefined }) })} />{action.operation === 'index-read' || action.operation === 'range-read' ? <SelectInput label="Index" value={action.indexId ?? ''} options={indexOptions.length ? indexOptions : [{ value: '', label: 'No index available' }]} issues={issues} path={['actions', index, 'indexId']} onChange={(indexId) => onChange({ ...action, indexId })} /> : null}<NumberInput label="Estimated rows" value={action.estimatedRows} optional min={1} onChange={(estimatedRows) => onChange({ ...action, estimatedRows })} /></div>
}

function ActionFields({ project, action, index, issues, onChange }: { project: ProjectFile; action: InteractionAction; index: number; issues: ProjectEditIssue[]; onChange: (action: InteractionAction) => void }) {
  if (action.kind === 'api-call' || action.kind === 'service-call') return <div className="definition-field-grid"><NodeSelect project={project} label="Source node" value={action.sourceNodeId} onChange={(sourceNodeId) => onChange({ ...action, sourceNodeId })} /><NodeSelect project={project} type="service" label="Target service" value={action.targetNodeId} issues={issues} path={['actions', index, 'targetNodeId']} onChange={(targetNodeId) => onChange({ ...action, targetNodeId })} />{action.kind === 'api-call' || action.operation ? <OperationReferenceSelect project={project} label="Operation" value={action.operation!} issues={issues} path={['actions', index, 'operation']} onChange={(operation) => onChange({ ...action, operation })} /> : null}</div>
  if (action.kind === 'data-access') return <DataAccessFields project={project} action={action} index={index} issues={issues} onChange={onChange} />
  if (action.kind === 'cache-access') {
    const current = referenceKey(action.key.cacheKeyId, action.key.cacheKeyVersion)
    return <div className="definition-field-grid"><NodeSelect project={project} type="cache" label="Cache node" value={action.nodeId} onChange={(nodeId) => onChange({ ...action, nodeId })} /><SelectInput label="Operation" value={action.operation} options={['get', 'put', 'delete'].map((value) => ({ value: value as typeof action.operation, label: value }))} onChange={(operation) => onChange({ ...action, operation })} /><SelectInput label="Cache-key contract" value={current} options={project.definitions.cacheKeys.map((key) => ({ value: referenceKey(key.id, key.version), label: key.name }))} issues={issues} path={['actions', index, 'key']} onChange={(key) => { const divider = key.lastIndexOf('@'); onChange({ ...action, key: { cacheKeyId: key.slice(0, divider), cacheKeyVersion: Number(key.slice(divider + 1)) } }) }} /></div>
  }
  if (action.kind === 'realtime') { const gateway = project.topology.nodes.find((node) => node.id === action.nodeId); const configuredBytes = gateway?.type === 'realtime-gateway' ? gateway.config.defaultMessageBytes : undefined; const defaultMessageBytes = typeof configuredBytes === 'number' ? configuredBytes : 1_024; return <div className="definition-field-grid"><NodeSelect project={project} type="realtime-gateway" label="Realtime gateway" value={action.nodeId} issues={issues} path={['actions', index, 'nodeId']} onChange={(nodeId) => onChange({ ...action, nodeId })} /><SelectInput label="Realtime operation" value={action.operation} options={[{ value: 'connect', label: 'Connect + join channel' }, { value: 'broadcast', label: 'Broadcast to channel' }, { value: 'disconnect', label: 'Disconnect' }]} onChange={(operation) => onChange({ ...action, operation, ...(operation === 'broadcast' ? { messageBytes: action.messageBytes ?? defaultMessageBytes } : { messageBytes: undefined }) })} /><TextInput label="Connection pattern" value={action.connectionPattern} issues={issues} path={['actions', index, 'connectionPattern']} onChange={(connectionPattern) => onChange({ ...action, connectionPattern })} /><TextInput label="Channel pattern" value={action.channelPattern} issues={issues} path={['actions', index, 'channelPattern']} onChange={(channelPattern) => onChange({ ...action, channelPattern })} />{action.operation === 'broadcast' ? <NumberInput label="Message bytes" value={action.messageBytes} min={1} onChange={(messageBytes) => { if (messageBytes !== undefined) onChange({ ...action, messageBytes }) }} /> : null}<p className="definition-hint"><code>{'{request}'}</code> selects a connection and <code>{'{key}'}</code> selects a channel, so the same action can model rooms, documents, games, or live feeds.</p></div> }
  const current = referenceKey(action.event.eventId, action.event.eventVersion)
  const event = project.definitions.events.find((candidate) => referenceKey(candidate.id, candidate.version) === current)
  const brokerTypes = ['queue', 'stream', 'topic']
  return <div className="definition-field-grid"><SelectInput label="Event contract" value={current} options={project.definitions.events.map((candidate) => ({ value: referenceKey(candidate.id, candidate.version), label: candidate.name }))} issues={issues} path={['actions', index, 'event']} onChange={(key) => { const divider = key.lastIndexOf('@'); onChange({ ...action, event: { eventId: key.slice(0, divider), eventVersion: Number(key.slice(divider + 1)) } }) }} /><NodeSelect project={project} type={brokerTypes} label="Broker node" value={action.brokerNodeId} issues={issues} path={['actions', index, 'brokerNodeId']} onChange={(brokerNodeId) => onChange({ ...action, brokerNodeId })} />{action.kind === 'event-publish' ? <NodeSelect project={project} type="service" label="Producer" value={action.producerNodeId} issues={issues} path={['actions', index, 'producerNodeId']} onChange={(producerNodeId) => onChange({ ...action, producerNodeId })} /> : <NodeSelect project={project} type="service" label="Consumer" value={action.consumerNodeId} issues={issues} path={['actions', index, 'consumerNodeId']} onChange={(consumerNodeId) => onChange({ ...action, consumerNodeId })} />}{event ? <p className="definition-hint">Contract producer: {event.producerNodeId} · consumers: {event.consumerNodeIds.join(', ') || 'none'}</p> : null}</div>
}

export function InteractionEditor({ project, value, issues, onChange }: { project: ProjectFile; value: InteractionDefinition; issues: ProjectEditIssue[]; onChange: (value: InteractionDefinition, issues?: ProjectEditIssue[]) => void }) {
  const replace = (index: number, action: InteractionAction) => onChange({ ...value, actions: value.actions.map((candidate, candidateIndex) => candidateIndex === index ? action : candidate) })
  const move = (index: number, direction: -1 | 1) => { const actions = [...value.actions]; const target = index + direction; if (target < 0 || target >= actions.length) return; [actions[index], actions[target]] = [actions[target]!, actions[index]!]; onChange({ ...value, actions }) }
  return <div className="definition-form"><IdentityFields value={value} issues={issues} onChange={onChange} /><OperationReferenceSelect project={project} label="Entry operation" value={value.entryOperation} issues={issues} path={['entryOperation']} onChange={(entryOperation) => onChange({ ...value, entryOperation })} /><div className="definition-array-heading"><div><strong>Interaction actions</strong><span>Typed topology overlay; order defines valid dependency direction</span></div><div className="definition-action-add">{actionKinds.map((kind) => <button type="button" key={kind.value} onClick={() => onChange({ ...value, actions: [...value.actions, createAction(project, kind.value, value.actions.length)] })}><Plus size={12} /> {kind.label}</button>)}</div></div>{value.actions.map((action, index) => <details className="definition-card" open key={`${action.id}-${index}`}><summary><span><strong>{action.name || action.id}</strong><small>{action.kind} · {action.dependsOn.length ? `after ${action.dependsOn.join(', ')}` : 'entry'}</small></span><div><button type="button" aria-label={`Move ${action.id} earlier`} disabled={index === 0} onClick={(event) => { event.preventDefault(); move(index, -1) }}><ArrowUp size={13} /></button><button type="button" aria-label={`Move ${action.id} later`} disabled={index === value.actions.length - 1} onClick={(event) => { event.preventDefault(); move(index, 1) }}><ArrowDown size={13} /></button><button type="button" aria-label={`Delete ${action.id}`} disabled={value.actions.length === 1} onClick={(event) => { event.preventDefault(); onChange({ ...value, actions: value.actions.filter((_, candidate) => candidate !== index) }) }}><Trash2 size={13} /></button></div></summary><div className="definition-card__body"><div className="definition-field-grid"><SelectInput label="Action type" value={action.kind} options={actionKinds} onChange={(kind) => replace(index, createAction(project, kind, index))} /></div><CommonActionFields action={action} index={index} priorIds={value.actions.slice(0, index).map((candidate) => candidate.id)} issues={issues} onChange={(replacement) => replace(index, replacement)} /><ActionFields project={project} action={action} index={index} issues={issues} onChange={(replacement) => replace(index, replacement)} /></div></details>)}</div>
}
