import { useState } from 'react'
import { EventTimeline } from '../protocol/event-timeline'
import { MAX_TIME, nextTimer, type Command, type Config, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'

export const processLabels = { running: '运行中', paused: '已暂停', crashed: '已崩溃' }
export const observationLabels = { unknown: '尚未收到心跳', healthy: '近期收到心跳', suspected: '怀疑失联' }
const heartbeatLabels = { network: '在途', delivered: '已递送', dropped: '已丢弃', ignored: '旧心跳被忽略' }
const writeLabels = { network: '在途', accepted: '已接受', rejected: '已拒绝', dropped: '已丢弃' }
const actors = [{ id: 'A', label: 'Worker A' }, { id: 'B', label: 'Worker B' }, { id: 'observer', label: '观察者' }, { id: 'authority', label: '租约授予者' }, { id: 'resource', label: '受保护资源' }]
const labels = { 'heartbeat-sent': '发送心跳', 'heartbeat-partitioned': '分区丢失心跳', 'heartbeat-dropped': '丢弃心跳', 'write-prepared': '发送写入', 'write-dropped': '丢弃写入', renewed: '续租', reconnect: '链路恢复', clock: '推进时间', 'local-expired': '本地租约过期', budget: '样本预算耗尽', suspect: '超时怀疑', 'heartbeat-received': '收到心跳', 'heartbeat-stale': '忽略旧心跳', 'lease-granted': '授予租约', 'lease-denied': '拒绝申请', 'lease-expired': '租约到期', 'write-rejected': '拒绝旧写入', 'write-accepted': '接受写入', 'stale-write-accepted': '旧写入覆盖', paused: '暂停', resumed: '恢复', crashed: '崩溃', restarted: '重启', partition: '网络分区' }

export function CoordinationLiveView({ state: s, config, act, disabled, showLease }: { state: State; config: Config; act: (command: Command) => void; disabled: boolean; showLease: boolean }) {
  const [values, setValues] = useState({ A: 'A-result', B: 'B-result' })
  const timer = nextTimer(s)
  return <div id="coordination-state">
    <section className={styles.metrics} aria-label="协调实验实时状态"><div><span>逻辑时间</span><strong data-testid="coordination-clock">{s.now} ms</strong></div><div><span>A 的实际状态</span><strong data-testid="coordination-truth">{processLabels[s.workers[0]!.status]}</strong></div><div><span>观察者对 A 的判断</span><strong data-testid="coordination-observation">{observationLabels[s.observations[0]!.status]}</strong></div>{showLease ? <div><span>资源当前值</span><strong data-testid="coordination-value">{s.resource.value}</strong></div> : <div><span>在途心跳</span><strong>{s.heartbeats.filter((h) => h.status === 'network').length}</strong></div>}</section>
    <div className={styles.advance}><button disabled={disabled || timer === null || timer > MAX_TIME} onClick={() => { if (timer !== null) act({ type: 'advance', ms: timer - s.now }) }}>推进下一时刻 {timer ?? '—'} ms</button>{[100, 500, 1000].map((ms) => <button key={ms} disabled={disabled || s.now + ms > MAX_TIME} onClick={() => act({ type: 'advance', ms })}>推进 {ms} ms</button>)}</div>
    <div className={styles.actors}>{s.workers.map((worker) => <section className={styles.actor} key={worker.id} aria-label={`Worker ${worker.id} 操作`}><h2>Worker {worker.id}</h2><p>真实状态：{processLabels[worker.status]} · {worker.connected ? '链路连通' : '链路分区'}</p><p className={styles.note}>进程世代 {worker.epoch} · 已发送序号 {worker.sequence}</p>
      <div className={styles.faultActions}>
        <button disabled={disabled || worker.status !== 'running'} onClick={() => act({ type: 'send-heartbeat', worker: worker.id })}>发送 {worker.id} 心跳</button>
        <button disabled={disabled || worker.status !== 'running'} onClick={() => act({ type: 'pause', worker: worker.id })}>暂停 {worker.id}</button>
        <button disabled={disabled || worker.status !== 'paused'} onClick={() => act({ type: 'resume', worker: worker.id })}>恢复 {worker.id}</button>
        <button disabled={disabled || worker.status === 'crashed'} onClick={() => act({ type: 'crash', worker: worker.id })}>崩溃 {worker.id}</button>
        <button disabled={disabled || worker.status !== 'crashed'} onClick={() => act({ type: 'restart', worker: worker.id })}>重启 {worker.id}</button>
        <button disabled={disabled || !worker.connected} onClick={() => act({ type: 'partition', worker: worker.id })}>分区 {worker.id}</button>
        <button disabled={disabled || worker.connected} onClick={() => act({ type: 'reconnect', worker: worker.id })}>连通 {worker.id}</button>
      </div>
      {showLease ? <><h3>本地持有权记忆</h3><p>{worker.localLease ? `token ${worker.localLease.token} · 到期 ${worker.localLease.expiresAt} ms${worker.localLease.expiresAt <= s.now ? '（已经过期）' : ''}` : '尚无本地租约'}</p><div className={styles.faultActions}><button disabled={disabled || worker.status !== 'running' || !worker.connected} onClick={() => act({ type: 'acquire', worker: worker.id })}>申请 {worker.id} 租约</button><button disabled={disabled || worker.status !== 'running' || !worker.connected || !s.lease || s.lease.owner !== worker.id || s.lease.token !== worker.localLease?.token || s.lease.expiresAt <= s.now} onClick={() => act({ type: 'renew', worker: worker.id })}>续租 {worker.id}</button></div>
        <label>准备写入的值<input aria-label={`${worker.id} 写入值`} value={values[worker.id]} maxLength={40} onChange={(event) => setValues({ ...values, [worker.id]: event.target.value })} /></label><button disabled={disabled || worker.status !== 'running' || !worker.connected || !worker.localLease || s.writes.length >= 20} onClick={() => act({ type: 'prepare-write', worker: worker.id, value: values[worker.id] })}>准备 {worker.id} 写入</button><p className={styles.note}>准备时检查本地租约；已经发出的包不会被过期检查撤回。</p></> : null}
    </section>)}<section className={styles.actor} aria-label="故障观察者"><h2>观察者的局部信息</h2>{s.observations.map((o) => <div className={styles.message} key={o.worker}><strong>{o.worker}：{observationLabels[o.status]}</strong><p>最近接收：{o.lastReceivedAt === null ? '无' : `${o.lastReceivedAt} ms`}<br />超时判定：{o.timeoutAt === null ? '已触发，等待新心跳' : `${o.timeoutAt} ms`}<br />已见世代 / 序号：{o.epoch} / {o.sequence}</p></div>)}<p className={styles.note}>观察者不读取真实进程状态；延迟的有效心跳可以暂时清除怀疑，即使节点实际已经崩溃。</p></section></div>
    <section className={styles.panel}><h2>心跳网络</h2><p className={styles.note}>运行的节点按 {config.intervalMs} ms 周期发送；消息需要手动递送，也可以丢弃或乱序递送。连通不代表消息自动到达。</p><div className={styles.tableScroll}><table aria-label="协调心跳表"><thead><tr><th>心跳</th><th>节点 / 世代 / 序号</th><th>发送时刻</th><th>状态</th><th>操作</th></tr></thead><tbody>{s.heartbeats.map((h) => <tr key={h.id}><th>{h.id}</th><td>{h.worker} / {h.epoch} / {h.sequence}</td><td>{h.sentAt} ms</td><td>{heartbeatLabels[h.status]}</td><td>{h.status === 'network' ? <><button disabled={disabled || !s.workers.find((w) => w.id === h.worker)!.connected} onClick={() => act({ type: 'deliver-heartbeat', heartbeatId: h.id })}>递送 {h.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-heartbeat', heartbeatId: h.id })}>丢弃 {h.id}</button></> : '—'}</td></tr>)}</tbody></table></div></section>
    {showLease ? <section className={styles.panel}><h2>授予者与资源端</h2><div className={styles.ledgers}><div><h3>权威租约记录</h3><p data-testid="coordination-lease">{s.lease ? `${s.lease.owner} · token ${s.lease.token} · ${s.lease.expiresAt > s.now ? '有效' : '已过期'}至 ${s.lease.expiresAt} ms` : '尚未授予租约'}</p></div><div><h3>资源已接受的最高世代</h3><p data-testid="coordination-token">{s.resource.highestToken}</p><p>Fencing {config.fencing ? '开启' : '关闭'} · 已拒绝 <strong data-testid="coordination-rejected">{s.writes.filter((w) => w.status === 'rejected').length}</strong> 次</p></div></div><div className={styles.tableScroll}><table aria-label="协调写入表"><thead><tr><th>消息</th><th>来自</th><th>token</th><th>值</th><th>结果</th><th>操作</th></tr></thead><tbody>{s.writes.map((w) => <tr key={w.id}><th>{w.id}</th><td>{w.worker}</td><td>{w.token}</td><td>{w.value}</td><td>{writeLabels[w.status]}</td><td>{w.status === 'network' ? <><button disabled={disabled || !s.workers.find((node) => node.id === w.worker)!.connected} onClick={() => act({ type: 'deliver-write', writeId: w.id })}>递送 {w.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop-write', writeId: w.id })}>丢弃 {w.id}</button></> : '—'}</td></tr>)}</tbody></table></div><p className={styles.note}>资源只拒绝低于已接受最高 token 的写入；它不会同步查询租约。新世代还没到达资源时，旧消息仍可能被接纳。同一 token 内的乱序需要额外保护。</p></section> : null}
    <EventTimeline events={s.events} actors={showLease ? actors : actors.slice(0, 3)} labels={labels} />
  </div>
}
