'use client'
import { ProtocolExperiment } from '../protocol/experiment'
import { EventTimeline } from '../protocol/event-timeline'
import { ConcurrentSession } from './session'
import { concurrentExercise, initialDraft, invariant, scenarioCommands, scenarioLabels, type Draft, type Scenario } from './lesson'
import { MAX_COMMANDS, runModel, strategyLabels, type Command, type Config, type State, type Strategy } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
const statusLabels = { idle: '等待读取', ready: '已有本地快照', waiting: '等待行锁', conflict: '版本冲突，需重读', 'sold-out': '无剩余名额', committed: '预订成功', crashed: '已崩溃', aborted: '已中止' }
const actors = [{ id: 'A', label: '任务 A' }, { id: 'store', label: '库存与预订' }, { id: 'B', label: '任务 B' }]
const eventLabels = { read: '读取快照', committed: '原子提交', conflict: '版本冲突', 'sold-out': '名额不足', 'lock-wait': '等待行锁', 'lock-granted': '获得行锁', unlock: '释放行锁', crashed: '进程崩溃', restarted: '重启', aborted: '事务中止', dedupe: '幂等重放' }
function Live({ d, s, act, disabled }: { d: Draft; s: State; act: (command: Command) => void; disabled: boolean }) {
  return <>
    <section className={styles.metrics} aria-label="并发实时状态"><div><span>剩余库存</span><strong data-testid="concurrent-remaining">{s.remaining}</strong></div><div><span>实际预订 / 总名额 {d.config.capacity}</span><strong data-testid="concurrent-reservations">{s.reservations.length}</strong></div><div><span>库存版本</span><strong>{s.version}</strong></div><div><span>业务不变量</span><strong data-testid="concurrent-invariant">{invariant(d.config, s) ? '成立' : '已违反'}</strong></div></section>
    <div className={styles.actors}>{s.workers.map((w) => <section className={styles.actor} key={w.id} aria-label={`任务 ${w.id}`}><h2>任务 {w.id} · 独立预订意图</h2><strong data-testid={`concurrent-${w.id}`}>{statusLabels[w.status]}</strong><p>本地读取：{w.snapshot ? `剩余 ${w.snapshot.remaining} / 版本 ${w.snapshot.version}` : '没有可提交快照'}</p><p>读取 {w.reads} 次 · 冲突 {w.conflicts} 次</p><div className={styles.faultActions}><button disabled={disabled || w.status === 'crashed' || w.status === 'waiting'} onClick={() => act({ type: 'read', worker: w.id })}>读取 {w.id}</button><button disabled={disabled || w.status !== 'ready'} onClick={() => act({ type: 'commit', worker: w.id })}>提交 {w.id}</button><button disabled={disabled || !['ready', 'waiting', 'idle', 'conflict'].includes(w.status)} onClick={() => act({ type: 'abort', worker: w.id })}>中止 {w.id}</button><button disabled={disabled || w.status === 'crashed'} onClick={() => act({ type: 'crash', worker: w.id })}>崩溃 {w.id}</button><button disabled={disabled || w.status !== 'crashed'} onClick={() => act({ type: 'restart', worker: w.id })}>重启 {w.id}</button></div></section>)}<section className={styles.actor}><h2>数据库当前事实</h2><p>锁持有者：<strong data-testid="concurrent-lock">{s.lock ?? '无'}</strong></p><p>等待者：{s.waiting.join('、') || '无'}</p><p>守恒：剩余 {s.remaining} + 预订 {s.reservations.length} = {s.remaining + s.reservations.length}；应为 {d.config.capacity}。</p><p className={styles.note}>数据库中的库存与预订一起提交。A、B 持有的旧快照不会自动更新；幂等键分别是 A 和 B。</p></section></div>
    <section className={styles.panel}><h2>实际预订记录</h2><div className={styles.tableScroll}><table aria-label="预订记录表"><thead><tr><th>预订</th><th>意图</th><th>提交前库存</th><th>提交后库存</th><th>新版本</th></tr></thead><tbody>{s.reservations.map((r) => <tr key={r.id}><th>{r.id}</th><td>{r.intent}</td><td>{r.before}</td><td>{r.after}</td><td>{r.version}</td></tr>)}</tbody></table></div><p className={styles.note}>应满足剩余 + 预订 = 初始名额，预订不得超卖，同一意图最多一份预订。只检查库存非负会漏掉错误。</p></section>
    <EventTimeline events={s.events} actors={actors} labels={eventLabels} />
  </>
}
export function ConcurrentLab() {
  return <ProtocolExperiment id="concurrent-update" title={concurrentExercise.title} summary={concurrentExercise.summary} conceptId="concurrency-control" createSession={() => new ConcurrentSession()} initial={initialDraft} scenarios={scenarioLabels}
    goals={{ 'last-slot': '让 A、B 都尝试读取最后一个名额，再提交。观察库存没有负数时，是否仍出现两份成功预订。用 CAS 或行锁保护不同意图的竞争。', 'lost-update': '初始有两个名额，两个任务都应完成。检查先读后写是否把同一个旧值写回两次，漏掉一次扣减。', 'crash-before-commit': 'A 读取后崩溃，B 继续提交，A 重启后重新判断。在行锁策略下观察等待者何时能获得锁。', manual: '自由安排读取、提交、中止、崩溃与重启。还可用同一意图重读，区分重复请求和不同事务的竞争；自由实验不计关卡进度。' }}
    selectScenario={(d, value) => ({ ...initialDraft(), scenario: value as Scenario, config: { ...d.config, capacity: value === 'lost-update' ? 2 : value === 'manual' ? d.config.capacity : 1 } })}
    runModel={runModel} guide={(d) => d.scenario === 'manual' ? [] : scenarioCommands(d.config, d.scenario)} commandLabel={(c) => `${({ read: '读取', commit: '提交', abort: '中止', crash: '崩溃', restart: '重启' })[c.type]} ${c.worker}`} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => { const change = (patch: Partial<Config>) => edit({ ...d, config: { ...d.config, ...patch }, commands: [] }); return <div className={styles.settings}><label>并发控制策略<select aria-label="并发控制策略" value={d.config.strategy} disabled={disabled} onChange={(e) => change({ strategy: e.target.value as Strategy })}>{Object.entries(strategyLabels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><label>同一意图去重<select aria-label="并发幂等保护" value={String(d.config.idempotent)} disabled={disabled} onChange={(e) => change({ idempotent: e.target.value === 'true' })}><option value="false">关闭</option><option value="true">开启：只去重相同意图</option></select></label><label>初始名额<select aria-label="初始名额" value={d.config.capacity} disabled={disabled} onChange={(e) => change({ capacity: Number(e.target.value) })}>{[1, 2, 3].map((n) => <option key={n} value={n}>{n}</option>)}</select></label></div> }}
    renderLive={(d, s, act, disabled) => <Live d={d} s={s} act={act} disabled={disabled} />}
    renderAnswers={(d, edit, disabled) => <div className={styles.answers}>{([['remainingAnswer', '剩余库存作答'], ['reservationsAnswer', '实际预订作答']] as const).map(([field, label]) => <label key={field}>{label}<input aria-label={label} inputMode="numeric" maxLength={5} value={d[field]} disabled={disabled} onChange={(e) => edit({ ...d, [field]: e.target.value })} /></label>)}<label>业务不变量<select aria-label="并发不变量作答" value={d.invariantAnswer} disabled={disabled} onChange={(e) => edit({ ...d, invariantAnswer: e.target.value })}><option value="">选择结论</option><option value="safe">守恒且没有超卖或重复意图</option><option value="broken">存在违反</option></select></label><label>为什么？<select aria-label="并发边界解释" value={d.reasonAnswer} disabled={disabled} onChange={(e) => edit({ ...d, reasonAnswer: e.target.value })}><option value="">选择解释</option><option value="different-boundaries">幂等去重相同意图；版本或锁保护不同事务的交错</option><option value="nonnegative">只要库存非负，预订就安全</option><option value="atomic">单次提交原子，就无需考虑旧快照</option></select></label></div>}
    compare={(d) => ({ headings: ['剩余', '预订', '冲突', '不变量'], rows: ([['先读后写', 'read-write', false], ['只开启幂等', 'read-write', true], ['版本 CAS', 'cas', true], ['行锁', 'row-lock', true]] as const).map(([label, strategy, idempotent]) => { const c = { ...d.config, strategy, idempotent }; const s = runModel(c, scenarioCommands(c, d.scenario as Exclude<Scenario, 'manual'>)); return { label, values: [s.remaining, s.reservations.length, s.workers.reduce((n, w) => n + w.conflicts, 0), invariant(c, s) ? '成立' : '违反'] } }) })}
    boundary={['concurrent-update-v1：两个独立预订意图、一行库存与符号预订表。每次成功提交都原子写入库存和预订；没有版本或锁的读写策略仍能违反并发不变量。CAS 将版本检查、库存更新、预订插入放在同一原子边界，冲突需重读。', '行锁由数据库持有至事务提交或中止，等待按 FIFO 授予。崩溃操作假定数据库已经识别会话结束并清理事务；真实网络分区可能延迟这一过程，本题不模拟故障检测时间、死锁、多行写偏斜、MVCC 或通用隔离级别。', '最多 60 个命令、12 份预订。所有动作逻辑瞬时，时序行表示交错，不表示数据库耗时。原子持久状态为模型前提；撤销回退教学操作，不是撤销已经完成的生产事务。']} />
}
