'use client'
import { useState } from 'react'
import { ProtocolExperiment } from '../protocol/experiment'
import { AnswerFields } from '../protocol/answer-fields'
import { EventTimeline } from '../protocol/event-timeline'
import { exercise, lesson, scenarioCommands, scenarios } from './lesson'
import { canDeliver, majority, MAX_COMMANDS, runModel, type Command, type Config, type NodeId, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
const messageLabels = { 'request-vote': 'RequestVote', vote: '投票回复', append: 'AppendEntries', 'append-result': '复制回复' }
function Live({ s, c, act, disabled }: { s: State; c: Config; act: (command: Command) => void; disabled: boolean }) {
  const [source, setSource] = useState<NodeId>('A'); const [target, setTarget] = useState<NodeId>('B'); const [value, setValue] = useState('v1')
  const leader = s.nodes.find((n) => n.id === source)
  const leaders = s.nodes.filter((n) => n.online && n.role === 'leader').map((n) => n.id).join(',') || 'none'
  return <><section className={styles.metrics}><div><span>自认 Leader 的在线节点</span><strong data-testid="raft-leaders">{leaders}</strong></div><div><span>曾确认提交的提案</span><strong data-testid="raft-committed">{s.acknowledged.length}</strong></div><div><span>安全性反例</span><strong data-testid="raft-violations">{s.violations.length}</strong></div><div><span>多数派门槛</span><strong>{majority(c)} / {c.size}</strong></div></section>
    <div className={styles.actors}>{s.nodes.map((n) => <section className={styles.actor} key={n.id}><h2>节点 {n.id} · term {n.term}</h2><strong data-testid={`raft-role-${n.id}`}>{n.role}</strong><p>{n.online ? '在线' : '崩溃'} · {n.isolated ? '网络隔离' : '链路可用'}<br />稳定投票：{n.votedFor ?? '无'} · 当前收票：{n.votes.join(', ') || '无'}<br />commitIndex：<span data-testid={`raft-index-${n.id}`}>{n.commitIndex}</span> · 已应用 {n.applied.length}</p><p>日志：<span data-testid={`raft-log-${n.id}`}>{n.log.map((e) => `${e.index}:${e.term}:${e.value}`).join(' → ') || '空'}</span></p><p>已应用：{n.applied.map((e) => e.value).join(' → ') || '无'}</p><div className={styles.faultActions}><button disabled={disabled || !n.online || n.role === 'leader'} onClick={() => act({ type: 'campaign', node: n.id })}>触发 {n.id} 选举超时</button><button disabled={disabled} onClick={() => act({ type: n.online ? 'crash' : 'restart', node: n.id })}>{n.online ? '崩溃' : '重启'} {n.id}</button><button disabled={disabled} onClick={() => act({ type: n.isolated ? 'heal' : 'isolate', node: n.id })}>{n.isolated ? '连通' : '隔离'} {n.id}</button></div></section>)}</div>
    <section className={styles.panel}><h2>追加提案与复制</h2><div className={styles.settings}><label>发送节点<select aria-label="Raft 发送节点" value={source} onChange={(e) => setSource(e.target.value as NodeId)}>{s.nodes.map((n) => <option key={n.id}>{n.id}</option>)}</select></label><label>提案值<input aria-label="Raft 提案值" value={value} maxLength={30} onChange={(e) => setValue(e.target.value)} /></label><label>复制目标<select aria-label="Raft 复制目标" value={target} onChange={(e) => setTarget(e.target.value as NodeId)}>{s.nodes.map((n) => <option key={n.id}>{n.id}</option>)}</select></label></div><div className={styles.faultActions}><button disabled={disabled || !leader?.online || leader.role !== 'leader' || s.proposals.length >= 10 || leader.log.length >= 8} onClick={() => act({ type: 'propose', node: source, value })}>追加并发送提案</button><button disabled={disabled || !leader?.online || leader.role !== 'leader' || source === target || !s.nodes.some((n) => n.id === target)} onClick={() => act({ type: 'replicate', from: source, to: target })}>重发复制或心跳</button></div><p className={styles.note}>节点是否隔离不改变其本地角色；发出的消息需要实际送达。当前任期提交后，日志前缀一并应用。</p></section>
    {s.violations.length ? <section className={styles.error} role="alert"><strong>实际执行出现安全性反例</strong><ul>{s.violations.map((v) => <li key={v}>{v}</li>)}</ul></section> : null}
    <section className={styles.panel}><h2>提案事实与复制证据</h2><div className={styles.tableScroll}><table aria-label="Raft 提案表"><thead><tr><th>提案</th><th>索引 / 任期 / 值</th><th>当前持有节点</th><th>曾确认提交</th></tr></thead><tbody>{s.proposals.map((p) => <tr key={p.id}><th>{p.id}</th><td>{p.index} / {p.term} / {p.value}</td><td>{s.nodes.filter((n) => n.log.some((e) => e.id === p.id)).map((n) => n.id).join(', ') || '已被未提交后缀替换'}</td><td>{s.acknowledged.includes(p.id) ? '是' : '未确认'}</td></tr>)}</tbody></table></div><p className={styles.note}>被替换的未提交提案仍保留在事实表中，不伪装成曾成功提交。旧任期多数复制被暂缓的记录：{s.oldMajorities.map((m) => `${m.node}/term${m.term}/index${m.index}`).join(', ') || '无'}。</p></section>
    <section className={styles.panel}><h2>在途消息与手动网络</h2><div className={styles.ledgers}>{s.messages.filter((m) => m.status === 'network').map((m) => <div className={styles.message} key={m.id}><strong>{m.id} · {messageLabels[m.type]}</strong><p>{m.from} → {m.to} · term {m.term}{m.type === 'append' ? ` · prev ${m.prevIndex}:${m.prevTerm} · entries ${m.entries.map((e) => e.value).join(', ') || '空'} · commit ${m.leaderCommit}` : m.type === 'vote' ? ` · ${m.granted ? 'YES' : 'NO'}` : m.type === 'append-result' ? ` · ${m.success ? `匹配到 ${m.matchIndex}` : '拒绝'}` : ` · last ${m.lastIndex}:${m.lastTerm}`}</p><div><button disabled={disabled || !canDeliver(s, m)} onClick={() => act({ type: 'deliver', messageId: m.id })}>递送 {m.id}</button><button disabled={disabled} onClick={() => act({ type: 'drop', messageId: m.id })}>丢弃 {m.id}</button><button disabled={disabled || s.messages.length >= 400} onClick={() => act({ type: 'duplicate', messageId: m.id })}>复制 {m.id}</button></div></div>)}</div></section>
    <EventTimeline timeUnit="step" events={s.events} actors={s.nodes.map((n) => ({ id: n.id, label: `节点 ${n.id}` }))} labels={{ sent: '发送 RPC', campaign: '选举超时', 'vote-granted': '授予投票', 'vote-denied': '拒绝投票', elected: '多数派选举成功', 'step-down': '退为 follower', proposed: '追加提案', 'append-accepted': '接受匹配前缀', 'append-rejected': '拒绝前缀', 'suffix-replaced': '替换冲突后缀', 'old-term-held': '暂缓旧任期提交', committed: '推进提交', applied: '应用条目', 'safety-violation': '安全性反例', crash: '崩溃', restart: '恢复', isolate: '隔离', heal: '连通', dropped: '丢弃消息' }} />
  </>
}
export function RaftLab() {
  return <ProtocolExperiment id={exercise.id} title={exercise.title} summary={exercise.summary} conceptId="consensus" createSession={() => lesson.session()} initial={lesson.initial} scenarios={scenarios}
    goals={{ 'split-vote': '先让所有节点同时在第一任期投自己，递送投票请求观察分票。再次触发 A 的本地超时，在新任期赢得多数票并提交一个条目。', minority: '隔离旧 Leader A，让它继续追加本地未提交提案。B/C 形成多数派并提交新值，恢复网络后检查旧 Leader 退位及提案状态。', 'conflict-repair': 'A 留下两条未提交后缀后崩溃。新 Leader 提交不同条目，再恢复 A，观察 prevIndex/prevTerm 检查、回退和后缀替换。', 'old-term': '使用五节点：旧任期条目在新 Leader 手中达到多数复制，但还没有本任期条目。再选出拥有更高日志任期的 Leader，核对为什么旧条目之前不能直接确认。错误提交规则会产生真实反例。', manual: '手工触发选举、递送/丢弃/复制 RPC，交错提案与故障。只检查当前有一个 Leader 不足以证明安全；自由实验不计挑战进度。' }}
    selectScenario={(d, scenario) => ({ ...lesson.initial(), scenario, config: { ...d.config, size: scenario === 'old-term' ? 5 : scenario === 'manual' ? d.config.size : 3 } })} runModel={runModel} guide={(d) => d.scenario === 'manual' ? [] : scenarioCommands(d.config, d.scenario)} commandLabel={(c) => 'messageId' in c ? `${c.type} ${c.messageId}` : c.type === 'replicate' ? `复制 ${c.from} → ${c.to}` : `${c.type === 'campaign' ? '选举超时' : c.type === 'propose' ? '追加提案' : c.type} ${c.node}`} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => { const update = (patch: Partial<Config>) => edit({ ...d, config: { ...d.config, ...patch }, commands: [] }); return <div className={styles.settings}><label>固定集群成员数<select aria-label="Raft 节点数" value={d.config.size} disabled={disabled} onChange={(e) => update({ size: Number(e.target.value) as 3 | 5 })}><option value={3}>3</option><option value={5}>5</option></select></label><label>推进提交的规则<select aria-label="Raft 提交规则" value={d.config.commitRule} disabled={disabled} onChange={(e) => update({ commitRule: e.target.value as Config['commitRule'] })}><option value="current-term">本任期条目达到多数，再提交前缀</option><option value="any-term">错误规则：仅按多数副本提交</option></select></label></div> }}
    renderLive={(d, s, act, disabled) => <Live key={d.config.size} s={s} c={d.config} act={act} disabled={disabled} />} renderAnswers={(d, edit, disabled) => <AnswerFields answers={d.answers} disabled={disabled} change={(answers) => edit({ ...d, answers })} fields={[{ id: 'leaders', label: '当前自认 Leader 作答（逗号分隔）' }, { id: 'committed', label: '曾确认提交的提案数作答' }, { id: 'violations', label: '安全性反例数作答' }, { id: 'reason', label: 'Raft 保证边界', options: [{ value: 'term-and-prefix', label: '任期、稳定投票、前缀匹配和本任期多数提交共同约束结果' }, { value: 'majority-only', label: '只要条目有多数份副本，任何任期都可直接提交' }] }]} />}
    compare={(d) => ({ headings: ['多数派选举次数', '曾确认提案', '旧任期暂缓', '安全性反例'], rows: (['current-term', 'any-term'] as const).map((commitRule) => { const c = { ...d.config, commitRule }; const s = runModel(c, scenarioCommands(c, d.scenario)); return { label: commitRule === 'current-term' ? 'Raft 本任期提交规则' : '错误的只数副本规则', values: [s.elections.length, s.acknowledged.length, s.oldMajorities.length, s.violations.length] } }) })}
    boundary={['raft-v1：固定三个或五个成员、RequestVote、AppendEntries 和逐条手动消息。任期、投票、日志稳定保存；应用状态与进度也一同持久保存，恢复据此保留提交进度。不存在真实服务器、磁盘或客户端 RPC；提交并应用后抽象为客户端收到确认。', '选举超时由用户显式触发，空 AppendEntries 是心跳；不模拟随机定时器、预投票、读取租约、成员变更、日志压缩或 InstallSnapshot。手动调度只用于研究安全性与条件下的进展，不用于得出故障恢复时间或性能数据。', '按不同成员计票；候选日志先比最后任期，再比长度。复制检查 prevIndex/prevTerm，确认匹配前缀；迟到失败不回退较新的复制进度。当前任期多数条目推进提交，前缀同时应用。错误规则仅用于反例，局部已提交冲突会显式报错并停止该冲突重试。', '最多 240 个命令、400 条消息、10 个提案及每节点八条日志。全局安全检查只观察事件，不替协议提供信息或选择 Leader；被隔离消息、未确认提案仍显示。通过有限实验不构成对所有调度的形式证明。']} />
}
