'use client'
import { ProtocolExperiment } from '../protocol/experiment'
import { ConfigurationFields, type ConfigurationField } from '../protocol/configuration-fields'
import { AnswerFields } from '../protocol/answer-fields'
import { choices, MAX_COMMANDS, runModel, type Config } from './model'
import { exercise, format, lesson, scenarioConfig, scenarios, script } from './lesson'
import styles from '../retry-idempotency/retry-lab.module.css'
const labels: Record<keyof typeof choices, string> = { users: '每日用户数', requestsPerDay: '每用户每日请求', peakFactor: '假设峰均比', readPercent: '读取比例（%）', responseBytes: '读取响应（bytes）', retentionDays: '记录保留天数', copies: '完整数据份数', computeSlots: '独立计算槽', storageSlots: '并行存储槽', bandwidthMbps: '共享响应带宽（Mbps）' }
const resources = { compute: '计算', storage: '存储', network: '响应网络' }
export function ResourceBudgetLab() {
  return <ProtocolExperiment id={exercise.id} title={exercise.title} summary={exercise.summary} conceptId="capacity-estimation" createSession={() => lesson.session()} initial={lesson.initial} scenarios={scenarios}
    goals={{ units: '区分每日用户、平均/峰值请求、逻辑数据与副本字节；先推导，再运行样本核对资源约束。', network: '固定 10 请求/s、读响应 1 MB。让全部样本的 p95 不超过 500 ms；比较只增加计算槽和增加共享带宽。', storage: '固定 20 请求/s、读响应 100 kB。让 p95 不超过 250 ms；检查增加计算槽是否改变存储排队。', manual: '自行修改需求和资源假设；结果用于推导与有限观察，不记挑战通过。' }}
    selectScenario={(_d, scenario) => ({ ...lesson.initial(), scenario, config: scenarioConfig(scenario) })} runModel={runModel} guide={() => script} commandLabel={c => c.type === 'derive' ? '展开单位与需求推导' : '观察 5 秒请求并排空'} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => <ConfigurationFields config={d.config} disabled={disabled} change={config => edit({ ...d, config, commands: [] })} fields={(Object.keys(choices) as (keyof typeof choices)[]).map(key => ({ key, label: labels[key], locked: d.scenario !== 'manual' && !['computeSlots', 'storageSlots', 'bandwidthMbps'].includes(key), choices: choices[key].map(value => ({ value, label: String(value) })) })) as ConfigurationField<Config>[]} />}
    renderLive={(d, s, act, disabled) => <>
      <section className={styles.panel}><h2>推导的来源与单位</h2>{s.estimate ? <><p>日请求量 = {d.config.users} × {d.config.requestsPerDay} = {s.estimate.dailyRequests}；平均 = 日请求量 / 86400 = {format(s.estimate.averageRps)} 请求/s；峰值假设 = 平均 × {d.config.peakFactor} = {format(s.estimate.peakRps)} 请求/s。</p><p>响应流量 = 峰值 × 平均响应字节 = {format(s.estimate.responseBytesPerSecond)} bytes/s = {format(s.estimate.responseMbps)} Mbps（8 bits/byte）。</p><p>新增写入 {format(s.estimate.dailyWrites)} 条/天 × 1000 bytes × {d.config.retentionDays} 天 = <strong data-testid="budget-logical">{format(s.estimate.logicalBytes / 1000000)} MB</strong>；{d.config.copies} 份完整副本 = <strong data-testid="budget-physical">{format(s.estimate.copiedBytes / 1000000)} MB</strong>。不含索引、日志、压缩或备份。</p><p>假设处理上限（请求/s）：{Object.entries(s.estimate.ceilings).map(([k,v]) => `${resources[k as keyof typeof resources]} ${format(v)}`).join('；')}。这只是固定成本下的上限，实际排队见下方。</p></> : <p>先展开推导，空结果不代表零需求。</p>}<button disabled={disabled} onClick={() => act({ type: 'derive' })}>重新推导</button><button disabled={disabled} onClick={() => act({ type: 'sample' })}>重新观察样本</button></section>
      <section className={styles.metrics}><div><span>实际样本请求</span><strong data-testid="budget-count">{s.requests.length}</strong></div><div><span>样本 p95</span><strong data-testid="budget-p95">{s.latencyP95Ms === null ? '—' : `${format(s.latencyP95Ms)} ms`}</strong></div><div><span>到达窗口内完成</span><strong>{s.completedInWindow}</strong></div><div><span>窗口平均在途</span><strong>{format(s.averageInFlight)}</strong></div></section>
      <section className={styles.panel}><h2>实际排队与前 20 条请求</h2><p>{Object.entries(s.maxWait).map(([k,v]) => `${resources[k as keyof typeof resources]}最长等待 ${format(v)} ms`).join('；')}</p><div className={styles.tableScroll}><table aria-label="资源等待账本"><thead><tr><th>请求</th><th>到达</th><th>计算等待</th><th>存储等待</th><th>网络等待</th><th>完成</th></tr></thead><tbody>{s.requests.slice(0,20).map(r => <tr key={r.id}><th>{r.id}</th><td>{format(r.arrival)}</td>{r.stages.map(stage => <td key={stage.resource}>{format(stage.startedAt - stage.queuedAt)}</td>)}<td>{format(r.finishedAt)}</td></tr>)}</tbody></table></div><p>表中时间单位 ms。全部请求参与统计；此处只截取展示。读写按每 10 条请求的固定比例序列生成，没有丢弃或截断需求。</p></section>
    </>}
    renderAnswers={(d, edit, disabled) => <AnswerFields disabled={disabled} answers={d.answers} change={answers => edit({ ...d, answers })} fields={[{ id: 'average', label: '平均请求率作答' }, { id: 'peak', label: '峰值请求率作答' }, { id: 'logical', label: '逻辑存储 MB 作答' }, { id: 'physical', label: '副本存储 MB 作答' }, { id: 'reason', label: '容量推导边界', options: [{ value: 'work-and-boundaries', label: '固定工作量和单位，检查实际瓶颈与观察窗口' }, { value: 'users', label: '用户数就是并发数，多加上游就能解决' }] }]} />}
    compare={d => ({ headings: ['p95 ms', '存储最长等待 ms', '网络最长等待 ms'], rows: [{ label: '当前资源', config: d.config }, { label: '只增加计算槽', config: { ...d.config, computeSlots: 4 } }, { label: '只增加存储槽', config: { ...d.config, storageSlots: 4 } }, { label: '只增加网络带宽', config: { ...d.config, bandwidthMbps: 800 } }].map(row => { const s = runModel(row.config, script); return { label: row.label, values: [s.latencyP95Ms === null ? '—' : format(s.latencyP95Ms), format(s.maxWait.storage), format(s.maxWait.network)] } }) })}
    boundary={['resource-budget-v1：1–1000 个均匀到达请求，计算每次 50 ms、存储每次 100 ms，响应通过一个共享 FIFO 链路。计算/存储各 1–4 个独立槽，三阶段不持有前一阶段资源；没有真实 CPU 调度、请求方向网络、TCP 或磁盘内部模型。', '峰均比和保留期是显式假设。读响应按所选字节、写入确认 1000 bytes，新增记录 1000 bytes，十进制 MB/Mbps。估算使用声明比例，有限账本按周期序列生成；不自动转换为完整容量规划或生产机器建议。', '实际窗口在途由每个请求与 5 秒窗口的重叠时间积分计算，不把瞬时峰值套进稳定态公式。样本后继续排空、全部记录完成；每次样本从空资源重跑，最多 8 步操作。']} />
}
