'use client'
import { useState } from 'react'
import { ProtocolExperiment } from '../protocol/experiment'
import { AnswerFields } from '../protocol/answer-fields'
import { EventTimeline } from '../protocol/event-timeline'
import { exercise, lesson, scenarioCommands, scenarios } from './lesson'
import { MAX_COMMANDS, runModel, type Command, type Config, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
const labels = { begun: '开始事务', 'wal-appended': '追加易失日志', 'wal-flushed': '日志刷盘', 'memory-applied': '内存应用', acknowledged: '客户端确认', checkpoint: '检查点落盘', backup: '复制快照', archive: '归档稳定日志', crash: '进程崩溃', 'lose-disk': '磁盘丢失', 'recovery-started': '开始恢复', 'redo-buffered': '读取未提交更新', redone: '重放提交', 'uncommitted-skipped': '跳过未提交事务', 'recovery-complete': '恢复完成', 'recovery-blocked': '恢复材料无效', corrupt: '归档损坏', remove: '归档缺失' }
function Live({ s, act, disabled }: { s: State; act: (command: Command) => void; disabled: boolean }) {
  const [delta, setDelta] = useState(1); const [backup, setBackup] = useState('backup-1'); const [archive, setArchive] = useState('archive-1'); const [target, setTarget] = useState(2)
  const online = s.phase === 'online' && s.restoredTarget === null
  const missing = s.acknowledgements.filter((a) => !s.applied.includes(a.transaction)).length
  return <><section className={styles.metrics}><div><span>当前可用值</span><strong data-testid="durable-value">{s.value ?? 'unavailable'}</strong></div><div><span>恢复/应用事务数</span><strong data-testid="durable-applied">{s.applied.length}</strong></div><div><span>曾确认但未恢复</span><strong data-testid="durable-missing">{missing}</strong></div><div><span>服务状态</span><strong data-testid="durable-phase">{s.phase}</strong></div></section>
    {s.error ? <p role="alert" className={styles.error}>{s.error}</p> : null}
    <div className={styles.actors}><section className={styles.actor}><h2>事务与易失内存</h2><p>当前事务：{s.active ? `${s.active.id} +${s.active.delta}` : '无'}<br />客户端已确认：{s.acknowledgements.map((a) => `${a.transaction}@${a.lsn}`).join(', ') || '无'}</p><label>本次增量<select aria-label="恢复实验增量" value={delta} onChange={(e) => setDelta(Number(e.target.value))}>{[1, 2, 3].map((n) => <option key={n}>{n}</option>)}</select></label><div className={styles.faultActions}><button disabled={disabled || !online || !!s.active || s.intentions.length >= 4} onClick={() => act({ type: 'begin', delta })}>开始一个事务</button><button disabled={disabled || !online || !s.active || s.active.updateLsn !== null} onClick={() => act({ type: 'append-update' })}>追加 update 日志</button><button disabled={disabled || !online || s.active?.updateLsn == null || s.active.commitLsn !== null} onClick={() => act({ type: 'append-commit' })}>追加 commit 日志</button><button disabled={disabled || !online || s.active?.commitLsn == null || s.active.applied} onClick={() => act({ type: 'apply' })}>应用到内存</button><button disabled={disabled || !online || !s.active?.applied} onClick={() => act({ type: 'ack' })}>向客户端确认</button></div></section>
      <section className={styles.actor}><h2>本地稳定存储</h2><p>数据页：{s.disk ? `${s.disk.value} / 恢复起点 ${s.disk.through}` : '磁盘已丢失'}<br />稳定 WAL：{s.wal.filter((r) => r.durable).length} 条<br />易失 WAL：{s.wal.filter((r) => !r.durable).length} 条</p><div className={styles.faultActions}><button disabled={disabled || !online} onClick={() => act({ type: 'flush-wal' })}>刷盘 WAL</button><button disabled={disabled || !online} onClick={() => act({ type: 'checkpoint' })}>安装数据检查点</button><button disabled={disabled || !online || s.backups.length >= 2} onClick={() => act({ type: 'backup' })}>备份磁盘快照</button><button disabled={disabled || !online || s.archives.length >= 2} onClick={() => act({ type: 'archive' })}>创建独立日志归档</button></div></section>
      <section className={styles.actor}><h2>故障与本地重放</h2><p>恢复游标：{s.recovery ? `${s.recovery.position} / ${s.recovery.records.length}，目标 LSN ${s.recovery.target}` : '无'}<br />已经恢复：{s.applied.join(', ') || '无'}</p><div className={styles.faultActions}><button disabled={disabled || s.phase === 'offline'} onClick={() => act({ type: 'crash' })}>模拟进程崩溃</button><button disabled={disabled || s.phase === 'online' || s.phase === 'recovering'} onClick={() => act({ type: 'restart' })}>从本地磁盘重启</button><button disabled={disabled || s.phase !== 'recovering'} onClick={() => act({ type: 'replay' })}>重放下一条记录</button><button disabled={disabled || !s.disk} onClick={() => act({ type: 'lose-disk' })}>模拟本地磁盘丢失</button></div></section></div>
    <section className={styles.panel}><h2>本地 WAL 与刷盘边界</h2><div className={styles.tableScroll}><table aria-label="持久日志表"><thead><tr><th>LSN</th><th>事务</th><th>类型</th><th>增量</th><th>保存位置</th></tr></thead><tbody>{s.wal.map((r) => <tr key={r.lsn}><th>{r.lsn}</th><td>{r.transaction}</td><td>{r.kind}</td><td>{r.delta}</td><td>{r.durable ? '稳定 WAL' : '易失缓冲'}</td></tr>)}</tbody></table></div></section>
    <section className={styles.panel}><h2>独立备份、归档与指定时点恢复</h2><p>{s.backups.map((b) => `${b.id}：值 ${b.snapshot.value} / LSN ${b.snapshot.through}`).join('；') || '尚无备份'}</p>{s.archives.map((a) => <p key={a.id}>{a.id}：{a.records.map((r) => `${r.lsn}${r.intact ? '' : '（损坏）'}`).join(', ') || '空归档'}</p>)}<div className={styles.settings}><label>备份<select aria-label="恢复备份" value={backup} onChange={(e) => setBackup(e.target.value)}>{['backup-1', 'backup-2'].map((id) => <option key={id}>{id}</option>)}</select></label><label>归档<select aria-label="恢复归档" value={archive} onChange={(e) => setArchive(e.target.value)}>{['archive-1', 'archive-2'].map((id) => <option key={id}>{id}</option>)}</select></label><label>目标提交 LSN<select aria-label="恢复目标 LSN" value={target} onChange={(e) => setTarget(Number(e.target.value))}>{Array.from({ length: 9 }, (_, n) => <option key={n}>{n}</option>)}</select></label></div><div className={styles.faultActions}><button disabled={disabled || s.phase === 'online' || s.phase === 'recovering' || !s.backups.some((b) => b.id === backup) || !s.archives.some((a) => a.id === archive)} onClick={() => act({ type: 'restore', backup, archive, target })}>从选定材料恢复</button><button disabled={disabled || !s.archives.find((a) => a.id === archive)?.records.some((r) => r.lsn === target)} onClick={() => act({ type: 'corrupt', archive, lsn: target })}>损坏选定归档记录</button><button disabled={disabled || !s.archives.find((a) => a.id === archive)?.records.some((r) => r.lsn === target)} onClick={() => act({ type: 'remove', archive, lsn: target })}>移除选定归档记录</button></div><p className={styles.note}>只改变教学模型中的材料。恢复到较早目标会有意排除后续已确认事务；它不是零数据损失的恢复。</p></section>
    <EventTimeline events={s.events} actors={[{ id: 'client', label: '客户端' }, { id: 'memory', label: '内存' }, { id: 'wal', label: '稳定 WAL' }, { id: 'disk', label: '数据页' }, { id: 'backup', label: '独立备份' }]} labels={labels} timeUnit="step" />
  </>
}
export function DurabilityLab() {
  return <ProtocolExperiment id={exercise.id} title={exercise.title} summary={exercise.summary} conceptId="durability-recovery" createSession={() => lesson.session()} initial={lesson.initial} scenarios={scenarios}
    goals={{ 'ack-loss': '提交并向客户端确认，然后立即崩溃。比较只依赖内存与确认前刷盘 WAL，确认曾承诺成功的事务是否恢复。', uncommitted: '先完成一个事务，再只写入第二个事务的 update 并刷盘，尚未提交就崩溃。重放时只应用完整提交。', checkpoint: '完成第一个事务后建立检查点，再完成第二个事务。重启后只重放检查点之后的提交，不能重复累计第一个事务。', 'point-in-time': '从初始快照和两个已提交事务的归档，只恢复到 LSN 2。解释为何客户端确认过的第二个事务会被有意排除。', 'damaged-archive': '保留两份独立归档，损坏第一份后模拟磁盘丢失。先观察恢复失败，再使用真实存在的完整备用归档恢复。', manual: '自由控制 WAL、提交、刷盘、快照和恢复输入；日志只含 update 不代表事务已经提交。自由实验只保存证据。' }}
    selectScenario={(d, scenario) => ({ ...lesson.initial(), scenario, config: d.config })} runModel={runModel} guide={(d) => d.scenario === 'manual' ? [] : scenarioCommands(d.config, d.scenario)} commandLabel={(c) => ({ begin: '开始事务', 'append-update': '追加 update', 'append-commit': '追加 commit', 'flush-wal': '刷盘 WAL', apply: '应用内存', ack: '客户端确认', checkpoint: '安装检查点', backup: '复制快照', archive: '归档日志', crash: '进程崩溃', restart: '启动恢复', replay: '重放记录', 'lose-disk': '模拟磁盘丢失', restore: '从备份恢复', corrupt: '损坏归档', remove: '移除归档' })[c.type]} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => <label>成功确认条件<select aria-label="持久确认策略" value={d.config.acknowledgement} disabled={disabled} onChange={(e) => edit({ ...d, config: { ...d.config, acknowledgement: e.target.value as Config['acknowledgement'] }, commands: [] })}><option value="memory">仅内存提交就确认</option><option value="wal">提交 WAL 刷盘后确认</option></select></label>}
    renderLive={(_d, s, act, disabled) => <Live s={s} act={act} disabled={disabled} />} renderAnswers={(d, edit, disabled) => <AnswerFields answers={d.answers} disabled={disabled} change={(answers) => edit({ ...d, answers })} fields={[{ id: 'value', label: '恢复后的值作答' }, { id: 'applied', label: '恢复事务数作答' }, { id: 'missing', label: '确认但未恢复数作答' }, { id: 'reason', label: '持久恢复边界', options: [{ value: 'durable-inputs', label: '按真实保存的快照、完整日志和目标边界恢复；确认清单不能修补数据' }, { value: 'memory', label: '只要客户端收到成功，重启就能恢复全部内存' }] }]} />}
    compare={(d) => ({ headings: ['恢复值', '客户端曾确认', '已恢复', '服务状态'], rows: (['memory', 'wal'] as const).map((acknowledgement) => { const c = { ...d.config, acknowledgement }; const s = runModel(c, scenarioCommands(c, d.scenario)); return { label: acknowledgement === 'memory' ? '内存确认' : 'WAL 刷盘确认', values: [s.value ?? 'unavailable', s.acknowledgements.length, s.applied.length, s.phase] } }) })}
    boundary={['durability-v1：四个以内的串行符号事务、易失 WAL 缓冲、稳定 WAL、数据检查点及两份独立备份/归档。update 和 commit 分别写入日志；redo-only 模型只在提交后应用值，不实现未提交脏页写回、undo、MVCC 或真实 fsync。', '检查点安装为模型原子步骤，先要求对应 WAL 前缀稳定；崩溃会丢弃内存和未刷盘日志。恢复按提交记录应用，缺失或损坏的目标范围进入失败状态。归档完整性是显式符号检查，不是现实文件格式或加密校验实现。', '指定时点恢复按提交 LSN 截断，安装恢复后的数据页；结果可再次重启核对，但本题不继续在新时间线上写入。目标之后的已确认事务被有意排除，不宣称 RPO=0 或真实 RTO。最多 120 个命令和 8 条本地 WAL 记录；事件单位为逻辑步。']} />
}
