'use client'
import { ProtocolExperiment } from '../protocol/experiment'
import { EventTimeline } from '../protocol/event-timeline'
import { OverloadSession } from './session'
import { initialDraft, overloadExercise, profileFor, scenarioCommands, scenarioLabels, type Draft, type Scenario } from './lesson'
import { MAX_COMMANDS, MAX_TIME, metrics, nextTimer, profileLabels, retryLabels, runModel, type Command, type Config, type Profile, type RetryPolicy, type State } from './model'
import styles from '../retry-idempotency/retry-lab.module.css'
const phaseLabels = { scheduled: '尚未到达', waiting: '等待客户端额度', active: '等待结果', success: '及时成功', expired: '超过截止期', cancelled: '停止前取消到达' }
const attemptLabels = { queued: '排队中', running: '执行中', completed: '实际完成', rejected: '容量拒绝', expired: '过期出队' }
const actors = [{ id: 'source', label: '原始需求' }, { id: 'client', label: '客户端' }, { id: 'queue', label: '队列' }, { id: 'server', label: '服务端' }]
const eventLabels = { offered: '原始请求到达', 'traffic-started': '启动固定需求', 'traffic-stopped': '停止新到达', 'client-admitted': '获得发送额度', 'attempt-sent': '发送尝试', enqueued: '接纳排队', rejected: '容量拒绝', 'work-started': '开始处理', 'work-completed': '实际完成', 'client-success': '及时成功', timeout: '等待超时', deadline: '总截止期已过', 'retry-scheduled': '安排重试', 'retry-budget': '停止新重试', 'stale-discarded': '过期出队', slow: '处理减速', recovered: '处理恢复', clock: '推进时间' }
function Trend({ s }: { s: State }) {
  const max = Math.max(1, ...s.samples.flatMap((p) => [p.queue, p.running, p.waiting]))
  const end = Math.max(1, s.now)
  const points = (key: 'queue' | 'running' | 'waiting') => s.samples.flatMap((p, i) => {
    const x = 50 + p.at / end * 700
    const current = `${x},${165 - p[key] / max * 125}`
    return i ? [`${x},${165 - s.samples[i - 1]![key] / max * 125}`, current] : [current]
  }).join(' ')
  return <section className={styles.panel}><h2>等待从哪里转移到哪里？</h2><div className={styles.diagram}><svg viewBox="0 0 800 210" role="img" aria-label="按逻辑时间展示队列、运行中和客户端等待数量，下方采样表提供数据"><line x1="50" x2="750" y1="165" y2="165" stroke="var(--border-bright)" /><text x="10" y="45" fill="var(--muted)" fontSize="12">{max}</text><text x="10" y="168" fill="var(--muted)" fontSize="12">0</text>{([['queue', '#087e98', '服务端排队'], ['running', '#9b6600', '执行中'], ['waiting', '#8853b3', '客户端等待']] as const).map(([key, color, label], i) => <g key={key}><polyline points={points(key)} fill="none" stroke={color} strokeWidth="2" /><text x={50 + i * 240} y="20" fill={color} fontSize="13">{label}</text></g>)}<text x="50" y="192" fill="var(--muted)" fontSize="12">0 ms</text><text x="750" y="192" textAnchor="end" fill="var(--muted)" fontSize="12">{s.now} ms</text></svg></div><p className={styles.note}>发送窗口将等待移到客户端，并不减少原始需求，也不重置截止期。队列只统计等待服务端执行的尝试。</p><details><summary>展开全部状态采样</summary><div className={`${styles.tableScroll} ${styles.eventTable}`}><table aria-label="过载采样表"><thead><tr><th>时刻</th><th>队列</th><th>执行中</th><th>客户端等待</th><th>累计尝试</th><th>及时成功</th></tr></thead><tbody>{s.samples.map((p, i) => <tr key={i}><td>{p.at} ms</td><td>{p.queue}</td><td>{p.running}</td><td>{p.waiting}</td><td>{p.attempts}</td><td>{p.successes}</td></tr>)}</tbody></table></div></details></section>
}
function Live({ s, d, act, disabled }: { s: State; d: Draft; act: (command: Command) => void; disabled: boolean }) {
  const m = metrics(s); const timer = nextTimer(s)
  return <>
    <section className={styles.metrics} aria-label="过载实时指标"><div><span>原始请求到达</span><strong data-testid="overload-offered">{m.offered}</strong></div><div><span>实际尝试（含重试）</span><strong data-testid="overload-attempts">{m.attempts}</strong></div><div><span>客户端及时成功</span><strong data-testid="overload-successes">{m.successes}</strong></div><div><span>服务端实际完成</span><strong data-testid="overload-completed">{m.completed}</strong></div></section>
    <section className={styles.panel}><div className={styles.heading}><h2>逻辑时间 <span data-testid="overload-clock">{s.now} ms</span></h2><span>之后开始的处理：{s.serviceMs} ms / 次 · 执行槽 {d.config.slots}</span></div><div className={styles.faultActions}><button className={styles.primary} disabled={disabled || s.started || s.roots.length > 8} onClick={() => act({ type: 'start' })}>启动固定 12 个请求</button><button disabled={disabled || !s.started || s.stopped} onClick={() => act({ type: 'stop-traffic' })}>停止新的原始到达</button><button disabled={disabled || s.roots.length >= 20} onClick={() => act({ type: 'submit' })}>注入一个原始请求</button><button disabled={disabled || s.serviceMs === 500} onClick={() => act({ type: 'slow' })}>处理减速到 500 ms</button><button disabled={disabled || s.serviceMs === 100} onClick={() => act({ type: 'recover' })}>恢复到 100 ms</button></div><div className={styles.advance}><button disabled={disabled || timer === null || timer > MAX_TIME || timer <= s.now} onClick={() => { if (timer !== null && timer > s.now) act({ type: 'advance', ms: timer - s.now }) }}>推进下一事件 {timer ?? '—'} ms</button>{[100, 200, 600, 1000].map((ms) => <button key={ms} disabled={disabled || s.now + ms > MAX_TIME} onClick={() => act({ type: 'advance', ms })}>推进 {ms} ms</button>)}<button disabled={disabled || s.now >= MAX_TIME} onClick={() => act({ type: 'advance', ms: MAX_TIME - s.now })}>推进到实验结束</button></div><p className={styles.note}>每次尝试等待 200 ms 后超时；服务端工作继续。恢复处理速度只影响随后开始的工作。</p></section>
    <div className={styles.actors}><section className={styles.actor}><h2>客户端知道什么</h2><p>等待发送额度 {m.waiting} 个原始请求</p><p>等待超时 {m.timeouts} 次 · 额外重试 {m.retries} 次</p><p>总截止期失败 <strong data-testid="overload-deadlines">{m.deadlines}</strong> 个请求</p><p className={styles.note}>及时成功按原始请求去重；重试次数不算新增用户需求。响应在这个模型中立即返回。</p></section><section className={styles.actor}><h2>接纳与排队</h2><p>当前队列 <strong data-testid="overload-queued">{m.queued}</strong> · 峰值 <strong data-testid="overload-peak">{m.peakQueue}</strong></p><p>容量拒绝 <strong data-testid="overload-rejected">{m.rejected}</strong> 次</p><p>过期出队 <strong data-testid="overload-expired">{m.expired}</strong> 次</p><p className={styles.note}>拒绝和过期出队分别计数；都不能记作成功。停止生产后，已接纳工作仍能持续排空。</p></section><section className={styles.actor}><h2>服务端实际做了什么</h2><p>执行中 {m.running} 次 · 已完成 {m.completed} 次</p><p>重复处理同一原始请求 {m.repeated} 次</p><p>执行槽实际占用 <strong data-testid="overload-busy">{m.busyMs} ms</strong></p><p className={styles.note}>工作是符号只读计算，每个尝试都消耗处理时间，不加入去重缓存。客户端不再等待，也可能仍有工作在执行。</p></section></div>
    <Trend s={s} />
    <section className={styles.panel}><h2>原始需求与客户端结果</h2><div className={styles.tableScroll}><table aria-label="过载原始请求表"><thead><tr><th>请求</th><th>到达 / 截止</th><th>客户端状态</th><th>尝试</th><th>首次实际完成</th><th>及时响应</th></tr></thead><tbody>{s.roots.map((r) => <tr key={r.id}><th>{r.id}</th><td>{r.arrival} / {r.deadline} ms</td><td>{phaseLabels[r.phase]}</td><td>{s.attempts.filter((a) => a.rootId === r.id).length}</td><td>{r.firstWorkAt === null ? '—' : `${r.firstWorkAt} ms`}</td><td>{r.successAt === null ? '—' : `${r.successAt} ms`}</td></tr>)}</tbody></table></div></section>
    <section className={styles.panel}><h2>每次尝试的去向</h2><p className={styles.note}>尝试 {m.attempts} = 完成 {m.completed} + 拒绝 {m.rejected} + 过期 {m.expired} + 排队 {m.queued} + 执行 {m.running}。</p><div className={`${styles.tableScroll} ${styles.eventTable}`}><table aria-label="过载尝试表"><thead><tr><th>尝试</th><th>原始请求 / 次数</th><th>发送时刻</th><th>等待超时</th><th>实际状态</th><th>执行时间</th></tr></thead><tbody>{s.attempts.map((a) => <tr key={a.id}><th>{a.id}</th><td>{a.rootId} / {a.number}</td><td>{a.sentAt} ms</td><td>{a.timeoutObserved ? '已发生' : '未发生'}</td><td>{attemptLabels[a.status]}</td><td>{a.startedAt === null ? '未开始' : `${a.startedAt} → ${a.finishAt} ms`}</td></tr>)}</tbody></table></div></section>
    <EventTimeline events={s.events} actors={actors} labels={eventLabels} />
  </>
}
export function OverloadLab() {
  return <ProtocolExperiment id="overload" title={overloadExercise.title} summary={overloadExercise.summary} conceptId="overload-control" createSession={() => new OverloadSession()} initial={initialDraft} scenarios={scenarioLabels}
    goals={{ 'retry-storm': '固定一个执行槽和 12 个原始请求，0 ms 减速、600 ms 恢复。让全部请求及时成功，并比无保护立即重试减少尝试和执行时间；不能减少需求或增加容量。', 'bounded-burst': '12 个请求同时到达。让全部及时成功，服务端队列峰值不超过 2，额外重试不超过 24。考虑把等待放在客户端，而不是让所有重试挤进队列。', 'expired-work': '全部请求只有 800 ms 总截止期，服务先减速再恢复。观察至少一个及时成功与一个迟到完成，丢弃排队中过期工作，确保截止后不启动新工作。', manual: '自由安排原始请求、减速、恢复和时间推进。停止新到达后，观察队列与重试如何继续；自由操作只保存证据，不自动计为关卡通过。' }}
    selectScenario={(d, scenario) => ({ ...initialDraft(), scenario: scenario as Scenario, config: { ...d.config, profile: scenario === 'manual' ? d.config.profile : profileFor(scenario) } })}
    runModel={runModel} guide={(d) => d.scenario === 'manual' ? [] : scenarioCommands(d.scenario)} commandLabel={(c) => c.type === 'advance' ? `推进 ${c.ms} ms` : ({ start: '启动原始需求', 'stop-traffic': '停止新到达', submit: '注入请求', slow: '处理减速', recover: '恢复处理速度' })[c.type]} maxCommands={MAX_COMMANDS}
    renderConfig={(d, edit, disabled) => { const change = (patch: Partial<Config>) => edit({ ...d, config: { ...d.config, ...patch }, commands: [] }); return <div className={styles.settings}><label>原始需求<select aria-label="过载需求配置" value={d.config.profile} disabled={disabled} onChange={(e) => change({ profile: e.target.value as Profile })}>{Object.entries(profileLabels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><label>重试策略<select aria-label="过载重试策略" value={d.config.retry} disabled={disabled} onChange={(e) => change({ retry: e.target.value as RetryPolicy })}>{Object.entries(retryLabels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><label>每请求最多尝试<select aria-label="过载尝试预算" value={d.config.maxAttempts} disabled={disabled} onChange={(e) => change({ maxAttempts: Number(e.target.value) })}>{[1, 2, 3, 5].map((v) => <option key={v} value={v}>{v} 次</option>)}</select></label><label>服务端队列上限<select aria-label="过载队列上限" value={d.config.queueLimit} disabled={disabled} onChange={(e) => change({ queueLimit: Number(e.target.value) })}>{[0, 2, 8, 60].map((v) => <option key={v} value={v}>{v} 份等待尝试</option>)}</select></label><label>客户端未获结果窗口<select aria-label="客户端发送窗口" value={d.config.senderLimit} disabled={disabled} onChange={(e) => change({ senderLimit: Number(e.target.value) })}>{[0, 1, 2, 4].map((v) => <option key={v} value={v}>{v ? `${v} 个原始请求` : '不限制'}</option>)}</select></label><label>出队检查总截止期<select aria-label="过期工作检查" value={String(d.config.discardExpired)} disabled={disabled} onChange={(e) => change({ discardExpired: e.target.value === 'true' })}><option value="false">继续执行已接纳工作</option><option value="true">丢弃未开始的过期工作</option></select></label><label>执行槽<select aria-label="过载执行槽" value={d.config.slots} disabled={disabled} onChange={(e) => change({ slots: Number(e.target.value) })}>{[1, 2].map((v) => <option key={v} value={v}>{v} 个（挑战固定为 1）</option>)}</select></label><label>重试抖动种子<select aria-label="过载抖动种子" value={d.config.seed} disabled={disabled} onChange={(e) => change({ seed: Number(e.target.value) })}>{[17, 83, 351].map((v) => <option key={v} value={v}>{v}</option>)}</select></label></div> }}
    renderLive={(d, s, act, disabled) => <Live d={d} s={s} act={act} disabled={disabled} />}
    renderAnswers={(d, edit, disabled) => <div className={styles.answers}>{([['offeredAnswer', '原始到达数作答'], ['attemptsAnswer', '实际尝试数作答'], ['successAnswer', '及时成功数作答'], ['workAnswer', '服务端完成数作答']] as const).map(([field, label]) => <label key={field}>{label}<input aria-label={label} inputMode="numeric" maxLength={5} value={d[field]} disabled={disabled} onChange={(e) => edit({ ...d, [field]: e.target.value })} /></label>)}<label>如何解释这些数字？<select aria-label="过载边界解释" value={d.reasonAnswer} disabled={disabled} onChange={(e) => edit({ ...d, reasonAnswer: e.target.value })}><option value="">选择解释</option><option value="work-and-outcome">原始请求、尝试、客户端结果和服务端工作分别计数</option><option value="timeout-cancels">客户端超时会取消服务端工作</option><option value="empty-success">队列清空代表所有请求及时成功</option></select></label></div>}
    compare={(d) => ({ headings: ['原始到达', '尝试', '及时成功', '峰值队列', '实际完成', '执行槽占用 ms'], rows: [
      { label: '立即重试，大队列', patch: { retry: 'immediate' as const, senderLimit: 0, queueLimit: 60, discardExpired: false } },
      { label: '仅指数退避', patch: { retry: 'backoff' as const, senderLimit: 0, queueLimit: 60, discardExpired: false } },
      { label: '仅限制队列为 2', patch: { retry: 'immediate' as const, senderLimit: 0, queueLimit: 2, discardExpired: false } },
      { label: '退避 + 单请求窗口 + 过期检查', patch: { retry: 'backoff' as const, senderLimit: 1, queueLimit: 2, discardExpired: true } },
    ].map(({ label, patch }) => { const s = runModel({ ...d.config, ...patch }, scenarioCommands(d.scenario as Exclude<Scenario, 'manual'>)); const m = metrics(s); return { label, values: [m.offered, m.attempts, m.successes, m.peakQueue, m.completed, m.busyMs] } }) })}
    boundary={['overload-v1：固定到达的符号只读工作、客户端窗口、一个 FIFO 队列与 1–2 个执行槽。每个尝试独立消耗处理时间，不模拟业务写入、幂等缓存、网络丢包、熔断或分布式限流。拒绝表示本模型的接纳失败，不冒充某厂商协议。', '正常处理 100 ms，减速后新开始的工作 500 ms；运行中的工作保留开始时的耗时。尝试等待 200 ms；根请求截止期为原始到达 + 3,000 ms，短截止场景为 + 800 ms。发送窗口中的等待也消耗截止期。完成响应在边界先于截止判断；截止时尚未开始的工作可出队丢弃，不能中止在途处理。', '退避为 400/800/1,600 ms，上限 1,600；抖动额外增加由根请求、尝试号和种子决定的 0–200 ms。每个原始请求最多 1/2/3/5 次尝试。成功或总截止期停止新重试，不撤销已有工作；停止原始到达也不会停止排空。', '每次最多 20 个原始请求、100 次尝试、100 个命令和 10,000 ms。所有计数从实际事件和状态计算；采样按事件产生，不能把图形间距当作实际网络传输。队列上限不是处理能力，拒绝全部或少发请求都不能通过挑战。']} />
}
