import { createProtocolLesson } from '../../../core/experiments/protocol-lesson'
import { defaultConfig,MAX_COMMANDS,parseCommand,parseConfig,runModel,violations,type Command,type Config } from './model'
export const exercise={id:'authorization-boundaries',kind:'protocol' as const,version:1,title:'已经登录，就能读取这个对象吗？',category:'安全与资源隔离',difficulty:'基础',estimatedMinutes:20,summary:'实际读取私有对象，比较身份检查、对象授权、过粗缓存键和撤销后的旧授权。',flow:['核对主体与对象','授权并缓存','撤销或换对象','检查实际数据返回']}
export const scenarios={ownership:'身份与对象授权',revocation:'撤销后的旧授权',scope:'授权缓存的键',manual:'自由授权实验'}
export const scenarioConfig=(scenario:string):Config=>scenario==='ownership'?defaultConfig():{...defaultConfig(),check:'resource',key:scenario==='scope'?'user':'resource'}
export function script(scenario:string):Command[]{if(scenario==='manual')return [];const read:Command={type:'read',user:'alice',resource:'a'};return scenario==='revocation'?[read,read,{type:'revoke',user:'alice',resource:'a'},read,{type:'read',user:'bob',resource:'b'}]:[read,read,{type:'read',user:'alice',resource:'b'},{type:'read',user:'bob',resource:'b'}]}
export const lesson=createProtocolLesson({id:exercise.id,versions:{model:'authorization-boundaries-v1',definition:1,assessment:1},initialConfig:defaultConfig,scenarios,maxCommands:MAX_COMMANDS,parseConfig,parseCommand,runModel,
  assess:(d,s)=>{const wrong=violations(s);const fixed=d.scenario!=='manual'&&JSON.stringify(d.commands)===JSON.stringify(script(d.scenario));return {task:fixed&&s.observations.length===4&&!wrong.length&&s.observations.some(o=>o.allowed&&o.expected),expected:{reads:String(s.observations.length),wrong:String(wrong.length),checks:String(s.policyChecks),reason:'resource-and-revocation'},messages:[`实际读取 ${s.observations.length} 次，错误决定 ${wrong.length} 次，其中错误放行 ${wrong.filter(o=>o.allowed).length} 次。`,`完整权威授权检查 ${s.policyChecks} 次；版本查询未计入该计数，不代表零网络成本。`,'身份、对象、授权动作和当前策略共同决定许可；缓存键与撤销策略也是授权路径的一部分。','已经交付给客户端的内容不会因为撤销而消失；本关检查撤销之后的新请求。',fixed?'保持了所有合法与非法访问。':'必须执行原合法/非法请求，拒绝全部或省略越权请求不能通过。']}}
})
